travis-ci/travis-web

- assets/scripts/app/templates/settings/index.hbs
My understanding is that this setting is actually a value used to control job concurrency, not build concurrency, so this clarifies that by referring to jobs instead of builds.
I realise there are other places this is used, such as `maximum_number_of_builds` in the CLI and elsewhere, but this change was more within my grasp. :)
> Rename 'Concurrent builds' setting to 'Concurrent jobs'

- app/routes/main/recent.coffee
- app/store.coffee
- app/utils/auth.coffee
- testem.json
If user is logged in and doesn't keep 'recent repositories' tab opened, most of
the pusher events from 'common' channel are useless.
This commit introduces a logic to reject pusher events if:
* recent tab hasn't been opened
* user is signed in
* Travis CI for open source is used
* repository for a given event is not yet in store
* repository for a given event is not part of current user's repositories
> Don't save data from pusher that won't likely be used

- app/templates/builds.hbs
It's correct when you navigate to the individual build:
> Fix a small spelling mistake: committed (on build listing pages)

- app/models/build.coffee
- app/models/repo.coffee
So that builds triggered via API can be found on the build history for the time being.
/cc @drogus @rkh
> Add eventType as an attribute, include api builds to the history

- app/templates/top.hbs
Simply deleted the list item in the drop down menu
> remove link to stack overflow in help menu

- app/templates/home-pro.hbs
It's normally written as Xcode and not XCode.
> Fix Xcode typo on landing page

- app/templates/components/build-header.hbs
While a job is running, on the job status view, the duration is labeled: "Running for x sec". When the job finishes, 'Running' is swapped for 'Total time'. But "Total time for x sec" doesn't make any sense. the " for" should be part of the conditional with "Running"
> Fix grammatical error for finished job duration

- app/templates/components/log-content.hbs
Very minor change - tested on staging, all is good.
> remove "Legacy" from "Precise builds" in log-content message

- app/templates/components/build-header.hbs
- app/templates/components/builds-item.hbs
- app/templates/components/jobs-item.hbs
- app/templates/components/landing-row.hbs
- app/templates/components/repos-list-item.hbs
- app/templates/components/running-jobs.hbs
Sample of using the `time` element instead of `abbr` for displaying timestamps.
The `time` element can also represent durations. So the sample used here is suboptimal. Rather than the duration time lising the `lastBuildStartedAt` time in the `datetime` attribute, it ought to be a [valid `duration` value](https://www.w3.org/html/wg/drafts/html/master/infrastructure.html#valid-duration-string). However, I didn't see any existing helpers for formatting according to a machine-readable duration value.
Ideally, the `time` element would be used in other areas where times/durations are displayed. This pr is meant as a starting point for discussion.
> Leverage <time> element

- app/router.js
- config/deprecation-workflow.js
The use of `resource` within the router is deprecated as of 2.0.0
(as noted in `deprecation-workflow.js`).
This uses ember-watson to do the manual conversion to `route`, with small
aesthetic tweaks.
> Remove resource router deprecations

- package.json
Upgading ember-cli-autoprefixer to 0.5.0 removes the deprecation
messages from the build output (these were targeted for removal
in 0.4.0).
There are no noticable side effects, but this version does package
the most recent version of postcss/autoprefixer. The release notes
for that version can be found
[here](https://github.com/postcss/autoprefixer/releases/tag/6.0.0).
> Remove autoprexifer deprecations

- app/components/repos-list-item.js
- app/mixins/scroll-reset.js
- app/routes/repo.js
An [issue](https://github.com/travis-ci/travis-ci/issues/5181) was reported in
which the repository sidebar links were not functioning as expected. I've
tracked it down to the fact that a click handler was registered and
automatically performing a redirect to the repo route.
As reported, this breaks CMD+Click behavior (as the click handler was still
called and navigating when the user did not expect it). It also breaks normal link
behavior as it would take the user to a URL they did not intend to visit.
This commit simply removes that click handler. I checked the previous
coffee version of the file to gain more context on why it was initially
added, but unfortunately, it was simply added when the original
component was created, so I'm not sure what its use was.
If there is known behavior …
> Remove click handler overriding default link behavior

- app/templates/components/builds-item.hbs
- app/templates/components/requests-item.hbs
This removes the warnings and should clean up the test output (especially in CI) quite a bit.
> Remove legacy binding deprecation warnings

- app/utils/keys-map.js
I believe this should fix the "no language set" message seen at https://travis-ci.org/jimhester/travis-test/builds/109884131
Let me know if there is something else which needs to be done
> Add R language key for matrix column

- waiter/config.ru
- waiter/lib/travis/web/app.rb
this fixes live log updates on enterprise (also, removes one trailing space, ha!)
> pass through Env.pusher.channelPrefix for enterprise

- app/utils/status-image-formats.js
Some POD parsers recognize only lowercase format names.
For e.g., pod2markdown fails to generate a markdown file with the status image if the format is 'HTML'
> fix image format for POD

- app/helpers/pretty-date.js
See https://github.com/moment/moment/issues/1407 for more details. All that was needed was to manually instantiate a new Date() object
> Remove moment deprecation on builds page

- app/templates/top.hbs
This shortens the broadcast copy and makes more sense grammatically
> Shorten broadcast copy

- app/styles/app/vars.sass
The contrast of the green, red and yellow highlight colors was too low.
Before:
After:
> Improve contrast of the highlight ansi colors

- .travis.yml
See the logs here:
https://travis-ci.org/travis-ci/travis-web/jobs/124193154
> DEPRECATION: tryCmd command is deprecated in favor of `ember try:one`.
> Example: `ember try default-scenario serve --port 4201`, becomes:
> `ember try:one default-scenario --- ember serve --port 4201`
This deprecation came along with @clekstro’s recent package updates. Harder to see because it’s only a CLI thing.
> Fix ember-try deprecation

- app/utils/keys-map.js
display the `smalltalk_config` key (which is expanded to a matrix) in the web, so you can distinguish the builds
see https://github.com/travis-ci/travis-build/pull/689
fix https://github.com/hpi-swa/smalltalkCI/issues/128
cc @fniephaus
> show smalltalk config matrix expansion key

- .travis.yml
It’s not currently being used and it’s limiting the number of concurrent builds, so this disables it until we want to start using it again.
> Disable Sauce Connect

- .travis.yml
This doesn't appear to be necessary in other projects I've encountered
recently, so removing it to see if it makes any difference. If nothing
breaks, it shortens our build config at the very least.
> Avoid building phantom.js from source

- .travis.yml
This will still show a failure/stacktrace at the end of our builds, meaning it simply cuts down on the noise
of our passing tests
> Use dot reporter within CI for shorter logs

- app/styles/app/layouts/log.sass
- app/styles/app/modules/icons.sass
- app/styles/app/modules/tabs.sass
A newer version of node-sass was released and it caused build errors related to these `@extend`s. This removes two uses of `@extend` that didn’t actually extend anything that existed. The other change is syntactic: a missing space was causing the parent selector to have nothing defined within it.
> Fix Sass extend problems

- tests/.jshintrc
- tests/acceptance/builds/restart-test.js
- tests/acceptance/profile-test.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/start-app.js
- tests/helpers/store-user-session.js
In preparation for my next acceptance test, I extracted a `storeUserSession` test helper and added the clearing of `localStorage` to the `afterEach` of all acceptance tests. This will reduce boilerplate.
This is pretty simple so I’ll probably just merge after the tests have passed, but let me know if you’d prefer a name other than `storeUserSession` or anything else?
> Extract test session setup and teardown

- .travis.yml
[This build](https://travis-ci.org/travis-ci/travis-web/jobs/126038516) failed with a warning about Node 6 and Ember CLI, so let’s revert to 5.X for now.
> Revert to Node 5.X

- app/services/raven.js
- tests/unit/services/raven-test.js
The error reporting was necessary to introduce, but the volume of errors has already become unwieldy.
This does two things:
1) implements a whitelist to swallow exceptions that are not really problems (e.g. transition aborted)
2) only report 10% of errors to reduce the volume (as recommended by Sentry)
> Limit Sentry error reporting

- app/components/branch-row.js
- app/components/dashboard-row.js
- app/components/log-content.js
- app/components/not-active.js
- app/components/repo-show-tools.js
- app/controllers/repo.js
- app/controllers/repos.js
- app/routes/application.js
- app/services/auth.js
- app/services/flashes.js
- app/services/permissions.js
- app/utils/permission.js
- mirage/config.js
- tests/acceptance/auth/automatic-sign-out-test.js
- tests/acceptance/profile-test.js
- tests/helpers/sign-in-user.js
- tests/pages/auth.js
- tests/unit/services/flashes-test.js
- tests/unit/services/permissions-test.js
- tests/unit/utils/permission-test.js
This is still WIP, but I wanted to create a PR already.
This is meant to fix the problem with long page when fetching user data takes longer. Originally we didn't check user data when page was loaded. Instead, we were relying on user data set in local storage. If user's token was invalid, some of the requests would fail and we would log user out. This led to some problems and recently I changed the strategy to always check user data when the app starts. The problem is that if loading user data takes long time, a user will see a blank page. We could of course put a spinner there, but I think that we could also get back to the old strategy and load user data in background. This will require a few tweaks in the code to handle some situations better, but it will allow people to use the site …
> Don't wait for downloading user data when opening the app

- ember-cli-build.js
Not sure if this is ideal or not, but this fixes https://github.com/travis-pro/travis-enterprise/issues/116.  We're now able to build and deploy enterprise again.
> Fix fingerprinting for Enterprise

- app/components/build-header.js
- app/components/repos-list.js
- app/controllers/repos.js
- app/models/hook.js
- app/routes/getting-started.js
- app/routes/main.js
- app/routes/main/repositories.js
- app/templates/build.hbs
- app/templates/getting-started.hbs
- mirage/config.js
- tests/acceptance/registration/getting-started-test.js
- tests/index.html
- tests/pages/dashboard.js
- tests/pages/header.js
This solves a few issues for new users enabling their first
repositories. Currently, when a user enables their first repository and
subsequently navigates to the dashboard, they do not see any
repositories. This was causing some unexpected errors that made certain
portions of the page unrenderable and led to divergent behavior between
the initial page visit and a refresh (where the data would, of course,
be accurate).
This is because we were missing a link between the state of the store
for repository models and making requests to the /hooks endpoint which
enable them on the backend. To fix this, we now manually inject a
repository model into the store, as the id between a hook and a repo is
shared.  This ensures that code querying the store will get the proper
result.
I think this …
> Persist repository state when enabling repositories

- app/services/raven.js
Stop gap until we make a final decision on how to proceed.
> Disable Sentry logging for Enterprise

- app/templates/components/repos-empty.hbs
We used to use campfire, but now we no longer do.
> Remove reference to campfire on empty-repos page

- config/environment.js
- mirage/config.js
- mirage/factories/ssh-key.js
- mirage/models/repository.js
- mirage/models/ssh-key.js
- tests/acceptance/repo-settings-test.js
- tests/pages/settings.js
This is a continuation of my [previous acceptance test](https://github.com/travis-ci/travis-web/pull/540), where I noticed when I wrapping up work on it that I’d missed assertions for SSH keys. It’s still somewhat mysterious to me how all this works and what the two different key endpoints are about, but hopefully I’ll learn that during this exercise.
> Settings acceptance test: keys

- app/router.js
Since I enabled SSH keys in the test environment, I was seeing a lot of deprecation warnings about this. It appears to be unused? Do you agree, @drogus?
> Remove unused route

- .travis.yml
Per https://github.com/travis-ci/travis-ci/issues/3039#issuecomment-119302093 it looks like the md5deep branch has been deployed, so this line is not needed ...
> Remove unneeded branch line for cache

- app/styles/app/modules/tooltips.sass
> Make jobs tooltip wider

- app/app.js
- app/components/helpscout-link.js
- app/index.html
- app/styles/app.scss
- app/styles/app/modules/helpscout-link.sass
- app/templates/components/helpscout-link.hbs
- app/templates/layouts/home.hbs
- app/templates/layouts/profile.hbs
- app/utils/init-hs-beacon.js
The HS beacon was not flexible enough styling-wise.
We're switching to the modal that let's us style an element
of our choosing to open the form.
Also updated the mascot in the noscript tag
> change from HS beacon to modal

- app/controllers/settings.js
- app/templates/components/add-cron-job.hbs
- app/templates/settings.hbs
This PR limits the availabe branches in the dropdown box to branches without crons. 
(branches on which you can create a new cron job)
To edit a cron job a user currently creates a new cron on the same branch thus overriding the old one. That is unintuitive and not documented.
> dropdown menu only lists cron-free branches

- app/styles/app/modules/helpscout-link.sass
so it won't cover the `top` link in the logs
> move helpscout link to the left

- app/initializers/configure-inflector.js
As I mentioned [here](https://github.com/travis-ci/travis-web/pull/598#issuecomment-231853066), `master` is failing to deploy. This is an experimental branch to see why this might be happening. Since the Javascript error relates to initialisers, I’m removing the one I added recently. This will cause the tests to fail, but I can force a deployment to staging.
> Debug site launch failure

- app/components/branch-row.js
- app/components/dashboard-row.js
I came across this while looking for code that would be improved by `ember-concurrency`. Could it truly be unused?? Thoughts, @lislis, @drogus, and/or @clekstro? I don’t see the `tiggerBuild` action being called anywhere, nor the `triggerBuild` non-action and the `canTrigger` property. A legacy of removed code perhaps?
> Remove unused code

- app/components/add-cron-job.js
- app/components/add-env-var.js
- app/components/add-ssh-key.js
- app/components/caches-item.js
- app/components/cron-job.js
- app/components/env-var.js
- app/components/limit-concurrent-builds.js
- app/components/no-builds.js
- app/components/not-active.js
- app/components/settings-switch.js
- app/components/ssh-key.js
- app/controllers/caches.js
- app/templates/caches.hbs
- app/templates/components/add-cron-job.hbs
- app/templates/components/add-env-var.hbs
- app/templates/components/add-ssh-key.hbs
- app/templates/components/caches-item.hbs
- app/templates/components/cron-job.hbs
- app/templates/components/env-var.hbs
- app/templates/components/limit-concurrent-builds.hbs
- app/templates/components/no-builds.hbs
- app/templates/components/not-active.hbs
- app/templates/components/settings-switch.hbs
- app/templates/components/ssh-key.hbs
- app/templates/env-vars.hbs
- package.json
So far, I’ve added `task`s in some obvious places, by searching for `this.get('is`, which usually signifies that a flag is being set and checked to prevent duplicate firing of asynchronous events, such as updates and deletes. You can see that `ember-concurrency` reduces the boilerplate around this pattern.
(Some of the line savings and shortening is because I’m replacing things with template strings too. 😁)
It would likely be useful elsewhere in the codebase, but for now I’ll just clean up some of the simple cases.
> Add ember-concurrency

- .travis.yml
- app/components/builds-wrapper.js
- app/components/repo-show-tabs.js
- app/controllers/builds.js
- app/router.js
- app/routes/crons.js
- app/templates/builds.hbs
- app/templates/components/no-builds.hbs
- app/templates/components/repo-show-tabs.hbs
- tests/acceptance/builds/current-tab-test.js
- tests/acceptance/repo-build-list-routes-test.js
- tests/pages/build-list.js
- tests/pages/repo-tabs/current.js
Crons are still currently interspersed between API-triggered builds and
available in the `Build History` tab.
This addresses https://github.com/travis-pro/team-teal/issues/1036.
> Remove crons tab from builds page

- app/components/owner-repo-tile.js
- app/controllers/owner/repositories.js
- app/routes/owner/repositories.js
- app/templates/components/owner-repo-tile.hbs
When we were changing the app to use current_build, we also change
owner's page, but this was a mistake, the intended behaviour is to show
master's branch status.
> Use default_branch.last_build isntead of current_build on owner's page

- app/utils/log-folder.js
We were registering new click handlers every time a new log component was inserted into the DOM, but are not
removing them during teardown. Instead of trying to understand that logic now, I have simply removed the previous click
handlers with `$.off()`.
This fixes https://github.com/travis-pro/team-teal/issues/931.
> Users can once again expand hooks after restarting build

- app/components/hook-switch.js
- app/components/not-active.js
We already have [code](https://github.com/travis-ci/travis-web/blob/f500c1eb225f087b9eed992ed970facacc71d611/app/utils/pusher.js#L73-L81) that automatically adds `config.pusher.channelPrefix`
to all pusher channels if it's set
> Don't add `private-` suffix manually to pusher channels

- README.md
- app/adapters/application.js
- app/app.js
- app/components/log-content.js
- app/initializers/inject-feature-flags.js
- app/models/job.js
- app/models/log.js
- app/routes/first-sync.js
- app/services/ajax.js
- app/utils/pusher.js
- config/environment.js
- package.json
- vendor/log.js
Currently, any user in any environment (including when we run our tests) will see console output when using the application. In development and production environments, this is only noticeable when the developer tools are opened, but it can still be distracting.
To quiet the noise, I've moved all of our application logging -- from Ember's internal transition logging to our errors when requests fail -- behind a unified feature flag that can be independently set per environment. Because this can be helpful on occasion, I've kept the logging in place, which can be turned on again at any time. I'd like to also integrate this within our UI so users can toggle it themselves to help debug issues.
To enable this for more debugging output at any time, you can enable the `debug-logging` feature …
> Move debug logging behind feature flag

- app/models/build.js
- app/models/job.js
Currently, it says 'Invalid date'. In other parts of the website,
though, if a job is incomplete, hovering will say 'not finished yet'.
> Change hovertext if job incomplete

- package.json
As [discussed](https://travisci.slack.com/archives/web/p1469122883000009). Here’s an example of how it changes the output:
When I write `assert.ok` I tend to add an assertion description, like `assert.ok(false, 'should be true')`, because the test failure message is barely useful otherwise. So this doesn’t help much with that; in this screenshot, I deleted the assertion description to see what the output would look like. But there are some `assert.ok`s scattered around the codebase without a description, and I also think the message for `assert.equal` might be an improvement too.
> Add ember-qunit-nice-errors

- app/app.js
I think this can be removed. It doesn't appear to be used, and if it is, seems like it's actually invalid HTML?
> Remove unused/invalid alt attribute for {{link-to}} helpers

- package.json
Updated to the new version of the addon [ember-qunit-nice-errors](https://github.com/wyeworks/ember-qunit-nice-errors) the addon was originally included in #631
> Update ember-qunit-nice-errors to 1.1.1

- app/components/org-item.js
Prevent `return true;` which causes the action to be bubbled up to the routing sytem (and no other handlers exist to handle it).
> Prevent `tokenVisibility` from bubbling.

- waiter/lib/travis/web/app.rb
This backports #655.
cc @rkh @bnferguson
> Backport 655 for 2.0: always encrypt websocket connection to pusher/slanger

- app/components/log-content.js
There is code present to truncate logs at 10k lines, but a bug prevented it from functioning.
For now, this just fixes the bug, but I plan to add an acceptance test to ensure we don’t lose this feature again.
> Restore log truncation

- app/components/log-content.js
Restarted jobs that formerly had truncated logs were showing as truncated immediately, even when they only had a few log lines showing. Log truncation was probably added before the
job reset UI, so when truncation broke, no handling was added for resetting the limited flag when a job was restarted.
Adding automated testing for this might be difficult, but I’ll try it in my separate pull request for overall truncation tests.
> Reset log truncation flag after job restart

- package.json
This incorporates [a fix](https://github.com/brandonjmckay/ember-prism/pull/18) for `ember-prism` that was causing [this deprecation warning](https://travis-ci.org/travis-ci/travis-web/jobs/157967105#L392) when Ember processes start:
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
```
There’s no released version yet, hence the SHA, but the warning is annoying enough to me after a period of clean warninglessness, so I’m going to merge this 😆
> Update ember-prism for deprecation fix

- app/components/add-cron-job.js
- app/components/add-env-var.js
- app/components/add-ssh-key.js
- app/components/caches-item.js
- app/components/cron-job.js
- app/components/env-var.js
- app/components/limit-concurrent-builds.js
- app/components/no-builds.js
- app/components/not-active.js
- app/components/settings-switch.js
- app/components/ssh-key.js
- app/controllers/caches.js
This was an unfortunate mistake on my part when I [originally converted these to ember-concurrency tasks](https://github.com/travis-ci/travis-web/pull/598): I thought tasks were single-instance by default, but the `drop()` call is required for that.
> Convert tasks to single-instance

- app/routes/branches.js
The previous implementation was setting DOM classes from the route, which violated separation of concerns.
This now uses the repo controller to set that state, although that will likely be extracted into a service in the future.
This addresses https://github.com/travis-pro/team-teal/issues/1278.
> Fix multiple tabs being highlighted

- app/models/build.js
- app/models/job.js
- mirage/config.js
This reverts commit 42a6b3187179507ae0d5ca39a77d5123739d8a8d.
Someone wrote in that some people at their organisation can’t restart jobs. This is a possible temporary fix.
> Revert V3 API usage for debug builds due to possible regression

- app/mixins/repo-actions-item-component-mixin.js
- app/models/build.js
- app/models/job.js
- app/models/user.js
- app/services/ajax.js
- app/templates/components/job-repo-actions.hbs
- mirage/config.js
- tests/unit/components/build-repo-actions-test.js
- tests/unit/components/job-repo-actions-test.js
This adapts @clekstro’s 42a6b31, using the V3 header instead of URL path prefix. It also replicates the knowledge of the V3 API’s permissions structure:
* a user must have pull permissions to cancel or restart jobs and builds
* a user must have push permissions to trigger debug jobs
I’m unable to run this locally against the com-staging API for mysterious reasons, so I’ll be deploying manually to web com-staging to try it out.
> Use V3 for cancel/restart and hide buttons when lacking permissions

- config/deployment/deploy-pull-request.sh
- config/deployment/store-pull-request-data.sh
- config/deployment/update-github-status.sh
Thanks to @BanzaiMan’s travis-ci/travis-scheduler#38 and
travis-ci/travis-build#848, these are now present as
environment variables rather than needing to be fetched
via the GitHub API.
> Remove API-fetched deployment variables

- config/deploy.js
- config/deployment/deploy-pull-request.sh
- config/deployment/update-github-status.sh
This is an idea for optionally creating org- and com-staging PR deployments if the branch name contains `staging`. Staging deployments aren’t useful most of the time so the extra time for the PR build to pass isn’t worth it, but when testing in concert with API changes, it can be helpful.
I’ve pulled this from various branches. Last time I tried it, the com-staging deployment actually used com-production, strangely. Hopefully I can figure out why.
> Optional staging PR deployments

- app/index.html
- tests/acceptance/builds/branches-tab-test.js
- tests/acceptance/builds/current-tab-test.js
- tests/acceptance/job/basic-layout-test.js
- tests/acceptance/owner/repos-test.js
- tests/acceptance/profile/basic-layout-test.js
- tests/acceptance/repo/builds-test.js
This fixes the flash of `{{title}}` as the document title. Everything is already in place for dynamic titles otherwise.
> Improve static title

- waiter/lib/travis/web/app.rb
I misunderstood this code before, thinking it was replacing
the entire element. Without this change, the SITE_TITLE
environment variable will have no effect.
> Update title replacement to replace entire element

- vendor/log.js
This adds a visibleName to a Fold, which is used as the
rendered name in the logs. Under the surface, the name
of each fold now has a numeric suffix appended so
using the same name for a fold multiple times will not
collide and break the log rendering.
> Add index to stop splitting same-named folds

- app/adapters/ssh-key.js
- config/environment.js
- mirage/config.js
- tests/index.html
This was removed from the blueprint in Ember CLI 2.7:
https://github.com/ember-cli/ember-cli/blob/ad5af6877c44653eaf121e6820f06d280007c93c/blueprints/app/files/config/environment.js#L34-L36
See the blog post:
http://emberjs.com/blog/2016/04/28/baseURL.html
This will remove this bit of log noise:
https://travis-ci.org/travis-ci/travis-web/jobs/166748870#L613
> Remove deprecated baseURL setting

- app/controllers/settings.js
- app/styles/app/layouts/settings.sass
- app/templates/settings.hbs
- tests/acceptance/repo/settings-test.js
- tests/pages/settings.js
If the `/repo/:repo/settings` response includes `auto_cancel_pr_builds` or `auto_cancel_branch_builds`, this will show switches for them. Labels TBD.
> Add auto-cancellation switches when API response includes them

- tests/unit/components/jobs-item-test.js
Hi all,
`langauges` → `languages` in `jobs-item-test.js`.
Cheers!
> Fix typo in component test

- package.json
I had a CSS rendering crisis locally because of this; Ember CLI
version 2.9.1 matches this semantic versioning string. The
Ember CLI blueprints don’t use the fuzzy matching because of
how easily incompatibilities can creep in, as in this case.
We should be careful in future Ember CLI updates to follow
the blueprint update suggestion.
Thanks to @mixonic for the Yarn reference that helped me
track this down much faster than my painstaking `npm ls`
diff technique was allowing for.
> Fix Ember CLI version

- app/components/build-header.js
- app/templates/components/build-header.hbs
- tests/integration/components/build-header-test.js
There is no new commit API and Cron builds can be compared to and our GH-Url helper often generates falsy urls because of that
> Remove compare link in build header for api and cron eventTypes

- app/styles/app/base.sass
- app/styles/app/layouts/sidebar.sass
- app/styles/app/modules/status-icon.sass
When a job is in `created` it's not doing anything yet. The idea is to only start spinning the icon once it enters `received state`.
> Don't spin pending icon in created state

- config/deployment/deploy-test-master.sh
- config/environment.js
Sentry swallows all errors, which makes debugging more difficult.
> Disable Sentry for beta/canary deployments

- app/models/job.js
- app/utils/pusher.js
Typically, the pusher.js client authorizes requests by hitting a user-defined endpoint,
which tells pusher whether to allow a user to connect. In our case, we've exposed an auth endpoint
at `/auth/push`. When the app boots, we make a single request with all the channels we receive from our `/auth` endpoint, authenticating them so that the client can connect to Pusher successfully.
Unfortunately, when we attempted to subscribe a to a private job channel, we would often (but not always) receive an auth error. 
This change hits our /auth/pusher endpoint with a single job channel to
authorize it before making the subscription call to Pusher.  Now that the subscribe call is
guaranteed to happen after the auth call has succeeded, we shouldn't see this error anymore.
I'm not super pleased about …
> Fix Pusher errors by pre-authorizing private job channels

- .travis.yml
I was debugging the sudden disappearance of these PR-deployment
environment variables and mistakenly merged these lines in ca5ef00.
> Remove forgotten logging statements

- .travis.yml
- config/deployment/deploy-pull-request.sh
- config/deployment/deploy-test-master.sh
- config/deployment/store-redis-urls.sh
- package.json
The Heroku Redis URLs for the PR/beta/canary deployments change
periodically, which breaks things until I manually update the Redis URL
environment variables for the Travis environment. This obtains them
at build time from Heroku instead.
> Add step to save Redis URLs from Heroku

- ember-cli-build.js
This was probably necessary in the past but the current Ember-CLI docs discourage its use:
https://ember-cli.com/user-guide/#customizing-a-built-in-asset
> Remove custom handlebars vendorFiles config

- tests/unit/components/job-repo-actions-test.js
In line with recent updates to other tests, I took the liberty of declaring consts in `job-repo-actions-test.js`.
Thanks!
> Declare consts in test

- tests/unit/components/job-repo-actions-test.js
Hi all,
I think one test had a `link` left over, so I updated that to `button`.
Thanks!
> Rename link to button in test

- tests/unit/components/jobs-item-test.js
Hi all, 
came across a little typo:
`langauges` → `languages`
Thanks!
> Fix typo in unit test

- app/models/job.js
- app/templates/components/log-content.hbs
We want to display a banner for the following `osx_image` images:
- `beta-xcode6.1`
- `beta-xcode6.2`
- `beta-xcode6.3`
**Banner text:** This job is using an OS X image that <a href="https://blog.travis-ci.com/2016-11-17-retiring-some-osx-images/">will be retired on Monday, Nov 28th at Noon PST</a>. After that this build will be routed to our <strong><a href="https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-6.4">Xcode 6.4 image</a></strong>.
- `xcode7`
- `xcode7.1`
- `xcode7.2`
**Banner text:** This job is using an OS X image that <a href="https://blog.travis-ci.com/2016-11-17-retiring-some-osx-images/">will be retired on Monday, Nov 28th at Noon PST</a>. After that this build will be routed to our <strong><a href="https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-7.3.1">X …
> Adding some osx image retirement banners

- bower.json
We were previously on the 2.x series. I tested this locally by triggering an error locally in production mode.
The error was successfully logged.
> Upgrade raven.js (Sentry client) to 3.8.1

- app/utils/log.js
This is the most common error we get in Sentry. Based on the stack
traces and source mapping, this is apparently where the issue originates.
> Fix log error as reported by Sentry

- app/components/job-infrastructure-notification.js
- app/models/job.js
- app/templates/build.hbs
- app/templates/components/job-infrastructure-notification.hbs
- app/templates/components/job-tabs.hbs
- app/templates/components/log-content.hbs
- app/templates/components/notice-banner.hbs
- app/templates/job.hbs
This also extracts some components to contain the job infrastructure
notifications. The `job-infrastructure-notification` component now
contains the computed properties that were formerly on the `job`
model, because this is the only place they’re used.
> Move infrastructure notice above log/config tabs

- app/utils/urls.js
Hi all,
just a little typo `deirectly` → `directly`.
Cheers!
Gus
> Fix typo in urls.js

- app/adapters/cron.js
- app/components/add-cron-job.js
- app/components/cron-job.js
- app/models/cron.js
- app/styles/app/layouts/settings.sass
- app/templates/components/cron-job.hbs
- app/utils/helpers.js
- tests/acceptance/repo/settings-test.js
- tests/pages/settings.js
This PR is a part of the a big [re-factoring of cron jobs](https://github.com/travis-ci/travis-api/pull/319) and it does the following:
- Show next and last run times for cron jobs
- Add tests for last and next runs
- Change text for cron job running condition
- Fix option string: `dont_run_if_recent_build_exists`
> Show next and last run times for crons

- config/deployment/deploy-pull-request.sh
My logic here is that if staging deployments are requested,
they’re probably higher priority than production deployments.
> Move staging deployments before production

- app/components/user-avatar.js
- app/templates/components/org-item.hbs
- app/templates/components/user-avatar.hbs
The current requests we make for the avatar make no specification as to the image size, meaning we by default receive a 460x460 image. However, we're restricting the size of that image to 32x32 in CSS, meaning we're downloading a lot of unnecessary bits. 
This will, of course, hit users worse that have more organizations.
Here's current production (but with the images cached so network captured here):
And with these changes:
This change is Github-specific, but I haven't added any additional logic to check whether we're fetching from gravatar vs. github, simply because the only components currently passing in the `size` parameter are known to just use Github.
@lislis It would be good to get your feedback on this, especially given your upcoming work in …
> Optimize Github avatar image sizes requested on profile page for user/organizations

- app/controllers/top.js
- app/services/external-links.js
- app/styles/app/modules/navigation.sass
- app/templates/top.hbs
- tests/unit/services/external-links-test.js
This is an experiment to clearly label if you’re on a non-production version, like one of the Ember beta/canary deployments, or a PR deployment.
The alignment is off, it can be tweaked.
If it’s a PR deployment, I’d like to link to the branch on GitHub. (Ideally the PR, but that’s probably too much work.)
> Add deployment badge to top bar

- app/utils/lines-selector.js
In the original code for the LineSelector we needed to change the URL in
order to remove the selected lines hash from the URL. So for example
when you visitted a job page with a log and you selected the 111th line,
you would be on the URL like /travis-ci/travis-web/jobs/456#L111. When
you navigate away from the page you don't want to still see the selected
line, so we were removing that portion from the URL.
With the current way the location code in Ember.js works, we don't have
to do it, so it's safe to remove the line.
> Remove `setHash` call from LineSelector

- app/components/hook-switch.js
We are seeing errors in production where `then` is undefined on `hook.toggle()`, which
is a product of the component having been destroyed before our promise can execute.
Wrapping this in a task should fix the error and make this behavior more robust.
> Wrap hook switch async behavior in task

- app/styles/app/modules/build-header.sass
- app/templates/components/build-header.hbs
- tests/integration/components/build-header-test.js
The underline was extending to the whitespace between the
text and the icon, which I found quite irksome 😬
What do you think of this technique, @lislis? I am somewhat displeased by the `inner-underline` class, I originally had it as `label-align`, but it seemed weird to me to need to use that for the text elements within `build-status`, which don’t currently have any kind of wrapper.
uhhhh apart from the test failure, which I will address haha
> Move link underline beneath text only

- app/components/job-infrastructure-notification.js
- app/templates/components/job-infrastructure-notification.hbs
Update OS X banners to include:
- beta-xcode6.1 needs to show that it will be retired on Fri, Jan 20, 2017 at Noon PST
- The other Xcode 6.x images warn they are now routed to xcode6.4
- The Xcode 7.x images warn they are now routed to xcode7.3
> Update OS X banners

- app/styles/app/layout.sass
- tests/index.html
This is Firefox-only, it appears, but Percy uses Firefox
for diffs, so that seems fine.
> Add crisp edges for SVG in testing

- .travis.yml
This is a follow-up to #846, enabling Percy on `master`
with `EMBER_VERSION` of `default`.
> Add step to enable Percy on master/default Ember

- app/router.js
- app/routes/page-not-found.js
- tests/acceptance/non-existent-routes-test.js
- tests/pages/404.js
I initially assumed that ember-cli-sentry would be able to capture any
error we threw at it. Unfortunately, that isn't true in this case (sentry handles the error before the wrapper service can), so the filtering behavior we built into the service to lighten the error logging load hasn't yet been being triggered.
This change means that users visiting *any* unknown URL within our app
(except `/unknown-org`, which currently redirects to `/404`) will stay at the URL
they entered, but be shown our standard 404 template. I think this
improves UX and should quiet down the error logging significantly.
I also believe that we should revisit the current `/404` redirect
behavior, but will address that in a separate PR.
> Add wildcard error route to avoid raising `UnrecognizedURLError`

- app/routes/simple-layout.js
Given that the hook was only calling super, the route should continue working properly if removed.
> Removes `renderTemplate` that only calls super

- app/routes/application.js
GitHub's code search isn't all that, but this method doesn't seem to be called from anywhere, and it's checking if itself exists before calling itself?
> Remove unused `renderDefaultTemplate` method

- app/templates/components/subscription-status-banner.hbs
Hi all, noticed a tiny thing:
`<a__href=...>` → `<a href=...`>
Hope it helps.
Cheers!
> Remove double space from anchor attributes

- app/templates/insufficient-oauth-permissions.hbs
Hi all,
another tiny thing: `<p>_For more information…` → `<p>For more information…`
Happy new year!
> Remove extraneous space from insufficient-oauth-perm

- app/routes/first-sync.js
We now use `self` (bound previously to the outer scope `this`) instead of referencing
`this` directly.  I'm not sure why we pass the null context in, but the
code will likely be changed when converted to ES2015, so not concerned
with it atm.
> Fix sentry error about undefined `this`

- app/styles/app/pages/plans.sass
> Remove right border on third plan on big displays

- package.json
- server/index.js
Recently GitHub introduced Content Security Policy header that disallows
putting GitHub in an iframe. That's why our iframe sign in flow fails on
browsers that support CSP headers. On top of that the redirect flow that
we used as a fallback didn't work properly when using ember-cli's built
in server, because it didn't know how to handle a POST request that we
get from GitHub.
This commit introduces an Express.js middleware that mimics the logic
we use in a Ruby server.
> Fix sign in with ember server and redirect flow

- app/models/job.js
The implementation was causing false positives when state
was not yet loaded.
See this screen capture for an example:
> Fix definition of job.canCancel

- app/styles/app/layouts/jobs.sass
- app/templates/components/jobs-item.hbs
Embarrassingly, clicking the actions on the matrix was
causing the route to change.
> Move matrix repo actions outside link

- app/utils/init-hs-beacon.js
The HS beacon documentation only offers the 'instruction' property to be set. This is would be the easiest way to inform users to include a link in their message.
> add beacon instruction

- app/components/repo-show-tools.js
- app/styles/app/modules/buttons.sass
- app/styles/app/modules/dropdown.sass
- app/styles/app/modules/navigation.sass
- app/templates/components/repo-show-tools.hbs
- app/templates/top.hbs
based on the feedback we got https://github.com/travis-pro/team-teal/issues/1402
I made two changes:
- The 'More options' button will only open the dropdown on click. This should prevent clicking on an item in this menu when actually aiming for the restart/ cancel button. This is a big-ish change to what people are used to, but I think it makes sense.
- I increased the 'clickable' or 'hoverable' space in the top navigation. This should prevent the dropdown closing too early (eg for the Help section). I think we can just roll with it as there are no downsides to this change
Feedback welcome!
> Navigation and button ux

- app/templates/components/ssh-key.hbs
- tests/acceptance/repo/settings-test.js
- tests/integration/components/ssh-key-test.js
Currently, when displaying a private repo's SSH keys, we tell the user that there isn't any custom key set. To me, that makes it feel as if there's something outstanding that they need to do, when in fact no action is necessary on their part. Instead, I've changed the text to simply give it a default label of `Default`. I also made a small modification to the tooltip.
Here's the before:
And what this change would do:
> Modify language around SSH keys in repo settings

- config/environment.js
This host is used only on travis pro, but I think it's OK to add it
directly to the config.
> Add HS bacon host to CSP headers

- app/services/raven.js
This should fix a big chunk of errors that are raised but do not appear to have any user impact.
> Ignore failed/aborted adapter errors

- app/components/repo-show-tabs.js
- app/templates/components/repo-show-tabs.hbs
- tests/acceptance/repo/caches-test.js
- tests/pages/caches.js
This uses the same mechanism as repo-show-tools.hbs to
determine whether to present a maybe-visible tab for
caches. Perhaps this worked using an injected config
before…? Unclear.
Comparison of current appearance on settings route vs caches:
> Restore caches tab

- app/serializers/build.js
- tests/unit/serializers/build-test.js
At the moment we use API V3 to fetch repositories data and along with
repositories we also get data for current_build. Because the payloads
differ between V2 and V3 we need to normalise them in the build
serializer. One thing that was still missing from there was a
pull_request key. We include pull_request key in V2 payloads, but not in
V3 payloads and the build model uses this attribute.
> Fix current build view

- waiter/lib/travis/web/app.rb
from the commit message:
```
Historically ENV vars were not enabled when building an app on Heroku,
so we couldn't rely on any checks made in environment.js file (like for
example checking for process.env.TRAVIS_PRO). At some point it must have
changed, because on travis-pro the config is properly compiled with a
proper value for `pro-version` feature flag, but the Travis CI
Enterprise setup relies on the old method of updating the config on
runtime.
This commit makes the ruby server update the pro-version and
enterprise-version feature flags at the time of making request and thus
it remove reliance on availability of ENV vars during build time.
Additionally we don't know if accessing ENV vars when deploying to
heroku is something supported, so this way of doing things is more
future …
```
> Set pro/enterprise feature flags on runtime

- app/utils/log.js
- tests/acceptance/job/basic-layout-test.js
I plan to find a solution that will fix [this](https://github.com/travis-ci/travis-ci/issues/7106) without breaking [this](https://github.com/travis-ci/travis-ci/issues/7293), but for now, this restores things to how they were. No one really knew what the code in question was about, but it was obviously necessary!
> Remove log fix that broke other logs

- app/templates/components/beta-feature.hbs
This removes the whitespace after the bracket:
> Remove leading whitespace on feedback link

- app/components/not-active.js
The endpoint for activating a repository changed in API V3 from `enable` to `activate`.
https://github.com/travis-pro/team-teal/issues/1756
> Change the repo endpoint

- app/templates/components/repo-actions.hbs
Backporting #955 for `enterprise-2.1` as Debug builds aren't available yet.
> [Backport] Disable "Debug Build" button in Enterprise (#955)

- app/adapters/branch.js
- app/adapters/cron.js
- app/components/branch-row.js
- app/components/dashboard-row.js
- app/components/no-builds.js
- app/components/not-active.js
- app/components/status-images.js
- app/controllers/dashboard/repositories.js
- app/routes/branches.js
- app/routes/owner.js
- app/routes/owner/repositories.js
- app/routes/owner/running.js
- app/routes/settings.js
- app/services/broadcasts.js
- mirage/config.js
There's a mix of /v3 prefix and Travis-API-Version header usage in the
app, which makes it hard to maintain the mirage config. This commit
unifies usage of V3 calls to always use a header version.
> Remove usage of /v3 prefix

- app/serializers/application.js
- app/serializers/build.js
- app/serializers/cron.js
- app/serializers/job.js
- app/serializers/repo.js
- app/serializers/request.js
- app/serializers/v2_fallback.js
- app/serializers/v3.js
This flag is no longer used and new serializer's API is the default
> Remove isNewSerializerAPI flag from serializers

- mirage/config.js
This is superseded by the server.logging = true option:
http://www.ember-cli-mirage.com/docs/v0.2.x/configuration/#logging
> Remove optional Mirage logging

- app/models/job.js
- tests/unit/models/job-test.js
From commit message:
```
Not all of the endpoints return job's config. Because of that we try to
fetch job's config if it doesn't exist. The problem is that till now we
were trying to fetch it only once and we were giving up if the record
was loading. That means that if a config property is accessed while
loading, we will just return it as `undefined` and not attempt a second
try. I haven't noticed this problem in production, but it happened
during tests, so I guess it could happen on production as well.
This commit fixes the situation by retrying until we can do an actual
request.
```
I haven't added tests here, because I'm not sure what would be the best way to reliably test it. I'll think about it.
> Try fetching job's config multiple times if it doesn't succeed

- app/adapters/cron.js
- app/adapters/v3.js
- tests/unit/adapters/v3-test.js
We use API's returned @href in cron's adapter. As API returns the full
path, it will also return any prefix that server uses, for example if
the API is ran at https://example.com/api, the returned @href might look
like `/api/v3/repo/1`. That's why when we use hrefs from the API V3 we
need to attach them to a bare host, without a path prefix.
> Use host without path when dealing with hrefs from API V3

- app/adapters/cron.js
- app/adapters/v3.js
Backporting #1006 for `enterprise-2.1`
--------------------------
We use API's returned `@href` in cron's adapter. As API returns the full
path, it will also return any prefix that server uses, for example if
the API is ran at https://example.com/api, the returned `@href` might look
like `/api/v3/repo/1`. That's why when we use hrefs from the API V3 we
need to attach them to a bare host, without a path prefix.
/cc @drogus - just an FYI since it's your work being backported! <3
> [Enterprise Backport] Use host without path when dealing with hrefs from API V3 (#1006)

- app/adapters/repo.js
- app/adapters/v3.js
- app/components/builds-item.js
- app/controllers/settings.js
- app/models/branch.js
- app/routes/abstract-builds.js
- app/routes/build.js
- app/routes/job.js
- app/routes/settings.js
- app/serializers/branch.js
- app/serializers/cron.js
- app/serializers/v3.js
- app/templates/settings.hbs
- mirage/config.js
- mirage/models/branch.js
- mirage/models/build.js
- mirage/models/cron.js
- mirage/serializers/branch.js
- mirage/serializers/cron.js
- tests/acceptance/repo/settings-test.js
- tests/unit/adapters/v3-test.js
This backports #972 which backports parts of #970. 
This fixes the bug where cron entries wouldn't show up in the UI after they'd been added (and the data was there) in `enterprise-2.1`
> [Enterprise Backport] Backport Curtis' changes from v3 work #972

- app/serializers/v2_fallback.js
- app/serializers/v3.js
- tests/unit/serializers/build-test.js
- tests/unit/serializers/env-var-test.js
While working on test's serializers I noticed that when a response
contains nested repository objects (for example when build embeds jobs
with a repository object), the serializer will fail, because it will
mismatch `repository` type that API sends with our model type in
travis-web - `repo`. This is not a problem on production at the moment,
because we don't query any endpoints that return such a result, but it's
still good to handle this situation for future proofing serializers.
> Fix repo relationship serialization

- mirage/serializers/repository.js
In most tests we only set a slug for a repository. This works fine in
most cases, but has a drawback of not displaying a proper owner name and
name in the UI. This commit fixes the situation by setting owner name and
name based on slug if needed.
> Make sure that repo has owner name and name in tests

- app/serializers/build.js
- app/serializers/build_v2_fallback.js
- app/serializers/commit.js
- app/serializers/job.js
- app/serializers/job_v2_fallback.js
- app/serializers/v2_fallback.js
- app/serializers/v3.js
- app/utils/traverse-payload.js
- app/utils/wrap-with-array.js
- mirage/config.js
- tests/acceptance/builds/cancel-test.js
- tests/acceptance/repo/build-list-routes-test.js
- tests/unit/serializers/build-test.js
- tests/unit/serializers/repo-test.js
This is yet another problem with serializers that I ran into when working on #970. When API returns nested relationships, we should put all of the records with representation set to `standard` into the `included` array. The problem is that with code currently in production it will only do that for relationships in the first level. As with other issues that I found, it doesn't affect us on production, because in all cases that we use V3 API, we don't actually deep nested records to be pushed in the store, but it would be nice to get it working consistently. And I want to fix it before merging #970 to isolate any problems that it might cause.
> Fix serializers for nested relationships

- config/environment.js
GitHub uses several servers (such as `avatars3.githubusercontent.com`), so specifying a single server wasn't working as expected.
I simply replaced this with a glob, though it's a little more permissive than I would have liked. Unfortunately, something like `https://avatars*.githubusercontent.com` is invalid:
> The source list for Content Security Policy directive 'img-src' contains an invalid source: 'https://avatars*.githubusercontent.com'. It will be ignored.`
> Fix CSP warning for GitHub avatars

- package.json
pretender is already packaged as part of ember-cli-mirage.
> Remove ember-cli-pretender

- tests/acceptance/builds/cancel-test.js
- tests/acceptance/home/with-repositories-test.js
- tests/acceptance/repo/build-list-routes-test.js
This quiets down the test suite (at least when running locally).
> Remove server logging from acceptance tests

- app/components/add-ssh-key.js
- config/environment.js
- mirage/config.js
- tests/integration/components/add-env-var-test.js
- tests/integration/components/add-ssh-key-test.js
- tests/integration/components/ssh-key-test.js
- tests/unit/services/external-links-test.js
- tests/unit/services/status-images-test.js
The test suite currently hits our production API in a few instances. This addresses most of them, though there's still an outstanding issue with a `DELETE` of an SSH key that I haven't solved yet.
> Remove live network requests from test suite

- app/helpers/format-message.js
The GitHub issue link (see https://travis-ci.org/travis-ci/travis-web/builds/221251257)
was being incorrectly generated because the `owner` attribute
we were using was assumed to be a string, but was actually an object.
This meant we were generating
`https://github.com/[object%20Object]/travis-web/issues/1047` in
production.
I'm not sure what caused this, but applying this fix corrects the links
without breaking other tests.
> Fix broken GitHub issue link in build title

- package.json
- tests/acceptance/job/build-matrix-test.js
- tests/acceptance/owner/repos-test.js
- tests/acceptance/repo/build-list-routes-test.js
- tests/acceptance/repo/caches-test.js
- tests/acceptance/repo/settings-test.js
My general approach here was to add this wherever there was
a series of assertions against the same member of a collection,
especially when the member was already stored for that use.
> Update tests with page object’s new as property

- tests/acceptance/auth/automatic-sign-out-test.js
- tests/acceptance/dashboard/repositories-test.js
This is a bit easier in that it tends to involve less commenting
out of imports etc, and it also reminds everyone that skipped
tests exist.
> Convert comment-out tests to use skip

- .eslintrc.js
- app/adapters/.eslintrc.js
I think that not allowing unused vars is not giving us any value and it
usually makes life harder. Despite the fact Javascript has dynamic
signatures, I usually like to still define them even if I don't use all
the args, because the signature hints on how to call the function. This
is especially important when you intend to override a function in
subclasses - you may want to define an empty (or almost empty) default
and start using it by passing all of the arguments and only use some of
the arguments in different subclasses.
The only advantage of not allowing unused arguments is that we will know
when an argument is misspelled, but that should be also caught by other
rules (like: don't allow using undefined variables).
> Allow unused args

- app/serializers/repo.js
- app/serializers/repo_v2_fallback.js
- tests/unit/serializers/pusher-repo-test.js
We get only slug from pusher, so if pusher payload is received for a
repo that's not already in the store, we will miss `name` and
`owner.login` properties.
This commit fixes the problem by adding the `name` and the `owner`
attributes during normalisation. I also created `RepoV2Serializer` to
not clutter regular V3 serializer with pusher stuff.
> Fix normalizing pusher payload for repo

- .travis.yml
- testem.js
Given that phantom.js' maintainer is stepping down and this would enable us to test directly on our most popular browser, this seems like the most sensible path going forward.
I'm able to run tests like this both on macOS and Linux, but not sure of Windows support.
> Use Chrome --headless for testing

- testem.js
The use of Chrome --headless breaks on Chrome versions under 59 on macOS/Windows. This detects the OS version and ensures we only run headless on Linux for the time being.
> Detect OS and set testem browser args accordingly

- app/controllers/branches.js
- app/templates/branches.hbs
- tests/acceptance/builds/pull-requests-test.js
- tests/acceptance/repo/branches-test.js
- tests/acceptance/repo/build-list-routes-test.js
- tests/pages/branches.js
- tests/pages/build-list.js
When visiting a build tab, we're currently missing some assertions based on the tab we're currently on having no data.  This effort also resulted in surfacing a bug, as we currently show `No builds for this repository` messages on the `Branches` tab, which based on the expected template logic is incorrect.
> Add missing tests concerning missing data/fix small bug

- config/targets.js
I’ve #1093 to fix this differently, but in the absence of
data about which browsers we should support, I’m going to
merge this one so recent updates can be deployed. This one
is less destructive; we can come back to it. I found out
about the problem via this thread:
https://github.com/ember-cli/ember-cli/issues/7006
> Add IE 9 to supported browsers list

- .travis.yml
I had a spurious test failure, but no seed to go off of.
Changing to ember exam and passing the `random` option will ensure a seed is logged,
meaning we should be able to reproduce locally and fix once and for all.
> Use Ember Exam even without concurrency

- tests/acceptance/layouts/default-test.js
- tests/acceptance/layouts/pro-test.js
- tests/pages/header/default.js
- tests/pages/header/pro.js
- tests/pages/layouts/default.js
- tests/pages/layouts/pro.js
This ensures we assert that the DOM wrappers that differ slightly between the two will stay intact. Also, adds assertions for the signed in state of the header. This gives me enough confidence to refactor 😸 .
> Improve header/layout assertions for both default/pro

- app/templates/layouts/landing-page.hbs
- config/environment.js
- mirage/config.js
- tests/acceptance/layouts/about-test.js
- tests/acceptance/layouts/logo-test.js
- tests/acceptance/layouts/plans-test.js
- tests/pages/footer.js
This was inadvertently removed as part of the Ember 2.13 release.
> Restore header/footer on landing pages

- app/routes/application.js
- app/services/auth.js
Based on our previous spelunking (as well as reported errors in Sentry), we currently appear to have a race condition where the first route
transition has not always completed when we attempt to call an action on the `ApplicationRoute`.
Given the `renderFirstSync` action simply redirects, we should be able to use the (currently private) `routing` service as an interim replacement.
If the exception is what is keeping users from proceeding through the typical auth flow, this should hopefully address it.
> Directly transition to first_sync instead of invoking action

- app/routes/search.js
- tests/acceptance/search/flow-test.js
If an unauthenticated user attempts to perform a search, they're greeted with a broken page, as the API returns a 403. Given the API doesn't consider this a valid request, it makes sense to redirect users away from this screen.
> Redirect unauthenticated users performing search to index page

- package.json
This should remove some of the `nested transaction` errors we're seeing in production. For more details, see https://github.com/emberjs/ember.js/pull/15284.
> Bump Ember to 2.13.3

- app/services/raven.js
The error messages we are seeing appears to be just expected behavior. We would expect a task to be dropped if a second task is created when one is already running
> Mark ember-concurrency `TaskInstance` errors as benign

- app/services/raven.js
This is not an exceptional case.
> Ignore `needs-auth` error

- app/components/build-header.js
- app/templates/components/build-header.hbs
- tests/acceptance/builds/current-tab-test.js
- tests/pages/repo-tabs/current.js
This is unsightly and perhaps can be improved but even now I’m a bit confused about how to handle asynchronous relationships in computed properties.
> Update build header to use lone job status

- app/services/external-links.js
- bower.json
- ember-cli-build.js
- tests/unit/services/external-links-test.js
My original plan was to move this from a Bower to an npm
dependency, but it appears to be unused apart from the test.
> Remove unused Gravatar image link generator

- bower.json
This is now unnecessary thanks to this PR:
https://github.com/brandonjmckay/ember-prism/pull/20
> Remove unused dependency

- app/routes/dashboard/repositories.js
Apparently leftover params that were once planned in api but never made it in?
In any case, this will hopefully help clear up API logs
> remove query params that throw api errors

- app/styles/app/layout.sass
- tests/index.html
@backspace — a followup to this PR from long ago: https://github.com/travis-ci/travis-web/pull/848
SVGs have been seemingly flaky in Percy for a while, causing annoying false positive visual diffs.
After digging into this a bit, the root cause is actually a bug introduced by https://github.com/travis-ci/travis-web/commit/d82b9cfffd9781cc8ea678262ab5ed0c1ddb7167#diff-7c16ab3f88a04758b1b87951c3d1385eR12
This line was added to the features route:
```javascript
Ember.$('body').attr('class', 'features');
```
That line will override _all_ classes on the `<body>` tag, causing the tag that originally looks like this:
```
<body id="home" class="testing">
```
To become:
```
<body id="home" class="features">
```
Because the `body` tag is _shared across test runs_ and only the `ember-test-container` …
> Fix SVG false positive visual diffs.

- app/components/repository-layout.js
- app/controllers/index.js
- app/templates/components/repository-layout.hbs
- app/templates/index.hbs
- app/templates/repo.hbs
Part of moving the `index` page to rendering components forced me to duplicate the logic between the `repo` template and `index`. That was meant to be temporary, and this should fix it.
@drogus @lislis @backspace One thing I'm not really sure of here is naming. I'd like for to start having stronger naming conventions/better organization between components (given we have a number of them all under `app/components/`, but I'm not sure that `repository-layout` is in line with that or if that even conveys what I intended.
I was trying to capture the non-sidebar/main section of the page, and given this component wraps all build/job information at the repository level, I think this makes sense. But I'd be happy to hear other ideas if you have them 😄
> Deduplicate repository layout

- app/components/branch-row.js
- app/components/repos-list-item.js
- app/services/auth.js
- package.json
This polyfill can likely be removed as of Ember 2.15. Adding this now as it moves us away from using private API sooner rather than later.
> Use `router` service polyfill instead of private `-routing` service

- package.json
We are having failed Heroku deployments on Node 8, might as well stick
with a known working version for now.
> Fix Node version at 6.9.5

- app/components/build-header.js
The referenced property in the `buildState` computed property was incorrect.
This should fix https://github.com/travis-pro/team-teal/issues/2043.
> Fix build state display

- app/components/loading-screen.js
- app/services/random-logo.js
- app/templates/application-loading.hbs
- app/templates/components/loading-screen.hbs
- app/templates/dashboard/loading.hbs
- app/templates/loading.hbs
- ember-cli-build.js
This shows a random logo (from all the SVG variants I noticed)
when the user first boots up the app.
Implementation-wise, it might be confusing at first as to why the
`random-logo` service was added instead of making this a part of the
`loading-screen` component. The reason is that we utilize several layers of loading
templates which -- were the randomization done at the component level --
would mean that the logo might jump between available options as we transition between loading screens. This would be jarring, so I opted for making the selection when the service
is first initialized and then referencing that state whenever the
component is used.
This should likely be behind some sort of feature flag before it goes
public.
See https://github.com/travis-pro/team-teal/issues/1729 for …
> Randomize loading logo

- app/utils/pusher.js
My unfamilarity with this code caused problems in the pro environment,
where subsequent chunk subscriptions failed because of incorrect
authorisation information. I’m going to fully revert for now.
The general idea of the problem is that the `bulk_ajax` method fetches
authorisation information for each channel in bulk, but since it happens
synchronously, it was only fetching it for the first chunk of channels.
I’d like to change it to fetch for each chunk.
> Revert chunked subscription to Pusher channels

- app/components/job-infrastructure-notification.js
- app/templates/components/job-infrastructure-notification.hbs
For the incremental update of our default Linux environment from Precise to Trusty
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
> Update Trusty banner

- app/adapters/build.js
- app/adapters/repo.js
- app/adapters/stage.js
- app/models/build.js
- mirage/api-spec.js
- mirage/config.js
We need stages info only on a build page and then we can fetch it
lazily, so we don't need to always include it.
> Don't always fetch stages info

- app/components/log-content.js
The computed property signature is very odd and could probably be
simplified, but this fixes the issue.
> Fix download link for raw logs (with token)

- app/services/store.js
- config/environment.js
- tests/integration/components/add-env-var-test.js
- tests/integration/components/add-ssh-key-test.js
- tests/integration/components/ssh-key-test.js
I've removed some of our timeouts completely and replaced another one that was causing an acceptance test to hang with a config value that we can set to `0` in tests.
Based on my local testing, this seems to speed things up by a little over 10%.
Before:
After:
> Speed up test suite

- app/services/flashes.js
- tests/acceptance/auth/automatic-sign-out-test.js
- tests/acceptance/builds/cancel-test.js
- tests/acceptance/builds/debug-test.js
- tests/acceptance/builds/pull-requests-test.js
- tests/acceptance/builds/restart-test.js
- tests/acceptance/home/flashes-test.js
- tests/acceptance/job/cancel-test.js
- tests/acceptance/job/debug-test.js
- tests/acceptance/job/restart-test.js
- tests/acceptance/repo/build-list-routes-test.js
- tests/acceptance/repo/settings-test.js
- tests/pages/top.js
This lets the default preamble be overwritten. It also adds acceptance tests around flash messages.
> Add customisable flash message preamble

- app/utils/log.js
As part of changes related to the linting rules, the logging behavior was somehow impacted. This resulted in logs being cut off prematurely, but no error was being thrown (consistently cut off after about 470 lines).
> Fix logging truncation

- .travis.yml
I did manage to fix a lot of the spurious visual diffs by [eliminating some test bleed-through](https://github.com/travis-ci/travis-web/pull/1140/files) (and we got some [welcome help for others](https://github.com/travis-ci/travis-web/pull/1147)), but we still have one or two on each build since then. I don’t have time at the moment to look deeply enough to remove the rest of the bleed-though, so instead I’m suggesting that we stop randomising tests when we’ll be producing diffs with Percy.
I don’t love it, but the noise from the false diffs is grating and I don’t know if/when I’ll be able to address the cause.
> Change test randomisation to not run with Percy

- app/components/build-layout.js
- app/controllers/build.js
- app/controllers/job.js
- tests/acceptance/builds/cancel-test.js
- tests/acceptance/job/basic-layout-test.js
This broke with some refactoring. As of this commit, the job state is indicated for a favicon and backed up with a test, but I haven’t gotten it working for builds yet.
> Restore live favicon-as-status

- app/controllers/dashboard/repositories.js
- app/models/repo.js
- app/routes/dashboard/repositories.js
- app/templates/dashboard/repositories.hbs
- app/utils/dashboard-repositories-sort.js
Before this PR starred repos were not explicitly sorted, which could
be confusing, because the list of all repositories is sorted by current
build - latest builds are shown first.
> Sort starred repos in the same order other repos are sorted

- app/utils/fetch-live-paginated-collection.js
- tests/unit/store-paginated-test.js
store.paginated tests didn't properly test a filter function and it was
improperly handled in fetchLivePaginatedCollection - the default (empty
filter function was always passed).
> Fix filter function on store.paginated

- .travis.yml
These have been moved to a nightly cron job (including the deploys).
It's also no longer necessary to use ember-try and set the $EMBER_VERSION, as we can simply use the Ember version from our package.json.
> Remove beta/canary jobs from job matrix and tidy things up

- app/components/trigger-custom-build.js
- app/templates/components/trigger-custom-build.hbs
This extracts out the ember-concurrency tasks into separate parent/child tasks and uses
`timeout` instead of Ember.run.later.
> Refactor trigger build logic to use derived states

- app/styles/app/layouts/jobs.sass
> fix job items overlaying job action

- Dockerfile
- docker-compose.yml
- scripts/docker-build-and-push
This isn't needed for master/production builds, but referencing a non-master file when on a different branch is tedious. As crons are currently limited to a single branch and we're wanting to avoid having a conditional-littered build configuration, committing them here seems like a good compromise. Also handy in case you'd like to just work with Docker right out of the gate.
> Add docker configurations for nightly quay releases

- scripts/docker-build-and-push
This allows us to call the script using `master` instead of worrying about what branch this is actually being executed on
> Prefer passed in branch over $TRAVIS_BRANCH

- app/app.js
- app/utils/pusher.js
We don't need to prefix pusher channels manually in travis-web, because
we either get pusher channels from the API (which are already prefixed
where needed) or we subscribe to public repositories (and then we don't
need to prefix). This commit removes prefixing logic and instead
subscribes to whatever we get from the API.
> Don't prefix pusher channels

- app/components/remove-log-popup.js
This was failing without an error in production, so pushing this out. Will add a test case afterwards to ensure we do not inadvertently break it again
> Rename event to ensure log removed

- app/services/auth.js
- tests/acceptance/auth/sign-out-test.js
- tests/pages/top.js
This clears all flash messages unless it is showing the user their token has expired. See https://github.com/travis-pro/team-teal/issues/2232 for more details.
> Ensure flash messages cleared when signing out

- app/models/job.js
Fixes occurrences of missing eventType icons in the job header like here https://travis-ci.org/ember-cli/ember-cli/jobs/269636611
> set evetType alias on job model

- app/models/repo.js
- app/routes/application.js
- app/services/store.js
- app/utils/filtered-array-manager.js
- app/utils/pusher.js
- mirage/factories/repository.js
- tests/acceptance/repo/show-public-repo-test.js
- tests/unit/store-filter-test.js
When a user opens a repo that they aren't a collaborator of, we will
subscribe them to a public repo channel, so they still get updates for
the repo. This was done only on .org, but now that we plan to merge the
platforms it should work on .com version too.
The code needed to be changed a little bit, because now we need to also
care about private repositories and also we don't want to subscribe to
repositories that are already covered on user channel (ie. if the
current user is a collaborator, they would get an update through a user
channel anyway).
> Subscribe to public repos on pro too

- app/styles/app/pages/landing.sass
- app/templates/components/landing-default-page.hbs
- public/images/landing-page/oss-num-0.svg
- public/images/landing-page/oss-num-1.svg
- public/images/landing-page/oss-num-2.svg
- public/images/landing-page/oss-num-3.svg
- public/images/landing-page/oss-num-4.svg
- public/images/landing-page/oss-num-5.svg
- public/images/landing-page/oss-num-6.svg
- public/images/landing-page/oss-num-7.svg
- public/images/landing-page/oss-num-8.svg
- public/images/landing-page/oss-num-9.svg
Addresses [design-tasks issue #68](https://github.com/travis-pro/design-tasks/issues/68)
To make our testing numbers more accurate, created new svgs and styles to make each number individual which will allow us to customize them when needed. Unfortunately this is static atm.
> customized and separate oss project numbers on landing page

- app/components/oss-usage-digit.js
- app/components/oss-usage-numbers.js
- app/styles/app/pages/landing.sass
- app/templates/components/landing-default-page.hbs
- app/templates/components/oss-usage-digit.hbs
- app/templates/components/oss-usage-numbers.hbs
- tests/integration/components/oss-usage-digit-test.js
- tests/integration/components/oss-usage-numbers-test.js
This was previously hard-coded, meaning any change was more laborious than it needs to be. Instead, we can now just pass a value to a component and it renders the images as expected.
> Componentize oss usage numbers

- app/components/job-infrastructure-notification.js
- app/models/job.js
- app/utils/pusher.js
- tests/acceptance/builds/current-tab-test.js
Subscription to private jobs was recently changed in a way that we allow
to subscribe to both private and public jobs, regardless of the
platform. This check requires access to a `repo.private` property and
unfortunately in certain cituations the `job.subscribe()` method may be
called when job is still not fully loaded (meaning that repository won't
be loaded either).
This commit fixes the situation by waiting to load the job before
subscribing. This is a bit hacky and we should probably fix the app to
not even reach this place when the job is not loaded, but this was the
best way to do it at the moment.
I also removed changed bulk_ajax authorizer to travis_ajax authorizer.
We don't need to authorize multiple channels anymore, so I could
simplify the authroizer and thanks to that also …
> Fix subscribing to private jobs

- app/components/trigger-custom-build.js
- tests/acceptance/repo/trigger-build-test.js
A `429` is a known error type for the requests API, might as well recognise it.
> Add 429-handling for build trigger failure

- app/controllers/account.js
`reloadHooks` no longer exists, so this was throwing an exception in production.
Also, given pagination, the previous logic of reloading the entire collection is no longer applicable
> Silence production error due to missing method

- app/adapters/stage.js
- tests/acceptance/builds/build-stages-test.js
At the moment API only implements /build/:id/stages endpoint for
fetching stages info. We implemented findMany method in stage adapter in
order where we use the endpoint, but it fails when there's only one
stage in build. Ember Data won't fire findMany then, but instead it will
use findRecord, which by default would go to /stages/:id; API doesn't
support it.
This commit implements findRecord method in the stage adapter to use
/build/:id/stages endpoint, but return only one stage.
> Fix fetching a single stage

- app/adapters/stage.js
- mirage/serializers/v3.js
Ids returned from the API are ints, so we need to convert the id to int
in order to properly fetch the stage by id. The tests didn't catch this,
because Mirage was returning ids as strings.
This commit fixes the bug by converting the id to int before filtering,
but also changes tests to also return id as int to prevent these kind of
problems in the future
> Convert id in stages adapter findRecord to int

- mirage/config.js
- package-lock.json
- package.json
I've tried moving directly to 0.3.4, but have encountered many issues along the way:
- missing explicit inverse statements, which throws errors such as `The repository model has multiple possible inverse associations for the repository association on the build model.` (That's fixable, but others e.g. branches/builds were harder and led to the next error)
- removing the models and letting Mirage infer them from our models currently leads to memory leaks and `Maximum stack size exceeded` errors.
For that reason, I figured I'd bring in the single fix for the hostname, as the logic for that apparently changed and it will apply to later versions as well.
> Bump mirage to 0.2.9

- app/controllers/account.js
- tests/acceptance/profile/redirect-test.js
This removes the unsightly `?offset=0` when you first view
the profile route.
> Add default for profile offset

- app/components/settings-switch.js
- app/templates/components/settings-switch.hbs
This should address https://github.com/travis-pro/team-teal/issues/2146 by preventing the switch from ever getting into a bad state in first place.
> Only apply settings switch state locally if successfully persisted

- app/styles/app/layouts/profile.sass
Restore 'full' width profile hooks on hover
> fix profile hook length

- .travis.yml
- app/utils/live-paginated-collection.js
- package-lock.json
- package.json
- testem.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/start-app.js
I removed ember-router-service-polyfill, as advised by a notification
while building.
This includes some simple line-switchings where the modules codemod
put things in a different order than the blueprints. I also replaced
testem.js with the blueprint version because our differences were
negligible, might as well reduce friction during updates.
> Update Ember projects to 2.16

- app/controllers/repo.js
This will be removed in Ember 2.17. I think it‘s the only one…
https://emberjs.com/deprecations/v2.x/#toc_controller-content-alias
> Remove deprecated alias

- app/styles/app/layouts/log.sass
> fix white-space in extra colored logs

- app/adapters/build.js
- app/adapters/v3.js
- app/instance-initializers/pusher.js
- app/services/live-updates-record-fetcher.js
- app/services/pusher.js
- app/services/store.js
- app/utils/pusher.js
- config/environment.js
- package.json
- tests/unit/services/live-updates-record-fetcher-test.js
travis-live doesn't always have the ability to send full payloads. This PR addresses situations where only ids are sent
> Load pusher data from api when needed

- app/templates/components/repo-actions.hbs
There were two tab stops before this, one that showed the
tooltip and one for the button itself. 😐
> Move action button tooltips inside button

- app/styles/app/layouts/footer.sass
That should fix this:
And make it look more like this:
> add yellow circle for maintenance status page status

- app/models/build.js
- app/models/job.js
- app/services/store.js
From the commit message:
```
Data updates doesn't arrive to the browser in any specific order.
Because of that it's possible that data in an update delivered by
Pusher is older than data that we have available locally.
This commit overrides `store._pushInternalModel` function in order to
guard against such situations by checking the `updatedAt` attribute. If
a record that is being pushed to the store is older than a record that
we already have, we will just return the existing record.
```
> Don't update records with stale data

- app/components/pagination-navigation.js
- tests/integration/components/pagination-navigation-test.js
When defining inner and outer bounds in a way that they overlap
a bug appeared duplicating page 3
> Fix pagination component bug

- app/controllers/account/repositories.js
This reverts 8d0cb92, which [causes problems](https://github.com/travis-ci/travis-web/pull/1322) when switching between accounts.
> Revert default for offset query parameter

- config/environment.js
These are the defaults and they should cover our major breakpoints.
I’m hoping this won’t be annoying because it’ll mean triple the
snapshot diffs to approve, but we can tweak as desired.
> Add more Percy breakpoints

- app/components/repository-status-toggle.js
- app/controllers/account/repositories.js
- app/services/store.js
- app/utils/filtered-array-manager.js
- app/utils/live-paginated-collection.js
- tests/acceptance/profile/redirect-test.js
- tests/unit/store-filter-test.js
- tests/unit/store-paginated-test.js
There was a bug in my custom filtering code that was improperly caching collections - we were caching by calculating id based on filter parameters, but not taking into account nested query params. This PR fixes it and then also adds `offset: 0` to `account/repositories` controller to avoid adding it to query params by default.
> Fix `offset=0` on the profile page

- app/routes/application.js
- app/services/auth.js
- tests/acceptance/auth/automatic-sign-out-test.js
from the commit message:
```
When a Travis token expires and a user tries to open the app, we will
sign them out. The problem is that due to changes in e71862c we're no
longer running some of the sign out steps when the sign out is initiated
from the `auth` service. This commit gets back to calling the
`afterSignOut` every time a `signOut` is initiated.
```
> Fix auto sign out

- app/templates/components/trigger-custom-build.hbs
- tests/acceptance/repo/trigger-build-test.js
- tests/pages/trigger-build.js
It doesn’t make sense to trigger a build on a branch that doesn’t exist on GitHub.
> Add filtering for triggerable branches

- app/models/repo.js
It’s hard to say what this will do, we’ll see!
> Remove included build.jobs from PR query

- bower.json
- package-lock.json
- package.json
This is possible thanks to the new version of ember-keyboard-shortcuts.
> Remove Mousetrap Bower dependency

- app/models/job.js
As written up here: https://github.com/travis-ci/travis-web/pull/1269#issuecomment-349621548 
> The issue being that we configure Travis.config.pusher.secure as true globally for Enterprise, so travis-logs tries to broadcast updates on the private-job-#{id} channel for everything (https://github.com/travis-ci/travis-logs/blob/master/lib/travis/logs/pusher.rb#L20-L22) while travis-web is listening either on job-#{id} for "public" repositories or private-job-#{id} for "private" ones (quotes added for GitHub Enterprise since everything is a bit private).
>
> Oddly, other pieces of pusher based interface (which also broadcast on private- in Enterprise) continue to work regardless, I'm guessing from this work: #601. So it seems the way we handle things is different for this end point than …
> Fix log streaming in Enterprise, always use private channels. 

- package-lock.json
- package.json
We haven’t restored Greenkeeper, so I’m manually updating some packages.
I realised after starting that I might as well update Ember and Ember CLI
to get those known updates out of the way, so I’ll come back to doing this
(in a new PR) after that.
> Update various dependencies

- package-lock.json
- package.json
I’m not sure about this being necessary BUT it follows the
existing pattern!
> Move fuzzysort into devDependencies

- app/index.html
- app/styles/app/base.sass
- app/styles/app/legacy/_global.scss
This was formerly different across platforms.
Thanks to @jarrodldavis for #1414, which prompted us to look
into normalising on different OSes, and to @hail2u for nicely
presenting all the monospaced Google Fonts.
> Change log font to Cousine

- tests/acceptance/job/basic-layout-test.js
This is meant to prevent a regression reported in #1426.
> Add long unbroken text for Percy

- app/components/dashboard-row.js
- app/components/repository-layout.js
- app/components/repository-sidebar.js
- app/components/trigger-custom-build.js
- app/controllers/dashboard/repositories.js
- app/models/build.js
- app/models/job.js
- app/models/repo.js
- app/routes/settings.js
- app/services/api.js
- app/services/repositories.js
- config/deprecation-workflow.js
- tests/acceptance/builds/pull-requests-test.js
- tests/integration/components/dashboard-row-test.js
- tests/unit/models/job-test.js
- tests/unit/services/store/record-version-test.js
- tests/unit/store-filter-test.js
- tests/unit/store-paginated-test.js
This commit introduces a new service named `api` that can be used to
request data from the V3 API. Before we were using the `ajax` service
for API operetions, but we want to remove it in the future (ie. as soon
as we drop V2).
> Introduce an api service for API V3

- app/components/log-content.js
- app/styles/app/layouts/log.sass
- app/utils/lines-selector.js
- app/utils/log.js
- tests/acceptance/builds/cancel-test.js
- tests/acceptance/job/basic-layout-test.js
- tests/pages/job.js
When using paragraphs Firefox inserts a new line after each line if you
copy the log output.
> Use divs instead of paragraphs for log lines

- app/components/log-content.js
- app/utils/lines-selector.js
When you select a line in the rendered log it doesn't really make sense
to do it with a repo url, because if you link to a repo URL the
displayed job will likely change in the future.
> Redirect to job page when selecting a line.

- .eslintrc.js
- app/.eslintrc.js
- app/routes/application.js
- app/routes/auth.js
- app/services/auth.js
- app/templates/components/repo-not-found.hbs
- tests/acceptance/feature-flags/user-sets-flags-test.js
When a user opens a URL that needs a redirect to the auth page, the
information about previous URL is lost. That's why whenever we
automatically redirect to the auth page we need to preserve the redirec
uri and pass it to the API.
> Redirect to a previous URL after signing in from auth page

- app/components/branch-row.js
- tests/acceptance/repo/branches-test.js
Screenshot confirms travis-ci/travis-ci#8986 completely. The URL is not formed completely post the "#" sign. The attempted fix simply encloses the branch name in encodeURIComponent. 
Further, tried to pursue the TODO mentioned just below.
> A fix to travis-ci/travis-ci#8986

- app/styles/app/layouts/profile.sass
- Places the settings icon in proper vertical alignment
`app/styles/app/layouts/profile.sass`
> Align gear icon

- app/styles/app/layouts/log.sass
- Places the fold badges in proper vertical alignment
[2470](https://github.com/travis-pro/team-teal/issues/2470)
`app/styles/app/layouts/log.sass`
> Change vertical alignment for fold badges

- app/components/job-infrastructure-notification.js
> Remove xcode8 image from the list of deprecated images

- app/styles/app/modules/dropdown.sass
- Removes extra white-space from the bottom of the trigger build button in Safari browser
[2484](https://github.com/travis-pro/team-teal/issues/2484)
`app/styles/app/modules/dropdown.sass`
> Remove extra white space on trigger build button

- app/styles/app/modules/buttons.sass
- Changes the outline border to `thin dotted` when the build button is active and/or focused
[2333](https://github.com/travis-pro/team-teal/issues/2333)
`app/styles/app/modules/buttons.sass`
> Change the active and focus state outline on build button

- .gitignore
Global .gitignore doesn't seem to take on Windows, so adding the JS Config file for VS Code to project gitignore to save time.
> Add VS Code JavaScript config file to gitignore

- app/templates/settings.hbs
- Add help links to the build branches and PR buttons
- Update text of the build branches and PR buttons
[2214](https://github.com/travis-pro/team-teal/issues/2214)
`app/templates/settings.hbs`
> Add help links and rename build branch and pr buttons

- tests/acceptance/auth/first-sync-test.js
- tests/acceptance/builds/build-stages-test.js
- tests/acceptance/builds/current-tab-test.js
- tests/acceptance/builds/pull-requests-test.js
- tests/acceptance/repo/show-test.js
I assume that this was used for debugging purposes at some point, but it currently just adds noise to the test suite.
> Remove server.logging statements from acceptance tests

- app/templates/components/repository-layout.hbs
This makes it more consistent with the other GitHub links within the app.
> Make GitHub icon open link in new tab

- app/templates/components/build-header.hbs
- app/templates/components/builds-item.hbs
- app/templates/components/repos-list-item.hbs
This PR aims to fix following errors,
- Title attribute shows "January 1, 1970" if user hovers over the job/build duration before it starts
- Title attribute shows "Invalid Date" if user hovers over the job/build completion date before it completes on Build History tab
> Fix Erroneous Title Values

- app/styles/app/modules/status-icon.sass
This fixes https://github.com/travis-pro/team-teal/issues/2524 by making the SVG overflow property visible to prevent rectangle shaped path clipping over the icons.
> Fix status icon clipping

- app/components/pagination-navigation.js
- app/controllers/account/repositories.js
- app/controllers/dashboard/repositories.js
- app/routes/account/repositories.js
- app/routes/dashboard/repositories.js
- app/templates/components/pagination-navigation.hbs
- config/environment.js
Users were able to manually specify the offset in the URL, which led to rounding errors in the rendered pagination links.
This makes it simpler to use from a user's perspective and also avoids exposing something the user should not be able to influence (yet). We can always re-evaluate this later if users would find it useful, as API still supports it.
> Fix broken pagination links containing decimals

- app/routes/builds.js
This should address https://github.com/travis-pro/team-teal/issues/2520, where builds for a public repo were not being loaded when clicking "Show more."
> [Bugfix]: Ensure tab is set as `builds` regardless of auth status

- app/helpers/fuzzy-highlight.js
- app/helpers/github-commit-link.js
There’s one more but maybe it’s from ember-svg-jar and
I can’t figure out how it could be addressed.
> Update some imports for deprecation warnings

- app/services/feature-flags.js
- tests/acceptance/feature-flags/app-boots-test.js
Currently in production, if a feature-flag call fails, ember-data throws an exception that halts loading on the page.
This change catches that exception to ensure the app still boots, just with the default flags.
Co-authored-by: Curtis Ekstrom <curtis@travis-ci.org>
Co-authored-by: Berrak Nil Boya <berraknil@gmail.com>
> [Reliability]: App boots without feature-flags

- app/services/feature-flags.js
- tests/acceptance/feature-flags/app-boots-test.js
The test is a bit noisier now, but it feels worth the tradeoff. Also, fix the test name as it was still the generated boilerplate.
> [Reliability]: Ensure feature flags exception logged to Sentry

- package-lock.json
- package.json
This changes the semver range for `ember-cli` to use the `^` operator instead of `~`. The only reason for this is that it [will allow minor/patch version updates](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) as opposed to [patch-only updates when the patch version is specified](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1).
Given we now have a `package-lock.json` file, I'm not sure an `npm install` will do anything weird in either case, but the version definition may affect how Greenkeeper works (meaning less PR's for versions we'd legitimately want automatically tested).
So, in our case, `~` would allow an update to 2.19.0, while `^` would only allow updates to higher 2.18.x versions.
> Bump Ember-CLI to 2.18.2

- app/styles/app/modules/build-tile.sass
- app/styles/app/modules/status-icon.sass
Build status icons are clipped on hover as documented [here](https://github.com/travis-pro/team-teal/issues/2539). This 1px padding forces them outside of their bounding box and makes them completely visible.
This commit also removes the previously applied global padding to all status icons as it is unnecessary and breaks the flow of the layout.
> [Reliability] Add padding to build status icons

- package-lock.json
- package.json
This should remove the last of the helper import deprecations.
> Upgrade ember-composable-helpers

- app/templates/components/jobs-list.hbs
I don’t love needing this wrapper element but I also wouldn’t
love needing an ID.
> Fix allowed failures tooltip alignment

- .eslintrc.js
- app/adapters/application.js
- app/adapters/v3.js
- app/components/branch-row.js
- app/components/not-active.js
- app/components/org-item.js
- app/helpers/obfuscated-chars.js
- app/models/log.js
- app/routes/branches.js
- app/routes/owner.js
- app/routes/owner/repositories.js
- app/services/ajax.js
- app/services/api.js
- app/services/auth.js
- app/services/broadcasts.js
- app/styles/app/layouts/profile.scss
- app/templates/components/org-item.hbs
- package-lock.json
- package.json
- public/images/stroke-icons/icon-copy.svg
- tests/acceptance/profile/view-token-test.js
- tests/helpers/start-app.js
- tests/integration/helpers/obfuscated-chars-test.js
- tests/pages/profile.js
This does a few things:
* Allows users to directly copy the token on the profile page (instead of merely hiding/showing), improving the flow.
* Switches the token that is shown/copied from the "Travis token" to the "API token"
* Removes the "eye" icon for a simpler button-based UI
See https://github.com/travis-pro/team-teal/issues/2559 for more details.
> Improve overall token UX on profile page

- config/environment.js
- mirage/config.js
- tests/acceptance/profile/view-token-test.js
- tests/helpers/sign-in-user.js
Currently, we manually check the auth token on a per-request basis. With this change, we automatically check the auth token if one is passed, returning a 403 if it doesn't match.
> Ensure test token validity

- tests/acceptance/job/delete-log-test.js
- tests/acceptance/repo/settings-test.js
- tests/acceptance/repo/trigger-build-test.js
- tests/integration/components/travis-status-test.js
I came across a few idiosyncrasies in terms of imports and server route definitions. This just changes them to be in line with how we do things in the rest of the test suite.
> Standardize mirage across test suite

- app/components/repository-sidebar.js
Currently in production, we incorrectly show inactive repositories in the sidebar if they are added to the repository service (which is the case when we fetch *all* repositories on the profile page).  This adds a filter to the `{{repository-sidebar}}` component to ensure only activate/activated repositories are shown.
> [Bugfix]: Only display active repositories in sidebar

- app/templates/components/top-bar.hbs
This was broken in #1564. I'm surprised this didn't break any tests/visual diffs. Will create an issue to beef up the coverage on Monday.
> Fix missing navigation on mobile

- app/components/show-more-button.js
- app/mixins/builds/load-more.js
- app/templates/builds.hbs
- app/templates/components/show-more-button.hbs
- app/templates/pull-requests.hbs
Currently in production, clicking on the "Show More" buttons when on the Build History/Pull Requests tab, nothing happens visually. The data loads, but the button doesn't do anything.
It appears this is a bug with the current implementation, as it expects us to change the button text to "Loading" and disable the button once it has been clicked.
Instead, this PR takes a different approach. Clicking the button will now replace the button with the loading indicator that is shown when the page loads, i.e. our normal `{{loading-indicator}}` component. This eliminates our need to disable the button. We also now use an ember-concurrency task to use derived state and the `perform` helper to radically reduce the complexity around this button.
Before:
After:
> Improve UX of Show More buttons

- .travis.yml
Some errors on heroku need a link to special error pages for error pages
that don't even load the app (500 from heroku, maintenance etc). We
decided to generate those pages from travis-web, but I think that it
doesn't really make sense anymore. For some reason generating those
pages broke and maintenance page was missing styles. Instead of
debugging it I think it would be better to just keep the error pages on
S3 and modify them there if needed. It would also add a benefit of not
making travis-web's builds longer.
> Don't upload error pages to S3

- app/templates/components/requests-item.hbs
- mirage/config.js
- mirage/models/commit.js
- mirage/models/repository.js
- mirage/models/request.js
- package-lock.json
- package.json
- tests/acceptance/repo/requests-test.js
- tests/pages/requests.js
I included `ember-test-selectors` here, which I remember you suggesting a while ago, @clekstro, but maybe that never happened? It just seemed weird to me to have to use `eq(3)` etc to get at the sections of a request. But I could remove it if it seems weird to have both page objects and test selectors.
> Add requests acceptance tests

- config/environment.js
this improves the initial page load speed dramatically.
refs https://github.com/travis-ci/reliability/issues/37
> reduce page size on dashboard from 100 repos per page to 25

- app/components/job-log.js
- app/components/log-content.js
- app/models/job.js
- app/models/log.js
- app/templates/components/job-log.hbs
As detailed in https://github.com/travis-pro/team-teal/issues/2607, there were circumstances under which we would render the incorrect log when clicking a sidebar link. 
This was due to the `didUpdateAttrs` hook not being fired when we expected it to be, as we were rendering a new component instance instead. I've now switched things over to use an ember-concurrency task (mainly to improve the UX around log loading which was pretty clumsy before), which just so happened to fix this issue 😎 .
I've tested this pretty thoroughly locally to make sure that log streaming is still working as expected, but will test it more extensively in our PR env to avoid a Friday surprise.
> Fix log rendering issue

- app/templates/plans.hbs
Saying that it is a plan can potentially be mistaken for it being a plan for travis-ci.com when really it's the on-premises version of Travis CI for users who want to use our product, but have it behind their firewall.
> enterprise plan to on-premises product

- app/instance-initializers/enterprise-environment.js
- tests/unit/instance-initializers/enterprise-environment-test.js
Closes https://github.com/travis-pro/travis-enterprise/issues/281 (apologies for private repo reference)
@danishkhan noticed during Enterprise 2.2 QA that jobs running in the sidebar was off and should have been on. I asked about it here https://github.com/travis-ci/travis-web/pull/1547#issuecomment-371213457 when it changed but I misunderstood the answer, thinking it was phasing out.
So this is fixing that by turning it back on!
> Turn on jobs running in the sidebar for Enterprise

- app/instance-initializers/enterprise-environment.js
- tests/unit/instance-initializers/enterprise-environment-test.js
Backport of #1609 for `enterprise-2.2`
> [Enterprise Backport] Turn on jobs running in the sidebar for Enterprise (#1609)

- app/services/raven.js
- tests/unit/services/raven-test.js
I have a case in billing where I want to be able to always
log an exception (apart from enterprise etc), so I’m
introducing this interface.
> Add option to skip Sentry sampling

- app/styles/app/layouts/profile.scss
- app/templates/components/org-item.hbs
It works for the view button but I don’t know how to address it for the copy button.
> Change token buttons to not switch routes

- config/environment.js
This is superfluous now that the team page has been extracted.
> Remove unused configuration

- app/templates/account/repositories.hbs
This links explains how to migrate an account with more that 50 repositories.
See action item #2 at https://travisci.slack.com/archives/C1MD4TBEV/p1525792124000033
> Add link to travis_migrate_to_apps gem

- app/templates/settings.hbs
- tests/acceptance/repo/settings-test.js
- tests/pages/settings.js
- Removes build only with `.travis.yml` option from build settings within `travis-web`
> Remove Build only with travis yml option

- app/components/enterprise-banner.js
Fixes https://github.com/travis-pro/travis-enterprise/issues/300 (Pardon the private issue)
Summarizing that issue, essentially the license banner comes back after a refresh even if you have dismissed it. Digging we found some bugs in one of the flows of logic where some properties got renamed: 
> Turns out it wasn't the logic that was off, but the get statements... `exceeding` and `almostExceeding` return as `undefinded`. It seems the proper properties are `exceedingSeats` and `almostExceedingSeats`? 
>
>As these are always false-y the localstorage got cleared everytime. Testing a fix to this right now. So hopefully that's the problem. 
This change has already been made in this PR. What makes this PR WIP and the feedback I need is it seems the enterprise banner component fires twice …
> Fix issue of localStorage getting cleared too often for the Enterprise License Banner

- app/templates/settings.hbs
- tests/acceptance/repo/settings-test.js
- tests/pages/settings.js
This reverts #1672, as the back-end changes haven’t happened yet.
> Restore build-only-with-yml switch

- app/services/status-images.js
- config/environment.js
- tests/unit/services/status-images-test.js
- waiter/config.ru
- waiter/lib/travis/web/app.rb
Backport of #1674 for `enterprise-2.2`
> [Enterprise Backport] When Enterprise has publicMode turned off, generate tokens for status images. (#1674)

- config/environment.js
- package-lock.json
- package.json
I’ve found that CSP warnings cause a lot of confusion and noise,
obscuring the true problems we’re trying to track down. The
“report only” nature of the log messages doesn’t stand out to
people, I think they see the red text and assume it’s a problem.
Until we get to a point where we’ve actually safelisted everything
and stop having false negatives, I’m removing this.
> Remove content security policy

- app/router.js
- Changes the route from `billing` to `subscription` when on the subscription tab in billing.
[Issue](https://github.com/travis-pro/billing-v2/issues/129)
`app/router.js`
> Change route to subscription for subscription tab

- app/templates/account/billing/index.hbs
- tests/acceptance/profile/billing-test.js
- Changes the copy from `builds` to `jobs` on the subscription tab in billing.
[Issue](https://github.com/travis-pro/billing-v2/issues/128)
`app/templates/account/billing/index.hbs`
> Change builds to jobs on subscription tab

- app/models/subscription.js
- app/styles/app/layouts/profile.scss
- app/templates/account/billing/index.hbs
- app/templates/components/payment-details.hbs
- tests/acceptance/profile/billing-test.js
- Add `Plan Overview` for manual subscriptions
- Make it visually clear that the subscription is a manual subscription
[Issue](https://github.com/travis-pro/billing-v2/issues/131)
`app/templates/account/billing/index.hbs`
> Add visual clarity for manual subscriptions

- app/components/enterprise-banner.js
This is port of the changes in https://github.com/travis-ci/travis-web/pull/1671 to `master`
A while back we needed to do a quick fix in `enterprise-2.2` where we made it so banners would be sticky when you closed them. We didn't do this in `master` because ideally we'd rework this to not have some of the timing issues (can see more of the details in the original ticket). 
Unfortunately we don't have the time or manpower to do that at the moment and want to make sure when the next version of Travis CI Enterprise comes out, we don't have a regression of this bug, therefore, I'm porting it to master. :D 
This should not affect hosted what so ever, and is already in production in Enterprise 2.2.1.
> [Port to master] Fix issue of localStorage getting cleared too often for the Enterprise License Banner" 

- app/services/status-images.js
- tests/unit/services/status-images-test.js
Backport of (#1724) for `enterprise-2.2`
> [Backport] Always generate status image tokens in Enterprise (#1724)

- package-lock.json
- package.json
There’s something wrong with adapter:request where it can no
longer determine the relevant repository id when fetching
the parsing messages.
> Revert to Ember Data 3.1.1

- app/utils/pusher.js
The absence of this causes spurious failures in tests.
> Add unsubscribe to mock Pusher

- app/models/log.js
- tests/acceptance/job/basic-layout-test.js
While it would be preferable to improve log-rendering speeds,
we probably won’t have time for that for a while.
> Add ability to turn off log-rendering

- app/styles/app/layouts/jobs.scss
Previously you could see this issue when viewing travis-ci/gimme.
Looks like it was due to a quirk of flexbox children with `white-space: nowrap;`. By default flex items won't become smaller than their contents. Setting `min-width: 0;` on the parent resolves the issue.
> Fix build job list alignment issue

- app/templates/components/requests-item.hbs
Looks like this is due to nested elements with middle vertical align. I think the label-align class on the strong elements is superfluous, so I removed them. But if that's not the case, we could instead add some css to override the vertical align.
> Fix alignment of branch name in requests

- app/components/job-infrastructure-notification.js
Adds a message at the top of jobs that use Xcode 6.4 to call out that we are planning to deprecate the image.
Some previous discussion on this:
- https://github.com/travis-ci/product/issues/26
- https://github.com/travis-ci/travis-build/pull/1454
> Add deprecation message for Xcode 6.4

- app/styles/app/layouts/footer.scss
- app/templates/components/page-footer.hbs
- config/environment.js
- Add `plans and pricing` link to footer for `.com`
- Reorganize footer links
[49](https://github.com/travis-ci/product/issues/49)
`app/templates/components/page-footer.hbs`
> Reorganize and add plans and pricing to footer

- app/controllers/account/repositories.js
- app/routes/accounts.js
User installations are somehow being deleted since the
merger of #1782. While my true desire is to figure out
why that’s the case, this is a workaround in the meantime,
as the serialiser code that’s likely responsible is often
still quite opaque to me.
> Add workaround to preserve user installation

- app/styles/app/modules/tracer.scss
- app/templates/components/x-tracer.hbs
A naming conflict with the global `.error` class was adding a lot of extra padding.
Before:
After:
> fix display of errors in web tracing panel (naming conflict with global .error)

- app/adapters/build.js
- app/models/repo.js
- app/routes/dashboard/builds.js
The inclusion of a build’s jobs is needed on “My Builds“ to
determine whether builds can be restarted, but it caused
other builds queries to slow down.
> Make build-jobs loading conditional

- app/controllers/account/billing/index.js
- app/templates/account/billing/index.hbs
- app/templates/components/billing-education.hbs
- app/templates/components/billing-subscription.hbs
- tests/acceptance/profile/billing-test.js
- tests/pages/profile.js
- Add logic to consider educational users
- Add new message for educational users
[2822](https://github.com/travis-pro/team-teal/issues/2822)
` app/controllers/account/billing/index.js`
> Add logic and messaging for educational users in billing

- config/deprecation-workflow.js
This is currently clogging the output in tests/development, turning down the noise for now.
> Silence additional deprecation warnings

- app/adapters/job.js
- app/services/job-config-fetcher.js
Context: https://travisci.slack.com/archives/CD38XGFGU/p1539344280000100
Example: https://travis-ci.org/junit-team/junit5/jobs/440495645/config - config does not load. 
As per investigation, `job-config-fetcher` service fetched builds by `job.build.id`, but `build` is an async relationship on `job`, which caused querying builds with `id: undefined` for unresolved builds.
> Fix config fetching logic

- app/components/job-infrastructure-notification.js
- app/styles/app/mixins.scss
- app/templates/components/job-infrastructure-notification.hbs
Suggestion: https://travisci.slack.com/archives/C1FAZPJNP/p1539297161000100
Here's how it looks like:
The link is only shown for `windows` jobs. Here's an example of one: https://as-windows-support-link-v2.test-deployments.travis-ci.org/yargs/yargs/jobs/440203815
> Add notice about support for windows builds

- .travis.yml
Issue: cron jobs for Ember beta releases fail the entire build on master branch. 
Example: https://travis-ci.org/travis-ci/travis-web/builds/444616978
> Allow failures for ember beta builds

- app/templates/components/owner-repo-tile.hbs
- tests/integration/components/owner-repo-tile-test.js
- tests/pages/owner.js
Addresses a repo title alignment issue found by @artursmirnov in https://github.com/travis-ci/travis-web/pull/1843
> Fix repo title alignment issue on owner page

- app/templates/components/account-repositories.hbs
- Organization repos pagination links will use organization route instead of account route
[2851](https://github.com/travis-pro/team-teal/issues/2851)
> Organization repos pagination links use organization route

- app/styles/app/modules/switch.scss
This is currently confusing as it's the opposite of what iOS or other similar implementations do.
Here's what this looks like after the change:
> Change switch so switch is to the left when disabled

- app/controllers/repo.js
- app/routes/repo/index.js
- app/templates/components/github-apps-repository.hbs
- tests/acceptance/profile/migration-test.js
We can't apply `active_on_org` prematurely, as it would remove the repository from the migration list before the user sees the migration result.
> Ensure correct status shown after repository migration

- app/utils/log.js
- tests/acceptance/job/basic-layout-test.js
Issues: 
- https://github.com/travis-pro/team-teal/issues/2782
- https://github.com/travis-ci/travis-ci/issues/10133
@backspace please take a look once you have a chance. This is basically the same fix as last time with a small difference to make sure, that it doesn't break formatting for other users. The difference is in this line: https://github.com/travis-ci/travis-web/pull/1783/files#diff-a9f1ee3a2839d79578ecf5adef53afe1R254 (I removed `\s` from regexp).
I tested it against both jobs and they both look good:
- https://as-fix-log.test-deployments.travis-ci.org/Ortus-Solutions/JSONPrettyPrint/jobs/417099159
- https://as-fix-log.test-deployments.travis-ci.org/mozilla/treeherder/jobs/430084979
> Fix blank lines in log

- app/controllers/github-apps-installation.js
This should address an issue where the Github Apps installation redirect page was not redirecting correctly.
> Fix apps redirect issue

- app/services/external-links.js
- app/templates/components/account-repositories.hbs
The URL I included here doesn't work yet, as it depends on https://github.com/travis-ci/docs-travis-ci-com/pull/2137 being merged which will happen shortly.
This way the documentation we're redirecting our customers to is the new one created specifically for migration beta testing.
> Add beta instructions docs to profile

- app/utils/keys-map.js
Currently, with `language: bash`, _no language set_ is displayed in the build matrix overview and job overview. This should be set to _Shell_.
> Display language as shell for shell

- .eslintignore
I don’t know why errors like these are suddenly showing up,
but it seems obv that we shouldn’t be linting dependencies:
https://travis-ci.org/travis-ci/travis-web/builds/458959836#L509-L540
> Add node_modules to .eslintignore

- config/deprecation-workflow.js
- package-lock.json
- package.json
The original has some deprecation fixes that have been long
awaiting a merge, see here for background:
https://github.com/kimroen/ember-cli-document-title/pull/75#issuecomment-441332495
> Change to fork of ember-cli-document-title

- app/controllers/settings.js
The service was not injected, which our tests unfortunately did not catch. It looks like when you enable a feature within the test suite, it actually injects the service, masking this type of error.
> Fix broken settings page after migration

- package-lock.json
- package.json
This reverts #1918, which is failing to deploy and I can’t look
more deeply at the moment.
> Revert ember-intercom-io update

- config/deprecation-workflow.js
This has been around for a while it seems, but I didn’t notice
it. It’s produced 30 times by the “we query the API for all
the jobs” test and I haven’t been able to figure it out.
> Add silencing for method-calls-on-destroyed-store

- package-lock.json
This is to address fresh runs of `npm install` caused by the yanking of v5.1.2 of `har-validator`. See [here](https://github.com/ahmadnassri/node-har-validator/issues/112) for further reading on the yank. The author has stated that v5.1.3 is identical to v5.1.0, which is what the `requests` package relies upon.
> Bump har-validator in package-lock.json to latest version (v5.1.3)

- app/templates/help.hbs
Since `Documentation` is more recognizable than `resources`. Thank you!
> update documentation link wording

- app/templates/components/branch-row.hbs
- app/templates/components/builds-item.hbs
- Fix state copy for build history tab to be consistent with rest of `Travis-Web`
> Humanize build states for build history tab

- app/utils/job-config-language.js
- tests/unit/utils/job-config-language-test.js
This avoids the rendering of `[object Object]` when a language
is mis-specified.
It may be that we want something more here, like an alert of
some kind, but this is an interim measure at least.
> Add handling for mis-configured language

- config/deployment/deploy-local.sh
- package.json
This PR enables test deployments from local environment. It works similar to PR deployments, but disabled for staging branches and picks branch from current git head. Basically, it pushes changes to the same subdomain that PR deployments do, so if there is a PR for the branch, the deployments will just be updated and the PR links will still work. Although, it's not necessary to have a PR to deploy test build, the script prints out deployment URLs. 
To deploy current branch just execute `npm run deploy` in project directory.
Of course, in order to upload assets, AWS credentials must be provided as environment variables `AWS_KEY` and `AWS_SECRET`. These could be acquired (generated) in AWS console.
The most convenient way to provide them would be to put them to `.env` file:
``` …
```
> Add ability to deploy travis-web locally

- app/components/top-bar.js
AFAIK this._super should always be called in cases like this.
> Address top bar testing inconsistencies

- .travis.yml
While it would be preferable to understand why some snapshots
are disappearing in Percy runs, this should reduce likelihood
that such will happen on auto-approved master.
> Remove Percy checks on cron jobs

- app/components/job-infrastructure-notification.js
- app/templates/components/job-infrastructure-notification.hbs
For upcoming PHP default update from 5.5 to 7.2
While I was there, also updated precise banner to recommend upgrading to Xenial
I need help evaluating there's not a pinned php version, rather than just the language check, is that feasible?
> Update job banner to message PHP default jobs

- app/models/repo.js
Extracting this small refactoring from https://github.com/travis-ci/travis-web/pull/1949/
It mostly adds some useful shortcuts to the `repo` model for migration status and makes it more reliable.
> Repo model refactoring

- app/styles/app/modules/tooltips.scss
This PR fixes tooltip arrow color.
Ever since update of `ember-tooltip` add-on the arrow was a different color:
Now it's the same color:
> Fix tooltips appearance

- app/components/loading-indicator.js
- app/components/loading-overlay.js
- app/styles/app.scss
- app/styles/app/modules/loading-overlay.scss
- app/templates/components/loading-indicator.hbs
- app/templates/components/loading-overlay.hbs
Another portion of extractions from https://github.com/travis-ci/travis-web/pull/1949/
This PR introduces a new component `loading-overlay` which wraps any content and dims it when `visible=true`. Here's a short demo:
Also this PR adds a `{{loading-indicator single=true}}` mode to `loading-indicator` component that makes it show only one dot instead of three, which may be useful when there's not enough space to show three (like over the checkbox).
> Loading overlay and loading indicator

- app/styles/app/modules/buttons.scss
Modeled after `.button--green`. We have buttons of various colors, why not red as well? Split off from https://github.com/travis-ci/travis-web/pull/1953
> Add red button

- app/components/build-count.js
- app/components/insights-glance.js
- app/templates/components/build-count.hbs
- app/templates/components/insights-glance.hbs
- tests/integration/components/build-count-test.js
- tests/integration/components/insights-glance-test.js
This adds a build-count component that generates a graph displaying build count data, along with some stats. It is one of 4 very similar components, which all utilize the insights-glance component, which handles a lot of the shared functionality.
> Add build-count and insights-glance components

- app/components/active-repo-count.js
- app/templates/components/active-repo-count.hbs
- tests/integration/components/active-repo-count-test.js
Adds an insights-glance component that shows active repositories chart and stats.
> Add insights active-repo-count component

- app/components/queue-times.js
- app/templates/components/queue-times.hbs
- tests/integration/components/queue-times-test.js
Adds an insights-glance component that shows average queue time chart and stats.
> Add insights queue-times component

- app/components/build-minutes.js
- app/templates/components/build-minutes.hbs
- tests/integration/components/build-minutes-test.js
Adds a glance component that shows build minute chart and stats.
> Add insights build-minutes component

- app/services/flashes.js
Split from https://github.com/travis-ci/travis-web/pull/1953
In testing I found that success flash messages behaved somewhat inconsistently, and it seems like the `removeFlash` function was maybe just broken?
It referenced `flashes.content`, which doesn't seem to exist nor is referenced anywhere else. And the `close` function below calls `removeObject` on `flashes` rather than `flashes.content`, so I updated `removeFlash` to match that.
It only affected success messages because `removeFlash` is only called for flash messages without close buttons.
> Make success flash messages behave more consistently

- app/components/insights-privacy-selector.js
- app/templates/components/insights-privacy-selector.hbs
- tests/integration/components/insights-privacy-selector-test.js
This adds the selector on the charts page for choosing whether to look at private build stats (if they're available)
> Add insights privacy selector component

- app/components/build-status-chart.js
Fairly straightforward, addresses this issue: https://github.com/travis-ci/travis-insights/issues/71
Not urgent to review, whenever you have time for it is fine 👍
> Reinstate day of week on tooltips for the build status chart

- app/components/insights-date-display.js
- app/styles/app/base.scss
- app/styles/app/layouts/insights.scss
- app/styles/app/mixins.scss
- app/templates/components/insights-glance.hbs
I noticed in https://github.com/travis-ci/travis-web/pull/1996 that Percy was flagging for review when nothing in the snapshot should have really been different. It seems due to changing dates on the x-axis as well as tiny variations in drawing the line charts. This PR should address that and also provides a way to hide other things from snapshots if we need to in the future.
Reference: https://docs.percy.io/docs/percy-specific-css
> Add a way to hide things from percy snapshots. Apply to insights.

- app/styles/app/modules/navigation.scss
After deploying https://github.com/travis-ci/travis-web/pull/1998 to staging, I noticed a difference in behavior of the navigation in IE/Edge between the deployed and locally run versions. I suspect that the CSS minifier / optimizer is merging together some nearly identical rules during the build for deployment. Testing out this hypothesis.
> Ensure that nav menu styles do not get merged during minification

- app/templates/owner/repositories.hbs
I noticed that percy is flagging the insights page again, based on dynamic content. Since the date range is the current 30 days, different dates in the date display component will have different widths, which causes the content on the right to move.
> Fix issue where date change can cause percy to flag a visual change

- app/styles/app/modules/build-header.scss
When on the build history page on a mobile device, it is possible for the commit message to overflow off the screen. This commit will fix that issue.
> Update style to prevent commit message from overflowing on mobile

- .travis.yml
- Dockerfile
- README.md
Based on https://docs.npmjs.com/cli/install and https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci
> This command is similar to npm-install, except it’s meant to be used in automated environments such as test platforms, continuous integration, and deployment – or any situation where you want to make sure you’re doing a clean install of your dependencies.
> Only use the package-json.lock for npm deps installation

- app/styles/app/modules/build-header.scss
_Fixes https://github.com/travis-ci/bugs-questions-comments-ideas/issues/181_
It looks like Safari doesn't support negative stroke-dashoffset.
https://stackoverflow.com/a/39127818
> Fix jumpy animation on Safari

- app/helpers/format-message.js
- app/templates/components/build-header.hbs
- app/templates/components/builds-item.hbs
_Fixes https://github.com/travis-ci/bugs-questions-comments-ideas/issues/89_
The problem is with RegExp matching a long string without spaces, it takes ~13 seconds on my macbook to process a String with ~2000 chars.
The browser's CPU usage also increases a lot while processing that.
See this JSPerf with an example:
https://jsperf.com/long-string-match/1
The commit message just shows about 50 characters on those 2 pages, my solution is to limit the string to that amount of characters, the UI looks the same and the RegExp matching is faster.
> Slice commit messages

- app/components/build-message.js
- app/styles/app/modules/build-messages.scss
- public/images/config/alert.svg
Build config validation messages have a new level `alert`. This will be used when a plain string is given on a node that represents a secret and a `secure` value should be given:
Before:
After:
> add css class icon-alert and alert.svg for config messages

- app/styles/app/modules/yaml.scss
i believe this fixes the vertical alignment of the line numbers. e.g: https://sf-tweak-line-nums.test-deployments.travis-ci.com/travis-ci/perl-builder/builds/128712741/config
before:
after:
in these recordings i have tried to use the mac osx native zoom feature ... but obviously that wouldn't make it into the recorded gif 🤦‍♂ i hope it's still visible enough ...
> tweak line number styles

- app/styles/app/modules/build-messages.scss
- app/templates/components/build-message-line.hbs
- app/templates/components/build-message.hbs
- config/environment.js
- tests/pages/build.js
if hovered the message has a help icon on the right side, which links to the build config validation docs https://github.com/travis-ci/docs-travis-ci-com/pull/2548 to the respective message type
> add a help icon to build config msgs

- app/components/build-message.js
- app/components/build-messages-list.js
- app/models/request.js
- app/styles/app/modules/build-messages.scss
- app/templates/components/build-messages-list.hbs
- public/images/messages/msg-alert.svg
- public/images/messages/msg-error.svg
- public/images/messages/msg-info.svg
- public/images/messages/msg-warn.svg
- tests/acceptance/config/yaml-test.js
- tests/pages/build.js
The build config validation will be collapsed if only `info` level messages are present, and expanded otherwise.
Expanded: 
Collapsed:
> summarize and toggle config messages

- app/styles/app/layouts/jobs.scss
Currently this is set with `flex-grow: 1` which allows it to grow, but that adds a lot of extra whitespace.
Setting instead the `flex-grow: 0` and `flex-shrink: 1` gives a better experience. It doesn't grow unnecessarily and can shrink a bit at smaller screen widths still (which was already happening).
> Swap flex-grow and flex-shrink styles for .job-arch column

- app/components/build-header.js
- app/components/jobs-item.js
- app/utils/job-config-arch.js
- app/utils/keys-map.js
- tests/integration/components/jobs-item-test.js
- tests/unit/utils/job-config-arch-test.js
After some brainstorming and feedback we decided to change casing for CPU arch labels (because amd64 and arm64 look very similar, especially when you have a long job list)
Also, we need to make a hack to display `ppc64le` arch when `os: linux-ppc64le` in config, because of legacy queue routing logic that is still used by many clients (but will be deprecated soon)
> Make job architecture more visually distinctive

- app/routes/first-sync.js
Reverting this change as it seem to affect analytics in unexpected way.
> Revert preventing first_sync page manual visits

- .env.example
- config/dotenv.js
It turns out that this is less helpful when you're not working on enterprise version. When TRAVIS_ENTERPRISE=false, it behaves as if it is true for some reason. So then you would need to comment it out or remove it to work on non-enterprise version. TRAVIS_PRO doesn't seem to have this problem. So I think it might be best to remove for now
> Remove enterprise dotenv variable

- app/adapters/request.js
- app/components/raw-config.js
- app/components/request-config.js
- app/models/request.js
- app/styles/app/modules/build-messages.scss
- app/styles/app/modules/yaml.scss
- app/templates/components/annotated-yaml.hbs
- app/templates/components/build-messages-list.hbs
- app/templates/components/request-config.hbs
- tests/acceptance/config/yaml-test.js
- tests/pages/build.js
this does:
* allow folding config sources
* fold empty sources by default (api is empty :alot:)
* display resulting build config
* remove the line between the header div and the foldable container (removed this accidentally when trying to remove a duplicate border there when folded, and then found it looked a lot more clean)
needs `travis-api/sf-request-config`: https://github.com/travis-ci/travis-api/pull/980
> tweak build config view

- app/components/build-tabs.js
- app/components/job-tabs.js
- app/templates/components/build-tabs.hbs
- app/templates/components/job-tabs.hbs
The `<LinkTo` components handle highlighting automatically on the build.index / build.config / job.index / job.config routes. This functionality covers the case where the log tab should be highlighted on parent pages like https://so-job-tabs-remove-jquery.test-deployments.travis-ci.com/travis-ci/travis-web
> Remove jQuery from build and job tab components

- app/components/repos-list-item.js
I changed to using `window.pageYOffset` because `window.scrollY` is not supported by IE. Some info: 
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY
https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset
> Remove jquery from repo-list-item component

- app/components/dialogs/migrate-beta.js
- app/templates/components/dialogs/migrate-beta.hbs
- app/templates/components/owner/migrate.hbs
While we removed the "wait" from the waitlist for the migration beta some time ago, I neglected when rolling out that change to remove all references to a waitlist within the UI. As users are immediately accepted, I didn't think much of it at the time. Unfortunately, this has resulted in some confusion, so needs to be addressed.
> Fix ui migration confusion

- app/services/tasks.js
I was doing some testing on staging and noticed a 500 error on beta_migration_requests endpoint when going to /account/subscription. It seems it was due to the `travis-api-version` header being set to 3
> Fix issue where migration requests request would get a 500 error

- app/services/ajax.js
- app/services/api.js
This should address an issue where the help page zendesk form is erroring. The X-Client-Release header, I believe should only be relevant to our API, and very few things use the ajax service directly, so I don't think this change should cause problems
> Move client release header to api service

- app/styles/app/pages/help.scss
Issue description:
When user sends a form to Zendesk the success image scales to the page width and looks giant.
> Fix success image size on help page

- app/utils/log-folder.js
I noticed while doing some testing on staging, the log jquery removal introduced an issue where clicking on a line within a fold closes the fold. It should only be clicking on the first line that toggles a fold. Some URLs where you can test:
https://so-fix-log-fold-issue.test-deployments.travis-ci.com/travis-ci/travis-web/builds/139577193
https://so-logs-remove-jquery.test-deployments.travis-ci.com/travis-ci/travis-web/builds/139577193
https://staging.travis-ci.com/travis-pro/test-repo-staging1/jobs/490940
https://travis-ci.com/travis-ci/travis-web/builds/139577193
> Fix issue where clicking on fold child closes fold

- app/services/auth.js
- app/services/storage.js
Feature flags are cached for performance reasons in local storage. Currently, when you log out, these are not cleared. If you're logged in in another browser window, these flags will never be updated, as we assume they haven't changed, so you'll have to repeat the action.
With this PR, this data is cleared, meaning that when you make an update in one browser window and log out, you'll get the desired settings upon your next login.
> Ensure feature flags are removed on signout

- app/mixins/components/with-config-validation.js
- app/models/repo.js
This change prevents `fetchSettings` from spamming API when user is unauthenticated
> Fix repo setting fetching for unauthorized users

- app/styles/app/modules/build-header.scss
It was reported that the apple logo at the bottom left of the build info box looked misaligned. For example:
https://travis-ci.com/travis-ci/dpl/jobs/280674895
Compare that with
https://so-realign-build-os-icon.test-deployments.travis-ci.com/travis-ci/dpl/jobs/280674895
> Address issue where build os icon is not aligned with other icons/text

- app/routes/travisci-vs-jenkins.js
- tests/acceptance/marketing/travisci-vs-jenkins-test.js
Part of https://github.com/travis-ci/travis-web/pull/2293
With the back and forth going on about this page, I'd like to hide it behind a feature flag, and merge the epic branch into master. There are some UI kit changes in the epic branch that would be nice to have for bb integration work.
> [TVJ] hide behind flag

- app/services/feature-flags.js
Currently, the bitbucket and assembla feature flags cannot be meaningfully set via env var, because of the way the setting of the flags from localstorage works. With the current logic, unless the correct localstorage key is set to 'true', the flag is disabled upon init of the `feature-flags` service. So even if you enable it via env var, it becomes immediately disabled on initial page load. I've updated the logic to only disable if the relevant localstorage key is set to 'false'.
Ultimately, I would like to remove this stuff entirely. It's not really necessary now that we can set the flags via env var, and it doesn't really belong in the feature flags service. But since Artur Kremens team uses these localstorage flags for testing, we should possibly wait or communicate/coordinate such a …
> [BB] update vcs localstorage flags logic

- app/templates/components/my-build.hbs
When we removed the provider icon from the dashboard repositories list we forgot to remove it from my builds. So, fixed 🚀
> Remove provider icon from my builds list

- app/components/jobs-item.js
- app/templates/build/index.hbs
- app/templates/components/jobs-list.hbs
`job.config.env` will include global env vars going foward. this makes displaying all env vars on the jobs list noisy and hard to parse.
this example build has one global env var `JOBS=1` which we want to hide from the env vars on the jobs list: https://travis-ci.org/svenfuchs/test/builds/658768955
before:
after:
> hide global env from jobs list

- app/components/insights-overlay.js
- app/styles/app/layouts/insights.scss
For: https://travisci.assembla.com/spaces/VCS/tickets/realtime_cardwall?ticket=137
A fix is on staging, have a look with firefox, should align properly https://staging.travis-ci.com/bitbucket/OlaTestAssembla?tab=insights&timeInterval=week
> fix insights alignment

- app/components/scroll-here.js
- app/templates/integration.hbs
Addresses an issue noted by Petra. To Reproduce:
1. Make sure you are signed out
2. Go to `/`
3. Scroll down to the Learn More button in the bitbucket section. The issue is more noticeable the further you scroll
4. Click the Learn More button
5. It will correctly lead to `/integration/bitbucket`, but you will be partially scrolled down on the page
Compare:
https://travis-ci.com/
https://so-fix-bb-landing-scroll.test-deployments.travis-ci.com/
Although, I'm not sure this is much better. Let me know what you think
> BB Landing page - Scroll to top on page load

- app/templates/travisci-vs-jenkins/index.hbs
Minor thing I noticed today: A faint line in the middle of the Case Study button at the bottom of the jenkins page. Compare:
https://travis-ci.com/travisci-vs-jenkins
https://so-adjust-case-study-button.test-deployments.travis-ci.com/travisci-vs-jenkins
> Remove line from middle of case study button

- app/components/repo-status-badge.js
- app/components/repository-layout.js
- app/templates/components/header-links.hbs
- app/templates/components/repo-status-badge.hbs
- app/templates/components/repository-layout.hbs
- tests/acceptance/repo/show-test.js
- tests/pages/repo/show.js
For https://travisci.assembla.com/spaces/VCS/tickets/145/details
I've been testing like this:
1. Create a new repo on provider with simple tests. A basic ember project works well, and to make this faster I've just been forking one that I already have.
2. Activate repo on travis if needed
3. Go to the repo page and trigger a build. Watch as the build completes, observing the status button.
4. Flip through tabs on completion
This regularly reproduces the issue on prod for me. I suspect it may be a caching thing, so I added a status-based query param to the image displayed on `travis-web`. Compare:
https://travis-ci.com/
https://so-fix-build-status-img-2.test-deployments.travis-ci.com/
I've seen this for both github and bitbucket, but if you want to test with bb, I would test on staging, …
> Fix build status image update issue

- app/components/build-message.js
This adds 6 new message types that Yml now produces when things are being skipped via `if` conditions.
It also moves the `<code>` tag to the `format` function in order to reduce the work needed to add such new messages.
> Add new skip_[type] messages

- app/templates/components/dashboard-row.hbs
For: https://travisci.assembla.com/spaces/VCS/tickets/161-align-loader-properly-on-a---39-trigger-a-build--39--button/details
To test, on the dashboard, using a repo that does not have any builds yet, click the 'Trigger a build' button on master/production and compare to test deployment.
> align loading indicator

- .travis.yml
Moves a duplicate `env` key, and adds an explicit `os` key, as suggested by build config validation
> Clean up build config

- tests/integration/components/add-ssh-key-test.js
- tests/integration/components/ssh-key-test.js
A couple of percy snapshots are incorrectly flagged as changed fairly often. I thought about trying 
to await settled or something like that for them, but then realized that I'm not sure we want or need snapshots inside of component integration tests. I think it makes more sense to utilize them in acceptance tests. So I removed them.
> Adjust flaky percy snapshots

- app/utils/countries.js
The accounts department requested to add Canary Islands in the list of countries, it comes under Spain, however not part of the EU so not VAT should be associated with it.
https://github.com/travis-pro/billing-v2/issues/525
> added Canary Islands to the list of countries

- public/images/svg/community.svg
For https://travisci.assembla.com/spaces/Web/tickets/304/details
Some background info: ID collisions between elements within different SVGs has caused various issues with the display of gradients, colors, etc within SVGs. In the past this was handled with ID changes and other tricks within individual SVGs. More recently, a more universal approach was implemented by changing SVGO settings in `ember-cli-build.js` (namely,  auto-generated ID prefixes was enabled). This now automatically handles these issues for the most part, but seems like it didn't work well with an old fix within the help page "community" svg. Removing the old fix seems to resolve all issues.
I looked to see if there were any other SVGs having a similar issue, but it appears not.
To test, deploy to staging and compare …
> Fix community SVG display

- config/deployment/deploy-local.sh
- config/deployment/deploy-pull-request.sh
- config/deployment/deploy-test-master.sh
- config/deployment/store-redis-urls.sh
Travis web PR deployments are using hobby-dev instance of redis on heroku. URL of these instances aren't constant which causes errors in travis-web-next app. 
I've prepared redis instance with static IP and would like to set redis urls via travis job env vars.
> Remove heroku redis urls

- app/controllers/signin.js
- app/services/multi-vcs.js
- app/templates/components/landing-default-page.hbs
- app/templates/components/multi-signin-button.hbs
- app/templates/signin.hbs
- config/providers.js
- tests/acceptance/layouts/plans-test.js
I have ended up with a slightly different solution rather than just disabling Github via env variable. With the new solution you should be able to re-define default provider via `DEFAULT_PROVIDER` environment variable. Default provider will always be enabled. Other providers are optional and if they aren't explicitly enabled via feature flag, they won't be available for login.
> Change default provider handling

- app/components/billing/select-addon.js
- app/templates/components/billing/select-addon.hbs
if user tries to change plan after canceling addon purchase, previously selected addon is displayed on the order summary page
> Fix for addon purchase process

- app/templates/plans/index.hbs
OSS credits are now granted only after filing request with Travis Support.
Free plan replaces trial and does not have renewable credits.
> Text changes to reflect change in policy

- app/templates/components/billing/summary-v2.hbs
Remove 'macOS' text for a hybrid plan on the plan page
> Remove 'macOS' text for a hybrid plan on the plan page

- app/components/profile-nav.js
- app/models/owner.js
- app/templates/components/profile-nav.hbs
- tests/acceptance/profile/plan-usage-test.js
Hide Plan Usage tab from users without credits. Related assembla issue [BSFY-6](https://travisci.assembla.com/spaces/Bugfix-Service-FY-2022/tickets/realtime_cardwall?ticket=6)
> Hide Plan Usage tab from users without credits

- app/components/billing/auto-refill.js
* Hid autorefill switch for free plans
* Additional fix
* Revert unnecessary changes
* Revert unnecessary changes
* Deleted trailing spaces
* Break too long line into two lines
* Fix
Co-authored-by: Ivan Dmytrenko <dmytrenko.i.t@gmail.com>
> Hid autorefill switch for free plans (#2644)

- app/helpers/format-number.js
- app/templates/components/billing/auto-refill.hbs
- app/templates/components/billing/credit-balance.hbs
- app/templates/components/billing/first-plan.hbs
- app/templates/components/billing/select-addon.hbs
- app/templates/components/billing/selected-plan.hbs
- tests/acceptance/profile/billing-test.js
- tests/integration/components/billing/select-addon-test.js
Formatted number of credits to separate thousands parts, e.g. 30 000 (many EU countries, US too) or 30,000 (EU countries/accounting formats)
changes made in:
- plan selection
- after plan is selected
- when showing pool of credits vs used credits on plan page
- addons selection page
- auto-refill boxes
> PDTQ-163 - [Pricing] travis-web - everywhere on plans page format number of credits to be more readable

- app/components/billing/select-plan.js
Continuation of https://github.com/travis-ci/travis-web/pull/2862
Missed sorting plans on these scenarios:
- first-plan: account_activation page > "Change Plan" modal
- when plan is expired for more than a month
> [Hotfix] Sort available plans on first-plan and when plan is expired for more than a month

- app/models/v2-plan-config.js
#[PDTQ-161](https://travisci.assembla.com/spaces/Product-and-Dev-Tickets-Queue/tickets/161--pricing--10m-users-in-plan-page-in-travis-web-instead-of---39-unlimited--39/details
) - [Pricing] 10M users in plan page in travis-web instead of 'unlimited'
> PDTQ161 - [Pricing] 10M users in plan page in travis-web instead of 'unlimited'

- app/components/account-env-var.js
- app/components/add-account-env-var.js
- app/controllers/account/settings.js
- app/controllers/organization/settings.js
- app/models/owner.js
- app/styles/app/layouts/settings.scss
- app/styles/app/modules/forms.scss
- app/templates/account/settings.hbs
- app/templates/components/account-env-var.hbs
- app/templates/components/add-account-env-var.hbs
- app/templates/organization/settings.hbs
- mirage/models/organization.js
- mirage/models/user.js
- tests/integration/components/account-env-var-test.js
- tests/integration/components/add-account-env-var-test.js
Pull Request contains changes related to recaptch Dockerfile that were needed for testing, before merge we need to remove these commits.
> Tbt 137 account env vars

- app/components/billing/authorization.js
[TBT-310](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=310) - [Bug-Trial] Not getting credits for bought addons], PR: trial addons purchase disabled (#2968)
> Release 2025 05 07
