app/utils/keys-map.coffee

See https://github.com/travis-ci/travis-core/pull/447#issuecomment-90778056.

Add haxe key.

---

app/models/job.coffee
app/styles/app.scss
app/styles/app/layouts/buildheader.sass
app/styles/app/layouts/profile.sass
app/styles/app/modules/icons.sass
app/styles/app/modules/notice.sass
app/styles/app/modules/tiles.sass
app/styles/app/popup.sass
app/templates/components/hooks-list-item.hbs
app/templates/jobs/pre.hbs
app/templates/profile/show.hbs
app/templates/profile/tabs/user.hbs
app/views/pre.coffee
app/views/status-images.coffee
public/images/svg/notice-flag.svg

[wip] display notice for legacy infrastructure

---

app/utils/keys-map.coffee

See https://github.com/travis-ci/docs-travis-ci-com/pull/253 for more detailed information.

Add Perl6 to matrix

---

app/utils/pusher.coffee

Add `job:queued` as a known Pusher event.

Handle job:queued events

---

app/routes/settings.coffee
app/styles/app/layouts/requests.sass
app/templates/account.hbs
app/templates/components/ssh-key.hbs
app/templates/settings.hbs
tests/integration/components/ssh-key-test.js

Check user permissions and if they're allowed to add/remove ssh keys on the settings page

ssh key permissions

---

app/index.html

For all the people who like to :surfer: without JS, a little reminder that Travis needs it.
Looks like this:

add simple noscript notice

---

app/routes/dashboard/repositories.coffee
app/routes/owner.coffee
app/routes/owner/repositories.coffee
app/templates/components/owner-repo-tile.hbs

@drogus so I tried to hack the auth header in there, but I still get a 404. What am I doing wrong?

Authenticate owner request

---

app/utils/status-image-formats.coffee
app/views/status-images.coffee

RST is abbreviation of reStructuredText.
Using Rst is plain wrong, it would be good to use RST or reStructuredText.

Change Rst ro RST

---

app/utils/keys-map.coffee

Ref https://github.com/travis-ci/travis-build/pull/526 and https://github.com/travis-ci/travis-core/pull/481

Add crystal language key

---

app/utils/keys-map.coffee

add osx_image to keys-map

---

app/templates/plans.hbs

simple fix to a typo on the landing page.

fix typo ulimited to unlimited

---

.travis.yml
app/routes/team.coffee

**Infrastructure Conductor** =D

Tweaking solarce's title

---

app/components/log-content.js
app/styles/app.scss
app/styles/app/layouts/repo.sass
app/styles/app/main/log.sass
app/styles/app/modules/buttons.sass
app/styles/app/modules/icons.sass
app/templates/components/log-content.hbs
app/templates/components/repo-show-tools.hbs

for https://github.com/travis-pro/team-teal/issues/618
Edit: This is working as good to merge. It's not the "fullscreen" solution discussed in the ticket, but as close as I can get right now. I'd like to revisit this in the future

Mobile log

---

app/templates/account.hbs

Not sure this makes sense but I felt making this button a component is overkill. Opinions?

remove deprecations

---

app/services/ajax.js

don't send data body if it is empty

---

config/deprecation-workflow.js
tests/unit/components/branch-row-test.js
tests/unit/components/build-repo-actions-test.js
tests/unit/components/builds-item-test.js
tests/unit/components/caches-item-test.js
tests/unit/components/hooks-list-item-test.js
tests/unit/components/job-repo-actions-test.js
tests/unit/components/jobs-item-test.js
tests/unit/components/jobs-list-test.js
tests/unit/components/loading-indicator-test.js
tests/unit/components/owner-repo-tile-test.js
tests/unit/components/repo-actions-test.js
tests/unit/components/travis-status-test.js
tests/unit/components/user-avatar-test.js
tests/unit/mixins/polling-test.js

Replacing with `render` to appease the test suite gods.

Remove append() test deprecations

---

app/routes/team.js

I forgot about my twitter handle :)

add twitter handle for laura in team page

---

app/templates/settings.hbs

Resolves https://github.com/travis-ci/travis-ci/issues/5611.

Add note for escaping bash special characters

---

app/components/orgs-filter.js
app/components/repo-show-tools.js
app/styles/app/components/sync-button.sass
app/styles/app/layouts/dashboard.sass
app/styles/app/layouts/owner.sass
app/styles/app/layouts/profile.sass
app/styles/app/layouts/repo.sass
app/styles/app/mixins.sass
app/styles/app/modules/dropdown.sass
app/styles/app/modules/switch.sass
app/templates/components/orgs-filter.hbs
app/templates/components/repo-show-tools.hbs
app/templates/components/sync-button.hbs
app/templates/dashboard/repositories.hbs

again some updates to the UI
So far:
- the sync button
- revamped org filter

Updating some UI elements

---

app/components/user-avatar.js
app/styles/app/layouts/pull-requests.sass
app/styles/app/layouts/settings.sass
app/styles/app/modules/avatar.sass
app/styles/app/modules/build-header.sass
app/styles/app/modules/icons.sass
app/styles/app/modules/row.sass
app/styles/app/modules/status-icon.sass
app/styles/app/modules/switch.sass
app/templates/components/branch-row.hbs
app/templates/components/build-header.hbs
app/templates/components/builds-item.hbs

- fix env var display
- fix icon/ avatar spacing

some UI fixes after the update

---

app/templates/plans.hbs

Just a quick typo fix.
Thanks to Lachlan who reported the typo!

fix typo "annually"

---

app/styles/app/modules/sync-button.sass
app/styles/app/pages/getting-started.sass
app/templates/account.hbs
app/templates/components/team-member.hbs
app/templates/getting-started.hbs

- remove case-sensitivity notice from getting_started
- remove 'Sign up this account' button on Enterprise
- fix UI issue on sync button
- add title attributes to team flags

Multiple smaller updates

---

app/templates/components/requests-item.hbs

As requested by @BanzaiMan in travis-pro/team-teal#807

Add title attribute for request message

---

.travis.yml

@drogus mentioned that he believes this has caused issues in the past, so this is somewhat experimental. It does seem to be working, however.

Cache bower packages

---

app/templates/account.hbs
mirage/config.js
mirage/factories/account.js
mirage/factories/hook.js
mirage/models/account.js
mirage/models/hook.js
tests/acceptance/profile-test.js
tests/pages/profile.js

This is not ready, it’s just one assertion to start with.

Profile route acceptance test

---

.travis.yml

I am pretty sure this is just an artifact of a bygone era. @drogus can you confirm?
Also, curious what you and @backspace think about setting up slack notifications as an alternative?

Remove campfire notifications

---

app/components/build-header.js

display the job id in a data-attribute on the build header

---

tests/.jshintrc
tests/acceptance/builds/restart-test.js
tests/acceptance/profile-test.js
tests/helpers/sign-in-user.js
tests/helpers/start-app.js

As [suggested by @drogus](https://github.com/travis-ci/travis-web/pull/519#issuecomment-214292999).

Rename to signInUser

---

.travis.yml
app/components/repo-actions.js
app/controllers/repo.js
app/mixins/repo-actions-item-component-mixin.js
app/models/build.js
app/models/job.js
app/models/repo.js
app/serializers/build.js
app/services/update-times.js
app/utils/eventually.js
config/environment.js
tests/unit/serializers/build-test.js
tests/unit/utils/eventually-test.js

This PR enables API V3 again and fixes a few things that were either not checked properly when I originally wrote the code or broke during the time this option was disabled.

Use API V3 - take two

---

app/templates/home.hbs

As suggested [here](https://secure.helpscout.net/conversation/199383136/28734/?folderId=30784) by @evnm.

Change title of testimonial

---

README.md

It just looks so much sharper!

Use the Travis CI SVG badge instead of PNG

---

app/routes/application.js
package.json
waiter/config.ru
waiter/lib/travis/web/app.rb

Since [Segment integration](https://github.com/travis-ci/travis-web/pull/544) will take a while and I’m off next week, this just removes Pendo.

Remove Pendo

---

app/components/cron-job.js
app/models/cron.js
app/styles/app/layouts/settings.sass
app/templates/components/cron-job.hbs
tests/acceptance/repo-settings-test.js
tests/pages/settings.js

Instead of the next enqueuing the concrete interval is now shown:
This depends on travis-ci/travis-api#266.

Cron interval

---

app/components/add-cron-job.js
app/components/cron-job.js
app/models/cron.js
app/styles/app/layouts/settings.sass
app/styles/app/modules/forms.sass
app/templates/components/add-cron-job.hbs
app/templates/components/cron-job.hbs
tests/acceptance/repo-settings-test.js
tests/pages/settings.js

Clarify cron time UI

---

app/templates/components/build-header.hbs

Should fix this issue https://github.com/travis-ci/travis-ci/issues/6108#event-675372949

fix wrong timestamp on running jobs/builds

---

app/components/requests-item.js
app/styles/app/layouts/requests.sass
app/styles/app/modules/buttons.sass
app/styles/app/modules/forms.sass
app/styles/app/modules/switch.sass
app/templates/account.hbs
app/templates/components/build-header.hbs
app/templates/components/requests-item.hbs
app/templates/components/subscribe-button.hbs
app/templates/settings.hbs

Sooo, I'm not sure why branches are currently not displayed on the requests page. Everything looks fine, but it's just not there?
This ^ is the view in question

Add branches to requests page

---

app/components/branch-row.js
app/templates/branches.hbs
mirage/config.js
mirage/models/branch.js
mirage/models/build.js
mirage/models/commit.js
mirage/models/user.js
mirage/serializers/branch.js
mirage/serializers/build.js
mirage/serializers/commit.js
mirage/serializers/user.js
tests/acceptance/repo-branches-test.js
tests/pages/branches.js

Here is a beginning for an [acceptance test for the branches route](https://github.com/travis-ci/travis-web/pull/563). I’m hoping this one is less involved!

Branches route acceptance test

---

app/templates/components/builds-item.hbs
mirage/config.js
tests/acceptance/repo-pull-requests-test.js
tests/pages/pull-requests.js

This is another step in the [ongoing saga of adding acceptance tests](https://github.com/travis-pro/team-teal/issues/687).
It looks like this will overlap significantly with my previous pull request for the repository branches route. So I hope to extract some shared functionality. My other goals in this pull request are to:
* create a true V3 Mirage serialiser
* figure out how to get Mirage models to have dynamic properties ([more](https://github.com/travis-ci/travis-web/pull/563#issuecomment-226842717))
* maybe? extract fixtures or common setup code for Mirage factories

Pull requests acceptance test

---

app/styles/app/layouts/profile.sass

I missed a color in the last style updates!

use right hover color on profile

---

app/templates/logo.hbs

This is a potential fix for [this](https://github.com/travis-pro/team-teal/issues/980).

Change to absolute paths

---

app/controllers/owner.js

This PR Backports #585 to the current enterprise branch. 
/cc @drogus - Heads up! Since you worked on it! 
/cc @joshk @danishkhan - Heads up for general Enterprise bug tracking!

Backport: Fix GitHub link on owner page for enterprise

---

app/utils/keys-map.js

This is a companion PR to travis-ci/travis-build#745.

Add Nix to keys-map.js.

---

app/adapters/repo.js
app/controllers/repos.js
app/models/build.js
app/models/repo.js
app/services/store.js
config/environment.js

Given the recent rollout of v3 (this time w/o issues), it seems a good opportunity to remove some of the indirection and noise the feature flag conditionals are causing

Remove v3 repo feature flag and conditionals

---

app/components/caches-item.js
app/controllers/caches.js
app/initializers/configure-inflector.js
app/templates/caches.hbs
app/templates/components/caches-item.hbs
config/environment.js
mirage/config.js
mirage/models/cache.js
mirage/models/repository.js
tests/acceptance/repo-caches-test.js
tests/pages/caches.js

This is the [final checkbox](https://github.com/travis-pro/team-teal/issues/687)! 🎉

Repository caches acceptance test

---

app/styles/app/modules/avatar.sass

fixing two issues with the 'pseudo avatar'

fix different issues with avatars

---

app/styles/app/layouts/broadcasts.sass
app/styles/app/modules/avatar.sass
app/styles/app/modules/tooltips.sass

- introduce another media query for requests
- make avatar overwrite more explicit
- fix broadcasts messages bleeding into close icon

Fix requests, avatar, broadcasts

---

config/deploy.js
config/deployment/deploy-pull-request.sh
config/deployment/update-github-status.sh
ember-cli-build.js

There are several things that may remain but this is a start.

Add pull request deployments to com-production

---

tests/acceptance/job-view-test.js
tests/pages/build.js

This addresses the lack of an acceptance test for a build with multiple jobs.

Add build matrix acceptance test

---

app/components/job-log.js
bower.json
package.json

Also fix `Binding` deprecations by replacing with `alias`

Upgrade Ember and Ember Data to 2.7

---

app/components/jobs-item.js
app/utils/job-config-language.js
tests/acceptance/job-view-test.js
tests/unit/utils/job-config-language-test.js

Show job language when not versioned

---

package.json

There's a new release for ember-qunit-nice-errors (included here https://github.com/travis-ci/travis-web/pull/631) that supports all assertions.

Upgrade ember-qunit-nice-errors to 1.0.0

---

config/environment.js
ember-cli-build.js
testem.js

Only creating this as a PR because I want to ensure these changes don't somehow negatively impact deploys.

Fix some ESLint errors, remove references to JSHint

---

app/components/hook-switch.js
app/templates/account.hbs
app/templates/components/hook-switch.hbs
app/templates/components/hooks-list-item.hbs

- link repos to Travis and not to Github
- refactor some component/template logic

Improve UX on profile page

---

app/routes/team.js

I've been using this in Slack for a while.

Update job title for Henrik

---

app/controllers/top.js
app/routes/basic.js
app/routes/owner.js
tests/acceptance/profile/redirect-test.js

Given the invasiveness of the change, it would be good to overhaul this
as soon as possible.

Fix profile page redirect by overriding basic route behavior

---

app/styles/app/modules/sync-button.sass
app/templates/components/build-header.hbs
app/templates/components/requests-item.hbs

- remove duplicate subject line from PR build header
- use darker color for sync button pro profile page

some minor bug fixes

---

app/components/log-content.js
config/environment.js
tests/acceptance/job/basic-layout-test.js
tests/helpers/start-app.js
tests/helpers/wait-for-element.js
tests/pages/job.js

This is mysteriously broken, but hopefully I’ll figure that out soon.

Add assertions for log truncation

---

tests/acceptance/builds/branches-tab-test.js
tests/acceptance/builds/cancel-test.js
tests/acceptance/builds/current-tab-test.js
tests/acceptance/builds/restart-test.js
tests/acceptance/job/basic-layout-test.js
tests/acceptance/job/build-matrix-test.js
tests/acceptance/job/cancel-test.js
tests/acceptance/job/log-error-test.js
tests/acceptance/job/restart-test.js

As discussed [here](https://travisci.slack.com/archives/web/p1473685290000015).

Remove redundant comments

---

app/styles/app/mixins.sass
app/styles/app/modules/notice.sass
app/templates/account.hbs

make subscription status a proper notice

---

app/templates/components/owner-repo-tile.hbs
mirage/config.js
mirage/models/repository.js
mirage/serializers/owner.js
tests/acceptance/owner/repos-test.js
tests/pages/owner.js

Owner repositories acceptance test

---

package.json

This is a followup to #671, thanks to this release:
https://github.com/brandonjmckay/ember-prism/pull/18#issuecomment-250299107

Update to released version of ember-prism

---

app/components/add-env-var.js
app/components/not-active.js
app/components/status-icon.js
app/controllers/repos.js
app/locations/auth-dependent.js
app/models/build.js
app/models/job.js
app/models/repo.js
app/models/user.js
app/services/flashes.js
app/services/permissions.js
app/services/polling.js
app/services/raven.js
app/services/update-times.js
app/utils/expandable-record-array.js
app/utils/helpers.js
bower.json
package.json
tests/acceptance/repo/settings-test.js
tests/pages/settings.js

This also upgrades Ember Data to 2.8.0 and removes all relevant deprecation warnings.  I'm no longer seeing the issue that we saw when upgrading to 2.7.1 🎉

Upgrade to Ember 2.8.1

---

app/styles/app/modules/forms.sass

Fix layout issue for cron select boxes on mid-sized screens

more width to select boxes

---

config/deployment/deploy-pull-request.sh

[This branch](https://github.com/travis-ci/travis-web/pull/723) has revealed to me a bug in PR deployments.

Add lowercasing when cleaning branch name

---

tests/acceptance/job/basic-layout-test.js
tests/pages/job.js

This makes assertions about folds and ANSI colour/formatting codes.

Add log-rendering acceptance test

---

package.json

Upstream fixes for usage with Glimmer 2:
https://github.com/kimroen/ember-cli-document-title/compare/41790e1a7b4f396a63bace220ed22e9a0824ca31...0c3b9923414406bffd6f748acf5fa6b29d56921e

Update ember-cli-document-title to support Glimmer 2.

---

app/templates/home.hbs
app/templates/signin.hbs
app/templates/top.hbs

As suggested by @chancancode here:
https://embercommunity.slack.com/archives/dev-ember/p1478547948004114
This appears to make the site entirely functional on the
current canary version of Ember! 🎉

Remove quotes from action targets

---

app/services/update-times.js

---
Note, didn't run tests. Just noticed via GH, and issues don't appear to be enabled. So this is my pseudo issue, they may fix the issue.

fix auto-run

---

app/components/queued-jobs.js
app/components/running-jobs.js
app/controllers/repo.js
app/controllers/repos.js
app/services/update-times.js
bower.json
ember-cli-build.js
package.json

This is an in-house branch with @stefanpenner’s #774. I’m also going to look at NPM/Browserifying `Visibility`.

Fix visibility auto-run

---

package.json
tests/integration/components/branch-row-test.js
tests/integration/components/owner-repo-tile-test.js
tests/unit/components/build-repo-actions-test.js
tests/unit/components/builds-item-test.js
tests/unit/components/caches-item-test.js
tests/unit/components/hooks-list-item-test.js
tests/unit/components/job-repo-actions-test.js
tests/unit/components/jobs-item-test.js
tests/unit/components/jobs-list-test.js
tests/unit/components/loading-indicator-test.js
tests/unit/components/no-builds-test.js
tests/unit/components/travis-status-test.js
tests/unit/components/user-avatar-test.js
tests/unit/helpers/format-config-test.js
tests/unit/mixins/polling-test.js
tests/unit/models/commit-test.js
tests/unit/serializers/build-test.js
tests/unit/services/polling-test.js
tests/unit/utils/computed-limit-test.js
tests/unit/utils/eventually-test.js
tests/unit/utils/favicon-manager-test.js
tests/unit/utils/hash-storage-test.js
tests/unit/utils/job-config-language-test.js
tests/unit/utils/limited-array-test.js
tests/unit/utils/status-image-formats-test.js

This was the hardest part of the most recent Ember-CLI 2.9.1 upgrade, so extracting this into its own commit until we can sort out the other issues we encountered.

Upgrade QUnit to 2.0

---

app/components/not-active.js
tests/acceptance/repo/not-active-test.js

We get a fix from api https://github.com/travis-ci/travis-api/pull/344#issuecomment-259319697

Adjust repo permissions for `not-active` component

---

tests/unit/utils/favicon-manager-test.js

Hi @backspace,
doing my hour-a-day's worth of studying your app, saw more things like the ones we looked at in the past couple of days.
Took the liberty of removing one `assert.ok(!...` in favor of `assert.notOk(...` just like one in a recent update you guys made.
I was also wondering about a number of `let`s, for example:
```
let done = assert.async();
```
if that shouldn't be a `const`, or if it makes much of a difference at all :)
Anyway...will be glad to help out with those things if you think it's worthwhile.
Thanks always,
Gus

Declare with const and fix typo in utils test

---

app/utils/log-folder.js

This should fix this Sentry issue: 182927139.

Guard against non-existent element

---

package.json

This should address rebuilding issues when switching git branches and certain files are no longer present in the new/old branch.
See https://github.com/broccolijs/broccoli-merge-trees/issues/50

Upgrade broccoli-merge-trees

---

app/utils/log.js

Also pre-emptively add some more guards to code that would probably have the same issues.

Fix another log error

---

app/templates/caches.hbs
app/templates/components/branch-row.hbs
app/templates/components/build-header.hbs
app/templates/components/builds-item.hbs
app/templates/components/caches-item.hbs
app/templates/components/cron-job.hbs
app/templates/components/env-var.hbs
app/templates/components/hook-switch.hbs
app/templates/components/jobs-item.hbs
app/templates/components/jobs-list.hbs
app/templates/components/limit-concurrent-builds.hbs
app/templates/components/org-item.hbs
app/templates/components/repo-show-tools.hbs
app/templates/components/repos-list-item.hbs
app/templates/components/request-icon.hbs
app/templates/components/requests-item.hbs
app/templates/components/running-jobs.hbs
app/templates/components/show-more-button.hbs
app/templates/components/ssh-key.hbs
app/templates/components/status-icon.hbs
app/templates/repo.hbs
app/templates/top.hbs
ember-cli-build.js

As suggested here:
https://github.com/minutebase/ember-inline-svg#atrociously-slow-build-times-
In my quite-informal testing, this brought a fresh build time
down from almost two minutes to less than 20 seconds.

Add path restriction for ember-inline-svg

---

app/controllers/top.js
app/routes/application.js
app/templates/signin.hbs

Reference auth service instead of auth controller

---

app/utils/log.js

I think that we're currently playing whack-a-mole with these exceptions,
but we don't have the bandwidth to rewrite this now. So small fixes
until at least Q1 2017.

Add another guard to address a reported Sentry issue

---

app/adapters/application.js
app/adapters/v3.js
app/models/build.js
app/routes/getting-started.js

According to the comments, these changes could have been made some time ago. Just doing some cleanup.

Check off some TODO items

---

app/styles/app.scss
app/styles/app/layouts/log.sass
app/styles/app/layouts/repo.sass
app/styles/app/modules/buttons.sass
app/styles/app/modules/dropdown.sass
app/styles/app/modules/icons.sass
app/templates/components/log-content.hbs
app/templates/components/owner-repo-tile.hbs
app/templates/components/repo-show-tools.hbs
app/templates/owner.hbs
public/images/stroke-icons/icon-deletelogs.svg
public/images/stroke-icons/icon-downloadlogs.svg
tests/pages/owner.js

- fix alignment of tofuburger 
- inline svg on owner page
- inline svg on logs buttons

Some UI fixes

---

app/components/build-header.js
app/services/external-links.js
app/templates/components/build-header.hbs
ember-cli-build.js
package.json
tests/integration/components/build-header-test.js
tests/unit/services/external-links-test.js
tests/unit/utils/urls-test.js

Add link to branch in build header

---

app/controllers/top.js

This collapses three list operations into one.

Refactor broadcast processing

---

app/components/job-infrastructure-notification.js
app/templates/components/job-infrastructure-notification.hbs

This is a followup to [this PR](https://github.com/travis-ci/travis-web/pull/837).
I’ll update with links to examples once there’s a deployment.

Update macOS infrastructure messages

---

.travis.yml

I think this makes more sense, as a PR that has approved visual
diffs will have that become the new baseline… I think???

Change Percy to only run on pushes

---

app/index.html
tests/index.html

This is an in-team continuation of #851. Thanks to @fotinakis!

Add fonts to test environment

---

app/styles/app.scss
app/styles/app/layouts/settings.sass
app/styles/app/modules/badge.sass
app/styles/app/modules/tooltips.sass
app/templates/components/cron-job.hbs
app/templates/settings.hbs

Add crons badge

---

app/styles/app/modules/badge.sass
app/templates/settings.hbs

Hide cron form if there are no branches

---

app/templates/settings.hbs

... because we're making them GA

Don't check for crons feature flag

---

app/routes/settings.js

to check if ssh key feature is actually enabled

update ssh key fetch logic

---

app/components/loading-indicator.js
app/routes/signin.js
app/styles/app/layouts/content.sass
app/styles/app/modules/loading-indicator.sass
app/templates/signin.hbs

The template can now be used with signin and auth route.
Instead of a blank screen we'll have Mr T and a message that we're signing the user in.

update signin route and template

---

config/deployment/deploy-pull-request.sh
config/deployment/deploy-test-master.sh

Should stop truncation such as [this](https://travis-ci.org/travis-ci/travis-web/jobs/182232129).

Reduce deployment verbosity

---

config/ember-try.js

This removes 210 lines of log output!

Add flag to quiet Bower

---

app/controllers/builds.js
app/models/repo.js
mirage/config.js
mirage/serializers/repository.js
tests/acceptance/repo/build-list-routes-test.js
tests/pages/build-list.js

This is in progress. I’ve started with acceptance tests around the “Show more” button for the Build History tab. I expect the tests to fail.

Fix gap in build history

---

app/templates/insufficient-oauth-permissions.hbs

Hi all, 
saw this `<div>` containing an empty conditional, seemed safe to delete it.
Cheers!

Remove empty div with empty conditional

---

bower.json

This is just a bugfix release, but cannot hurt to upgrade.

Upgrade Ember to 2.10.2

---

app/styles/app/modules/buttons.sass
app/styles/app/modules/tooltips.sass

adjust icon positions

---

app/services/auth.js

This removes our current use of an iframe completely from web.

Only support redirect auth

---

app/components/remove-log-popup.js
app/components/repo-actions.js

Prompted by @beckjake in [HS <span>#</span>47894](https://secure.helpscout.net/conversation/309036213/47894/). Thank you!

Fixed typos: occured -> occurred

---

app/components/user-avatar.js
app/controllers/owner.js
app/models/commit.js
app/models/user.js
app/styles/app/layouts/owner.sass
app/styles/app/modules/avatar.sass
app/templates/components/branch-row.hbs
app/templates/components/build-header.hbs
app/templates/components/builds-item.hbs
app/templates/components/org-item.hbs
app/templates/components/user-avatar.hbs
app/templates/owner.hbs
app/templates/top.hbs
tests/unit/components/user-avatar-test.js
tests/unit/models/commit-test.js

Refactor avatar

---

app/styles/app/modules/avatar.sass

in case the avatar is transparent

set background color for avatars in topbar

---

app/utils/lines-selector.js

While we generally need to overhaul this code, this should quiet down our logging in the interim.

Fix sentry issue 187862253

---

bower.json

Getting warnings when viewing errors on Sentry, as well as bug fixes.

Bump Sentry version

---

app/styles/app/layouts/jobs.sass

fix an alignment bug on midsized laptops

adjust job list

---

app/controllers/account.js
app/templates/account.hbs

This PR changes a query to fetch hooks to not require order, which should speed things up a little bit. It also adds an error message when the hooks fail to load.

Improve hooks handling

---

app/components/build-header.js
app/models/job.js
app/templates/components/build-header.hbs
app/templates/components/repos-list-item.hbs
tests/integration/components/build-header-test.js
tests/unit/models/job-test.js

differentiate between create, queued and received

change logic for display of finished at

---

app/adapters/repo.js
app/adapters/v3.js
app/components/builds-item.js
app/controllers/settings.js
app/models/branch.js
app/routes/abstract-builds.js
app/routes/build.js
app/routes/job.js
app/routes/settings.js
app/serializers/branch.js
app/serializers/cron.js
app/serializers/v3.js
app/templates/settings.hbs
mirage/config.js
mirage/models/branch.js
mirage/models/build.js
mirage/models/cron.js
mirage/serializers/branch.js
mirage/serializers/cron.js
tests/acceptance/repo/settings-test.js
tests/unit/adapters/v3-test.js

Some of the changes in #970 are not strictly related to moving builds on V3. In order to clean up the PR a little bit, I ported some of the changes here, so we can merge them into master right away.

Backport Curtis' changes from v3 work

---

app/components/branch-row.js
app/components/status-images.js
app/routes/branches.js
app/routes/owner.js
app/routes/owner/repositories.js

I think #985 introduces bugs because the V3 header is sometimes only included when logged in.

Add V3 header even when not logged in

---

app/templates/settings.hbs

As requested in https://github.com/travis-pro/team-teal/issues/1768

Add a feedback link for the auto-cancel beta feature

---

app/controllers/build.js
app/templates/build.hbs
tests/acceptance/builds/current-tab-test.js
tests/pages/repo-tabs/current.js

add no jobs error

---

app/utils/keys-map.js

show Dart task matrix expansion key

---

package.json

I recall this causing problems in the past…

Fix Ember CLI version

---

app/styles/app/layouts/jobs.sass
app/utils/job-config-language.js

fix for https://github.com/travis-ci/travis-ci/issues/7537#issuecomment-293995052

Key expansion for Dart lang's task

---

app/templates/components/owner-repo-tile.hbs

Just randomly came across what either is a typo, or an interesting new type of attribute called `clas`. If it is in fact the latter, then I apologise for the clutter :)
Just wanted to take this opportunity to thank travis for the awesome service which I almost literally use every day.
Have a nice day!

Fix a typo in the markup

---

app/templates/components/job-infrastructure-notification.hbs

This also removes an extraneous space 😬

Correct Precise banner punctuation

---

app/services/external-links.js

Gravatar link in web UI should use lowercase email.

---

tests/acceptance/layouts/default-test.js
tests/pages/header/default.js

Necessary to safely refactor some template logic

Add test coverage for default header

---

tests/acceptance/layouts/pro-test.js
tests/pages/header/pro.js

Same as for default header, just want to be sure I do not break things.

Add test coverage for pro header

---

config/environment.js

This will hopefully cut down on a bunch of noise. See [the Sentry docs](https://docs.sentry.io/clients/javascript/config/#config-whitelist-urls) for more details.

Whitelist production URLs for Sentry

---

app/utils/pusher.js
config/environment.js

Allows logging pusher events to console as per https://pusher.com/docs/debugging#pusher_logging

pusher: add new pusher debug setting to environment

---

app/templates/layouts/landing-page.hbs

`signIn` and `signOut` were missing.

Add missing action that was not present in restored template

---

app/components/job-infrastructure-notification.js
app/templates/components/job-infrastructure-notification.hbs

Part of the communication plan in https://github.com/travis-pro/team-sapphire/issues/670

Added a banner in preparation for the Trusty update

---

app/components/caches-item.js
app/components/cron-job.js
app/components/env-var.js
app/controllers/caches.js
app/templates/components/env-var.hbs

I should have included these when adding ember-concurrency.

Remove pre-ember-concurrency leftovers

---

app/components/job-infrastructure-notification.js

@cotsog let me know this was incorrect.

Update Trusty update release date

---

app/components/job-infrastructure-notification.js

fixes travis-pro/team-teal#2065

add missing Date.parse() call to trusty date comparison

---

app/components/pagination-navigation.js
app/controllers/dashboard/repositories.js
app/routes/dashboard/repositories.js
app/serializers/v3.js
app/services/store.js
app/styles/app.scss
app/styles/app/modules/pagination.sass
app/templates/components/dashboard-row.hbs
app/templates/components/pagination-navigation.hbs
app/templates/dashboard/repositories.hbs
app/utils/paginated-collection-promise.js
app/utils/paginated-collection.js
mirage/config.js
mirage/serializers/v3.js
tests/acceptance/dashboard/repositories-test.js
tests/acceptance/repo/build-list-routes-test.js
tests/integration/components/pagination-navigation-test.js
tests/pages/dashboard.js
tests/unit/serializers/repo-test.js
tests/unit/utils/paginated-collection-test.js

Pagination protoype for dashboard

---

app/models/build.js
app/models/job.js
app/utils/safelisted-config-keys.js
package.json

This saves over 130kB from vendor.js!

Change to using individual lodash functions

---

app/components/job-infrastructure-notification.js
app/templates/components/job-infrastructure-notification.hbs

and update the note about when last updated and how to roll back.

Cast off the shroud of BETA from the Trusty

---

app/components/job-infrastructure-notification.js
app/templates/components/job-infrastructure-notification.hbs

and rename component function accordingly

Update latest trusty release date

---

app/services/random-logo.js

Remove duplicate logo from list

---

package.json

Thanks to @krisselden and @stefanpenner for fixing
https://github.com/emberjs/ember.js/pull/15502.

Update Ember to 2.14.1

---

app/templates/owner-loading.hbs
app/templates/profile-loading.hbs

This was just an oversight in the course of doing #1180.

Fix profile/owner loading screens

---

app/templates/components/build-layout.hbs

The feedback issue is locked now

Remove feedback link from build stages

---

config/environment.js
tests/acceptance/layouts/about-test.js
tests/acceptance/layouts/logo-test.js
tests/acceptance/layouts/plans-test.js

This should reduce false negatives in Percy.

Remove status link in test environment

---

app/models/repo.js

in favour of 'cronJobs' property

remove 'crons' property from repo model

---

app/styles/app/modules/switch.sass
tests/acceptance/feature-flags/user-sets-flags-test.js
tests/pages/features.js

I’m also going to add a screenshot and proper tests for feature flags.
I currently can’t run tests locally because all sorts of things that should be globally present like `signInUser` and `server` aren’t available 😢

Fix switch alignment

---

app/styles/app/modules/dashboard-row.sass
app/templates/components/dashboard-row.hbs

fadeout long default branch names

---

app/templates/components/trigger-custom-build.hbs

Fixes https://github.com/travis-ci/beta-features/issues/12#issuecomment-325272514
Thanks, @florenthemmi

Correct link to beta feedback issue

---

app/styles/app/layouts/owner.sass
app/styles/app/layouts/pull-requests.sass
app/styles/app/modules/row.sass
app/templates/components/branch-row.hbs
app/templates/components/builds-item.hbs
app/templates/components/owner-repo-tile.hbs

All the icons

---

tests/acceptance/job/delete-log-test.js
tests/pages/job.js

Adds test for behavior fixed in https://github.com/travis-ci/travis-web/pull/1270

Add test coverage for log deletion behavior

---

app/styles/app/layouts/owner.sass
app/styles/app/layouts/repo.sass

fix opacity on GH icon

---

app/styles/app/base.sass
app/styles/app/data.scss
app/styles/app/layouts/jobs.sass
app/styles/app/layouts/log.sass
app/styles/app/layouts/pull-requests.sass
app/styles/app/layouts/requests.sass
app/styles/app/layouts/sidebar.sass
app/styles/app/mixins.sass
app/styles/app/modules/build-header.sass
app/styles/app/modules/build-tile.sass
app/styles/app/modules/row.sass
app/styles/app/modules/search.sass
app/styles/app/modules/status-icon.sass
app/templates/components/branch-row.hbs
app/templates/components/repos-list-item.hbs
app/templates/components/requests-item.hbs
app/templates/components/status-icon.hbs
public/images/stroke-icons/icon-running.svg

Center loading icon in sidebar

---

app/templates/components/job-infrastructure-notification.hbs

and remove the Trusty banner as the time has come

Update the Precise EOL banner

---

app/utils/pusher.js

Although we don't need bulk ajax for subscribing to multiple channels
anymore, it's just easier to keep it for now and use for private
channels. Also, since we always use private user channel on .org, we
should also register it on .org.

Always use bulk ajax auth for pusher

---

app/components/trigger-custom-build.js

Tested on:  https://ar-fix-request-format.test-deployments.travis-ci.org/anarosas/test-gce/jobs/271823188/config

Change requestConfig to config

---

tests/acceptance/builds/build-stages-test.js
tests/acceptance/builds/invalid-build-test.js
tests/acceptance/job/build-matrix-test.js
tests/acceptance/job/invalid-log-test.js

This was obscuring the log output with errors about multiple Pretender instances.

Fix test warnings

---

.travis.yml

Simplify use of chrome in .travis.yml

---

app/templates/components/landing-default-page.hbs

Update the number of open source software projects and users who use Travis-CI.

update oss projects and user numbers

---

app/routes/dashboard/repositories.js
app/utils/filtered-array-manager.js
package.json
tests/acceptance/dashboard/repositories-test.js
tests/acceptance/repo/settings-test.js

I’ve skipped some tests with a [backtracking rerender error](https://github.com/emberjs/ember.js/issues/13948) but apart from that everything seems to be working now, so I’ll return to look at what’s going on there.

Update to Ember Data 2.15

---

.travis.yml
app/components/log-content.js
app/services/ajax.js
app/utils/pusher.js
package.json
tests/acceptance/job/basic-layout-test.js

This includes some ESLint fixes, I don’t know why they’re necessary though!

Update to Node 8.5.0

---

app/routes/application.js
app/services/feature-flags.js
tests/acceptance/dashboard/repositories-test.js

Hide dashboard upon signout

---

ISSUE_TEMPLATE.md

Add issue template from `beta-features` repo

---

app/styles/app/layout.sass
app/styles/app/layouts/footer.sass
app/styles/app/layouts/jobs.sass
app/styles/app/mixins.sass
app/templates/dashboard/repositories.hbs
app/templates/getting-started.hbs
app/templates/index.hbs
app/templates/layouts/center.hbs
app/templates/layouts/profile.hbs
app/templates/repo.hbs
app/templates/search.hbs

I also added different hover styles for overflowing `</> lang` and `📦 env` values

Addressing the job matrix alignment issues

---

.travis.yml

It’s my hope that this will address the team page being randomised
in some snapshots.

Add branch to explicitly turn off Percy

---

app/styles/app/layouts/log.sass

Thanks to @Turbo87 for letting us know about this here:
https://github.com/travis-ci/travis-web/pull/1377#issuecomment-338700704

Restore log whitespace style

---

app/templates/components/limit-concurrent-builds.hbs

Jobs / builds wording updates:

update wording from builds to jobs and also link to docs

---

app/routes/team.js

This PR removes Amanda from our team page.

Remove Amanda from team page 😞

---

app/styles/app/layouts/profile.sass
app/styles/app/modules/notice.sass

I’d prefer to get rid of floats altogether, but that’s for
another century.

Fix background colour bleeding

---

package-lock.json
package.json

I’m _really_ trying to get Greenkeeper back but it’s slow and confusing.

Update even more dependencies

---

app/styles/app/layouts/log.sass

See the comments in #1426 for more; thanks to @rsimha-amp for
letting us know.

Remove wrapped log line alignment fix

---

app/styles/app/layouts/log.sass

This is an attempt to address #1426 without breaking other things. It doesn’t work yet.

Change log wrapping alignment

---

.eslintrc.js
app/.eslintrc.js
app/models/job.js
app/serializers/job.js
app/services/job-config-fetcher.js
package-lock.json
tests/.eslintrc.js
tests/acceptance/home/with-repositories-test.js
tests/unit/models/job-test.js

This PR uses config from V3 instead of querying V2.

Use config from V3

---

.travis.yml

Add chmod for Chrome

---

.travis.yml

While we still do require sudo, a Scheduler change should
take care of this automatically. Testing…

Revert Travis configuration for sudo

---

tests/acceptance/job/basic-layout-test.js
tests/pages/job.js

- Adds acceptance test to cover the fold duration
[2476](https://github.com/travis-pro/team-teal/issues/2476)
`tests/acceptance/job/basic-layout-test.js`

Add acceptance test to cover fold duration element

---

.travis.yml

ugh
This is because [this](https://github.com/travis-ci/travis-ci/issues/8836) is ongoing and my Scheduler change had to be reverted.

Return to using GCE

---

app/templates/components/branch-row.hbs
app/templates/components/build-header.hbs
app/templates/components/builds-item.hbs
app/templates/components/repos-list-item.hbs
app/templates/components/running-jobs.hbs

Fixes https://github.com/travis-pro/team-teal/issues/2485

Fix date&time formatting on title attributes

---

app/templates/components/top-bar.hbs

This is a first draft PR to demonstrate the change related to issue [#2458](https://github.com/travis-pro/team-teal/issues/2458)

Change "Accounts" on the top navigation to "Profile"

---

package-lock.json
package.json

This is a Greenkeeper thing yet somehow I am creating a PR for it?

Update Ember Concurrency

---

app/services/auth.js
app/utils/url.js
config/environment.js
package-lock.json
package.json

Add URL polyfill

---

app/router.js
app/routes/signin.js
mirage/factories/user.js
tests/acceptance/sign-in-test.js
tests/unit/routes/signin-test.js

I believe this should address the issue, though it would be good to get feedback from @backspace or @drogus around what the concerns were with https://github.com/travis-ci/travis-web/pull/1395 to make sure this is the expected behavior.

[Reliability]: Fix education sign in

---

app/components/top-bar.js
app/templates/components/top-bar.hbs
bower.json
ember-cli-build.js
package-lock.json
package.json

I’m still looking to replace the Bower-imported Waypoints
jQuery plugin with something. I’ve figured out why
ember-in-viewport didn’t work last time I tried:
didInsertElement was missing the super call! 😱
This still isn’t working as expected though, despite all
my fiddling attempts with the settings. It shows the
top-bar having exited the viewport immediately upon scrolling,
rather than after it’s completely disappeared. I’m pushing
just to save this for later revisiting.
The tests will fail.

Add experiment with ember-in-viewport

---

mirage/models/branch.js
mirage/models/build.js
mirage/models/env-var.js
mirage/models/repository.js
mirage/models/settings.js
mirage/models/stage.js
mirage/serializers/v2.js
package-lock.json
package.json
tests/acceptance/builds/pull-requests-test.js

We've avoided upgrading for too long because of the perceived amount of work to change our relationship definitions. I'm going to try and fix this incrementally, these first few commits being the first chunk.

Bump ember-cli-mirage to 0.4.x series

---

app/components/build-messages-list.js

This will make more sense with another PR.

Change build messages to use ajax service

---

app/styles/app/layouts/sidebar.scss

Center the `Add New Repositories` button 
` app/styles/app/layouts/sidebar.scss`

Center add repo button

---

app/templates/requests.hbs

Remove lint link

---

app/styles/app/layouts/top.scss
app/styles/app/modules/navigation.scss

This isn’t my favourite but it at least makes them seem non-linky.

Change profile links to be inert when active

---

app/components/branch-row.js
app/routes/branches.js
app/routes/owner.js

attempt to fix api token on branches page

---

app/routes/owner/repositories.js

patch another call to this.auth.token

---

config/deployment/deploy-pull-request.sh

This will make Greenkeeper PRs have proper deployment links.

Add PR deployment handling for slash in branch

---

app/templates/requests.hbs

Backports #1571 for Enterprise 2.2
/cc @acnagy @backspace

[Enterprise] Backport: Add placeholder for empty requests (#1571)

---

app/components/branch-row.js
app/components/job-infrastructure-notification.js
app/components/landing-default-page.js
app/components/landing-pro-page.js
app/components/org-item.js
app/components/owner-not-found.js
app/components/repo-not-found.js
app/controllers/getting-started.js
app/controllers/plans.js
app/controllers/repo.js
app/controllers/signin.js
app/initializers/auth.js
app/routes/application.js
app/routes/basic.js
app/routes/branches.js
app/routes/builds.js
app/routes/owner/repositories.js
app/routes/pull-requests.js
app/routes/repo.js
app/routes/settings.js
app/templates/repo-error.hbs

Similar work to #1569, this time for the auth service.

Remove auth initializer

---

tests/acceptance/dashboard/repositories-test.js
tests/acceptance/home/broadcasts-test.js
tests/acceptance/home/sidebar-tabs-test.js
tests/acceptance/home/with-repositories-test.js
tests/acceptance/owner/repos-test.js
tests/acceptance/profile/basic-layout-test.js
tests/acceptance/profile/filtering-test.js
tests/acceptance/profile/not-found-test.js
tests/acceptance/profile/update-repositories-test.js
tests/acceptance/profile/view-token-test.js
tests/acceptance/repo/branches-test.js
tests/acceptance/repo/build-list-routes-test.js
tests/acceptance/repo/caches-test.js
tests/acceptance/repo/settings-test.js
tests/acceptance/repo/show-test.js
tests/integration/v2-serializer-test.js
tests/integration/v3-serializer-test.js

“When you expose a problem you pose a problem.” — [Sara Ahmed](https://feministkilljoys.com/2014/02/17/the-problem-of-perception/)

Remove political references

---

app/components/enterprise-banner.js
app/templates/components/enterprise-banner.hbs

Addresses this issue: https://github.com/travis-pro/travis-enterprise/issues/257

Make 5 User message removable.

---

app/components/enterprise-banner.js
app/templates/components/enterprise-banner.hbs

Backports #1594 for `enterprise-2.2`

[Backport] Make 5 User message removable. (#1594)

---

tests/integration/components/add-ssh-key-test.js
tests/integration/components/status-images-test.js

It’s unclear to me why these started failing, but these changes fix them.

Fix spurious failures

---

app/controllers/accounts.js
app/instance-initializers/enterprise-environment.js
app/instance-initializers/pro-environment.js
app/templates/accounts.hbs
config/environment.js
package-lock.json
tests/acceptance/config/oss-feature-flags-test.js
tests/acceptance/enterprise/beta-features-disabled-test.js
tests/unit/instance-initializers/enterprise-environment-test.js
tests/unit/instance-initializers/pro-environment-test.js

Backports #1607 for `enterprise-2.2`

[Enterprise Backport] Don't show Beta Features page in Enterprise (#1607)

---

app/routes/account/repositories.js

I should have removed this when V3ifying this route.

Remove unneeded ESLint directive

---

mirage/config.js

This will let me change branches more smoothly!

Add control of Mirage logging via query param

---

app/components/repository-visibility-icon.js
app/styles/app/layouts/repo.scss
app/templates/components/repository-layout.hbs
app/templates/components/repository-visibility-icon.hbs
public/images/stroke-icons/icon-lock.svg
public/images/stroke-icons/icon-os.svg

Add repository visibility icon

---

app/templates/plans.hbs

Now that we have a sales email address these conversations should be sent to their inbox for starting conversations with our customers.

Update contact button to sales email

---

app/services/job-config-fetcher.js

I don’t really understand this…??

Add already-fetched config wrapper

---

app/models/user.js
app/services/ajax.js
mirage/factories/user.js
tests/acceptance/profile/sync-test.js
tests/pages/profile.js

There’s some mystery to me here regarding the `user:synced` event but it seems to work…?!

Update sync to happen via V3

---

app/components/remove-log-popup.js
app/components/status-images.js
app/components/trigger-custom-build.js
app/templates/components/trigger-custom-build.hbs

This isn’t [as complete as I’d like](https://github.com/yapplabs/ember-modal-dialog/issues/236) but maybe I can contribute to improving it upstream.

Add keyboard features for modals

---

config/environment.js

We’re going over our limit and can’t change the plan for now.

Remove tablet breakpoint for Percy

---

waiter/lib/travis/web/app.rb

Remove CSP code from waiter

---

app/styles/app/modules/codedisplay.scss

[2714](https://github.com/travis-pro/team-teal/issues/2714)
- Update font in the `view config` section
`app/styles/app/modules/codedisplay.scss`

Update font for view config

---

app/components/repo-show-tools.js
app/styles/app/layouts/repo.scss
app/styles/app/modules/dropdown.scss
app/templates/components/repository-layout.hbs

This will allow links to be opened in new tabs but I’m also looking into keyboard accessibility.

Improve repository tools popup

---

config/environment.js

I mistakenly committed this in #1506.

Restore Sentry logging

---

app/styles/app/modules/loading-indicator.scss
app/templates/components/repository-status-toggle.hbs

[2725](https://github.com/travis-pro/team-teal/issues/2725)
- Fix repository toggle from jumping when loading
`loading-indicator.scss`

Fix repository toggle jump when loading

---

app/models/subscription.js
tests/acceptance/profile/billing-test.js

Update resubscribe link to point to the same url as the edit subscription

Change resubscription link

---

app/styles/app/layouts/jobs.scss

- Change width of `job env` section so it will not push the restart button off the page
`app/styles/app/layouts/jobs.scss`

Change width on large screen

---

app/adapters/cron.js
app/services/accounts.js
app/services/store.js
package-lock.json
package.json
tests/acceptance/builds/pull-requests-test.js

aka tragic nightmare
I don’t know if I’ll be able to address most of them, I’ve been having Significant Problems.

Update Ember Data and filter addon

---

app/adapters/request.js
app/components/requests-item.js
app/initializers/configure-inflector.js
app/models/request.js
app/serializers/request.js
ember-cli-build.js
package-lock.json
package.json
tests/acceptance/repo/requests-test.js
tests/integration/components/requests-item-test.js

This changes the request-build relationship to a belongsTo to address this
Ember Data snapshot situation:
https://github.com/emberjs/data/issues/5565
Thanks to @runspired for the guidance!

Update Ember etc to 3.3

---

app/styles/app/layouts/profile.scss

Fix error message at repositories list

---

package-lock.json
package.json

This should fix some deprecation warnings.

Update ember-tooltips to 2.10.0

---

tests/unit/utils/abstract-method-test.js

It was failing for me locally. Not sure how it worked in CI.

Fix abstract method test

---

app/components/paper-block.js
app/styles/app.scss
app/styles/app/modules/paper-block.scss
app/templates/components/paper-block.hbs
tests/helpers/selectors.js
tests/integration/components/paper-block-test.js

Extacting the component from https://github.com/travis-ci/travis-web/pull/1760

Add paper-block component

---

app/components/loading-screen.js
app/styles/app.scss
app/styles/app/modules/loading-screen.scss

Extracting changes from https://github.com/travis-ci/travis-web/pull/1760

Refactor loading-screen to handle some states

---

app/templates/components/add-env-var.hbs

I somehow missed this in #1766 😞

Fix action name deprecation

---

app/components/repository-visibility-icon.js
app/templates/components/repository-visibility-icon.hbs

I thought I didn’t have this for some reason… but now it seems
to work fine???

Add tooltip for repository visibility icon

---

app/styles/app/modules/build-header.scss

Issue: https://github.com/travis-pro/team-teal/issues/2792

Trim commit message for narrow screens

---

app/styles/app/layouts/jobs.scss

Fixes an issue similar to the one addressed in https://github.com/travis-ci/travis-web/pull/1778

Address another stage time alignment issue

---

app/styles/app/modules/navigation.scss
app/templates/components/header-links.hbs

- Allows keyboard tabbing functionality for the profile menu dropdown. 
[2801](https://github.com/travis-pro/team-teal/issues/2801)
`app/styles/app/modules/navigation.scss`

Add keyboard navigation for profile menu

---

app/controllers/repo.js
app/templates/repo.hbs

Issue: https://github.com/travis-pro/team-teal/issues/2807

Fix layout for logging in state when new dashboard is enabled

---

package-lock.json
package.json

This fixes our inability to log in in development:
https://github.com/ember-cli/ember-cli/issues/8037

Update to Ember CLI 3.4.2

---

app/templates/components/header-links.hbs

Remove unneeded menu separator

---

app/templates/components/limit-concurrent-builds.hbs

Fix anchor

---

app/controllers/account/settings.js
app/routes/account/settings.js
app/templates/account/settings.hbs
package-lock.json

The issue: Settings page fetched only first page of repositories, thus displaying only partial results in unsubscribed list. More context here: https://travisci.slack.com/archives/CC97UDR8R/p1537265808000100

Make settings page fetch all repositories for unsubscribe

---

app/utils/log.js
tests/acceptance/job/basic-layout-test.js

This reverts commit eddfa3f, in light of travis-ci/travis-ci#10133.
Thanks to @edmorley for letting us know about it.

Revert "Fix log blanks (#1783)"

---

app/models/build.js
app/models/job.js
app/models/stage.js

Reverts travis-ci/travis-web#1718 per @joshk request.

Revert "Show log content when received/booting"

---

app/models/repo.js

Issue: https://travisci.slack.com/archives/C1T1E0F4L/p1537870032000100
This is a temporary solution until the API is fixed properly.

Reduce builds request amount

---

package-lock.json
package.json

This reverts #1819 as it’s broken the cron tests against Ember
and Ember Data betas and I can’t figure it out at the moment.

Revert ember-try version change

---

app/styles/app/layout.scss
app/styles/app/layouts/log.scss
app/utils/tailing.js
app/utils/to-top.js

Smooth scroll log control

---

app/routes/application.js
app/services/auth.js

Because of the incorrect current user loading, accont page for GitHub apps always showed "enable github apps" stub.

As com account repos

---

app/styles/app/modules/build-header.scss
app/templates/components/branch-row.hbs
app/templates/components/build-header.hbs
app/templates/components/builds-item.hbs
app/templates/components/dashboard-row.hbs
app/templates/components/owner-repo-tile.hbs
tests/integration/components/build-header-test.js
tests/pages/build.js

- Change commit SHA font to monospace app wide
[2814](https://github.com/travis-pro/team-teal/issues/2814)

Monospace commit sha throughout Travis

---

app/components/build-header.js
app/styles/app/modules/build-header.scss
app/templates/components/build-header.hbs

- Removes fading element for commit messages 72 characters or less
[2843](https://github.com/travis-pro/team-teal/issues/2843)

Update commit description fading logic and styling

---

.travis.yml

Issue: cron jobs for Ember beta releases fail the entire build on master branch.
Example: https://travis-ci.org/travis-ci/travis-web/builds/444616978

Fix cron failures

---

app/adapters/job.js
app/components/build-layout.js
app/models/job.js
app/services/job-config-fetcher.js
app/utils/promise-object.js

Improvement of https://github.com/travis-ci/travis-web/pull/1839

Improve job config fetching logic

---

app/routes/dashboard.js
app/routes/dashboard/repositories.js
app/templates/components/header-links.hbs
app/templates/dashboard.hbs
tests/acceptance/dashboard/repositories-test.js
tests/acceptance/layouts/default-test.js
tests/acceptance/layouts/pro-test.js

- Add `Dashboard` link to top bar
- Change `Recent builds` to `My builds`

Add dashboard link to top bar and update text to my builds

---

app/components/tooltip-on-element.js
app/styles/app/base.scss
app/styles/app/modules/dashboard-row.scss
app/templates/components/my-build.hbs

Issue: https://github.com/travis-pro/team-teal/issues/2774

As page horizontal scrolling

---

app/styles/app/layouts/features.scss

This is just a small style fix to make this feature looks right :)

A pride flag linear gradient fix

---

tests/acceptance/builds/current-tab-test.js
tests/acceptance/job/log-error-test.js
tests/acceptance/profile/basic-layout-test.js
tests/acceptance/profile/billing-test.js
tests/acceptance/profile/view-token-test.js

This should help us stay under the Percy limits.

Remove redundant snapshots

---

app/routes/owner/repositories.js

Issue: https://github.com/travis-pro/team-teal/issues/2824

Inconsistent repos list

---

app/components/header-links.js
app/routes/application.js
app/services/help-scout.js

- Create an ember service for Help Scout
- Create a fallback to a mailto link if the Help Scout link fails
[2868](https://github.com/travis-pro/team-teal/issues/2868)

Check around helpscout link availability

---

package-lock.json
package.json

We’ve been having deployment problems that mention this addon
specifically, so I’m seeing if this will help.

Revert update of ember-cli-sentry

---

mirage/api-spec.js
mirage/config.js

It would be nice to automate this process in the future, but it currently requires a bit more finesse due to "hidden" resources within API.

Update api spec to use .com

---

app/utils/log.js
tests/acceptance/job/basic-layout-test.js

Another attempt on https://github.com/travis-pro/team-teal/issues/2782
Works as expected for all previous cases:
- https://as-log-fixes.test-deployments.travis-ci.org/Ortus-Solutions/JSONPrettyPrint/jobs/417099159
- https://as-log-fixes.test-deployments.travis-ci.org/mozilla/treeherder/jobs/430084979
- https://as-log-fixes.test-deployments.travis-ci.org/servo/servo/jobs/451986012

Fix blank lines

---

package-lock.json
package.json
tests/integration/components/status-images-test.js

Thank you @backspace for opening this issue: https://github.com/thefrontside/emberx-select/issues/232
Here's the finishing touches :)

Update x-select to `v4.0.0-beta.2`

---

app/components/not-active.js
app/components/repo-show-tools.js
app/components/repository-layout.js
app/components/repository-status-toggle.js
app/controllers/settings.js
app/models/repo.js
app/services/external-links.js
app/styles/app/modules/buttons.scss
app/templates/components/account-repositories.hbs
app/templates/components/not-active.hbs
app/templates/components/repo-show-tools.hbs
app/templates/components/repository-layout.hbs
app/templates/components/repository-status-toggle.hbs
app/templates/settings.hbs
mirage/factories/repository.js
tests/acceptance/builds/current-tab-test.js
tests/acceptance/profile/migration-test.js
tests/acceptance/profile/update-repositories-test.js
tests/acceptance/repo/not-active-test.js
tests/acceptance/repo/settings-test.js
tests/acceptance/repo/trigger-build-test.js
tests/acceptance/repo/view-migrated-test.js
tests/pages/profile.js
tests/pages/trigger-build.js

This will be a long-running branch to encapsulate all changes across org/com relating to migrations.
See https://github.com/travis-ci/product/issues/110 for more details.

UI updates to show migration status and build history

---

config/deprecation-workflow.js

I should have done this in #1910.

Remove decorators deprecation-silencing

---

app/components/github-apps-repository.js
app/models/repo.js
app/templates/components/github-apps-repository.hbs
tests/acceptance/profile/migration-test.js

Also, ensure that the loading indicator is shown for both `queued` and `migrating` states.

Make queued the default migration status

---

app/services/accounts.js
app/templates/components/billing-subscription.hbs
app/templates/components/payment-details.hbs
mirage/factories/plan.js
mirage/factories/subscription.js
tests/acceptance/profile/basic-layout-test.js
tests/acceptance/profile/billing-test.js

This adds logging and I’ll also fix the `NaN` cost 🙃

Add handling for null subscription plans

---

app/models/build.js
app/models/job.js
app/templates/components/builds-item.hbs
tests/acceptance/builds/pull-requests-test.js
tests/acceptance/repo/build-list-routes-test.js
tests/pages/build-list.js

This only addresses one but there was no test for this previously
and I broke it in #1915, so I’m going to continue on this tomorrow
to add assertions for other `title` attributes I can find.

Fix date-formatted titles

---

tests/acceptance/repo/settings-test.js

I have need of the new style elsewhere. One test is still failing, though… 🤔

Update settings acceptance test to new style

---

app/styles/app/modules/build-header.scss
app/templates/components/log-content.hbs

- Update font color on number text to meet WCAG 2.0 standards for accessibility
- Update position on text so "jumping" doesn't occur when state goes from loading to loaded

Update stage text to be easier to read

---

app/routes/application.js

Did this break with Ember 3.7? 🤔
I’d prefer this to be tested but I don’t know how that would work…

Update generation of redirect URL

---

app/models/repo.js

This isn’t being accessed anywhere that I can see.

Remove unused stats property

---

app/components/forms/form-checkbox.js
app/components/forms/form-field.js
app/components/forms/form-input.js
app/styles/app/modules/travis-form.scss
app/templates/components/forms/form-checkbox.hbs
app/templates/components/forms/form-field.hbs
public/images/svg/checkbox-checked.svg
public/images/svg/checkbox-unchecked.svg

This is a part of giant https://github.com/travis-ci/travis-web/pull/1949/ that is quite independent, so I've extracted it to a separate PR. Here's the link to design in scope of [MOSS] Migrate tab: https://github.com/travis-pro/team-teal/issues/2915#issuecomment-465244581

Add form-checkbox to travis-form

---

app/utils/bind-generator.js
app/utils/dynamic-query.js

This is extracted from https://github.com/travis-ci/travis-web/pull/1949/ as pretty independent thing, although, it's using only in that PR. This one contains only implementation.
The documentation, intents and examples are in the code.
Please let me know if you have any questions about it.

Add dynamic query utility

---

app/components/pagination-navigation.js
app/styles/app/modules/pagination.scss
app/templates/components/pagination-navigation.hbs

A small refactoring of pagination component, mostly for simplicity and stability. Also extracted from https://github.com/travis-ci/travis-web/pull/1949/
It also fixes the issue with pagination on narrow screens (it wraps and looks broken)

Refactor pagination component

---

package-lock.json
package.json

I'm going to be splitting up this branch for easier review https://github.com/travis-ci/travis-web/pull/1966
This PR handles the install of new dependency ember-c3

Install ember-c3 addon

---

app/styles/app/modules/loading-indicator.scss

Update loading container overflow css rule

---

app/components/insights-date-display.js
app/templates/components/insights-date-display.hbs
tests/integration/components/insights-date-display-test.js

Adds an insights component for displaying a date range.

Add insights date display component

---

app/components/insights-tabs.js
app/services/insights.js
app/templates/components/insights-tabs.hbs
tests/integration/components/insights-tabs-test.js

Adds an insights tabs component for selecting intervals.

Add Insights tabs component

---

app/styles/app/base.scss
app/styles/app/layouts/repo.scss
app/styles/app/modules/loading-indicator.scss
app/templates/components/repository-layout.hbs
tests/pages/sidebar.js

Fix for issue 2841
https://github.com/travis-pro/team-teal/issues/2841

Responsive repository header

---

app/components/build-status-chart.js
app/templates/components/build-status-chart.hbs
tests/integration/components/build-status-chart-test.js

This adds a component for the large build status chart

Add insights build status chart component

---

app/components/visibility-setting-list.js
app/styles/app/modules/visibility-setting-list.scss
app/templates/components/visibility-setting-list.hbs
tests/integration/components/visibility-setting-list-test.js

Split from https://github.com/travis-ci/travis-web/pull/1953
Adds a component for selecting insights visibility settings.

Add insights visibility settings list component

---

app/components/remove-log-popup.js
app/styles/app/modules/popup.scss
app/templates/components/github-apps-repository.hbs
app/templates/components/log-content.hbs
app/templates/components/repository-layout.hbs
app/templates/components/visibility-setting-list.hbs
app/templates/settings.hbs
app/transitions.js
package-lock.json
package.json

Extraction from https://github.com/travis-ci/travis-web/pull/1995

Add animation to modal dialogs

---

app/components/forms/form-field.js
app/components/forms/form-select-multiple.js
app/components/forms/form-select.js
app/mixins/components/form-select.js
app/styles/app/modules/travis-form.scss
app/styles/app/power-select-vars.scss
app/templates/components/forms/form-field.hbs

Another extraction from https://github.com/travis-ci/travis-web/pull/1995
It can be seen in action here: https://as-moss-beta-ui.test-deployments.travis-ci.org/account/repositories after clicking on "Sign me up for beta".
Here's the screenshot:

Add multiple select component to travis-form

---

app/styles/app/modules/forms.scss

Issue: https://github.com/travis-ci/bugs-questions-comments-ideas/issues/119

Increase form label text size

---

app/templates/components/github-apps-repository.hbs
app/templates/components/log-content.hbs
app/templates/components/repository-layout.hbs
app/templates/components/visibility-setting-list.hbs
app/templates/settings.hbs
app/transitions.js
config/environment.js

This change addresses the issue with Percy showing random diffs caused by modal dialog animation.

Disable liquid fire animations for testing environment

---

app/templates/components/build-count.hbs
tests/acceptance/owner/insights-test.js
tests/integration/components/build-count-test.js

Addresses this issue: https://github.com/travis-ci/travis-insights/issues/74

Update the title on the build-count component

---

app/components/insights-glance.js
app/styles/app/layouts/insights.scss
app/templates/components/queue-times.hbs

Addresses https://github.com/travis-ci/travis-insights/issues/73

Reverse delta colors on queue-times component

---

app/controllers/owner/repositories.js
app/templates/owner/repositories.hbs

This PR is intended to address this issue: https://github.com/travis-ci/travis-insights/issues/75

Fix an issue where public builds always show on initial load.

---

app/adapters/request.js
app/components/annotated-yaml.js
app/components/raw-config.js
app/models/request.js
app/services/external-links.js
app/styles/app/base.scss
app/styles/app/modules/yaml.scss
app/templates/components/annotated-yaml.hbs
app/templates/components/raw-config.hbs
app/utils/format-config.js
mirage/api-spec.js
tests/acceptance/config/yaml-test.js
tests/pages/build.js

Use raw configs instead of yaml config endpoint

---

app/controllers/settings.js
app/templates/settings.hbs
tests/acceptance/repo/settings-test.js
tests/pages/settings.js

https://github.com/orgs/travis-pro/projects/31

Add allow config imports for private repositories

---

app/templates/components/owner/migrate.hbs
app/templates/components/repository-migration-modal.hbs
tests/integration/components/repository-migration-modal-test.js

* Updated migrate tab copy
* Updated tooltips text
* Updated migration modal text and buttons position

Update UX copy - migrate tab

---

app/components/repository-status-toggle.js
app/templates/components/repository-status-toggle.hbs
app/utils/api-errors.js
tests/integration/components/repository-status-toggle-test.js
tests/unit/utils/api-errors-test.js

Backport https://github.com/travis-ci/travis-web/pull/2029 into Enterprise 2.2

Backport #2029 Repo activation 409 handle 

---

app/components/repository-status-toggle.js
app/templates/components/repository-status-toggle.hbs
app/utils/api-errors.js
tests/integration/components/repository-status-toggle-test.js
tests/unit/utils/api-errors-test.js

Backport #2029 into Enterprise 2.2

Enterprise backport 2029

---

app/components/repository-status-toggle.js
app/templates/components/repository-status-toggle.hbs
tests/integration/components/repository-status-toggle-test.js

Correcting changes made to the previous backport so that functionality works as we want it to.

Jaroslaw enterprise backport 2029

---

app/components/raw-config.js
app/templates/components/raw-config.hbs

Changes the config view to pretty print JSON payloads for requests triggered via API

pretty print raw config json

---

app/templates/components/log-content.hbs
app/templates/components/repository-layout.hbs
app/templates/components/visibility-setting-list.hbs
app/templates/settings.hbs
app/transitions.js
config/environment.js

This is recommended in the project [README](https://github.com/ember-animation/liquid-fire#testing) and can't help but speed up the test suite.

Reduce liquid fire duration in tests

---

app/templates/settings.hbs

Fixes typo and improves readability.

Minor copyedit to special-chars instructions

---

app/templates/components/missing-notice.hbs
app/templates/components/not-active.hbs
app/templates/repo/active-on-org.hbs

After merging [this PR](https://github.com/travis-ci/travis-web/pull/2033) Percy started to show random diffs on SVG animations. This PR should fix that issue.

Fix percy diffs on SVG animations

---

app/controllers/repo/index.js
app/mixins/route/owner/migrate.js
app/templates/components/owner/migrate.hbs
app/templates/repo/active-on-org.hbs

Some improvements for the issues reported by support [here](https://travisci.slack.com/archives/C6CMPT8R0/p1562245599021900)

As moss fix feedback

---

app/templates/components/landing-pro-page.hbs

Asana URL: https://app.asana.com/0/1127370853218484/1129993563559226

fix signup home page inner content redirection issue

---

app/components/status-images.js
app/components/trigger-custom-build.js
app/mixins/branch-searching.js
app/services/status-images.js
app/styles/app/modules/travis-form.scss
app/templates/components/forms/form-field.hbs
app/templates/components/status-images.hbs
app/templates/components/trigger-custom-build.hbs
package-lock.json
package.json
tests/acceptance/repo/trigger-build-test.js
tests/integration/components/status-images-test.js
tests/integration/components/trigger-custom-build-test.js
tests/pages/trigger-build.js

Extracted from https://github.com/travis-ci/travis-web/pull/2075 as it's going to be huge. 
These changes replace `x-select` component with `travis-form` everywhere in the app and remove `x-select` add-on.

As remove x select

---

app/styles/app/layouts/log.scss
app/utils/log-folder.js

Trying to fix https://github.com/travis-ci/travis-web/pull/2102

Fix line folding

---

config/environment.js
config/plans.js

Allows for configuration of available plans.

Create plans config

---

app/controllers/plans.js
app/templates/components/ui-kit/text.hbs
app/templates/plans.hbs
config/environment.js

Part of https://github.com/travis-ci/travis-web/pull/2068
This is in response to feedback about the content of the FAQ section

[Plans] faq content update

---

app/styles/app/pages/help.scss

Bug report in Slack https://travisci.slack.com/archives/C1FAZPJNP/p1568122255000800

Fix help page image width

---

app/components/ui-kit/box.js
app/styles/tailwind/components.scss
app/templates/plans.hbs

The main purpose of this PR is to have a PR deployment utilizing the staging environment, API etc. so that form submissions go to the Dev space in Close.io. This avoids putting a bunch of test junk in the Production space. I considered a few other methods, but this seemed the easiest.
The main PR for this update, where code review etc. can be done is still https://github.com/travis-ci/travis-web/pull/2118. I'll be updating code there and merging it into here as needed

[Plans] Contact form STAGING

---

app/adapters/lead.js
app/components/sales-contact-form.js
app/models/lead.js
app/serializers/lead.js
app/templates/components/sales-contact-form.hbs
app/templates/plans.hbs

Another staging test deployment PR. The main update here is to utilize ember-data for leads.

Update to use ember data

---

app/components/billing/account.js
app/components/billing/authorization.js
app/models/subscription.js
app/templates/components/billing-manual.hbs
app/templates/components/billing/account.hbs

This PR resolves this: https://github.com/travis-pro/billing-v2/issues/287

Fix subscription tab flickering

---

app/components/dialogs/cancel-subscription-modal.js
app/styles/app/modules/popup.scss
app/templates/components/dialogs/cancel-subscription-modal.hbs
tests/acceptance/profile/billing-test.js
tests/pages/profile.js

Enable user select a cancellation reason before cancelling

Make selecting a cancellation reason compulsory

---

app/components/build-message.js

New message type:
Before: https://travis-ci.org/svenfuchs/test/jobs/590057267/config
After: https://sf-config-msg-condition.test-deployments.travis-ci.org/svenfuchs/test/jobs/590057267/config

add new build config message type: condition

---

app/templates/components/owner/migrate.hbs
package-lock.json
package.json

For https://travisci.assembla.com/spaces/Web/tickets/208/details

Update ember to 3.12

---

app/templates/components/landing-pro-page.hbs

Objective:
- Redirect to proper page from middle signup button like top right corner.
ref: https://travisci.assembla.com/spaces/Enterprise/tickets/realtime_list?ticket=50

resolved conflicts for svg-jar

---

app/templates/components/forms/form-switch.hbs

This change fixes toggle control on the Add Env Var form in repository settings.

Fix toggle switch appearance

---

app/components/sales-contact-form.js
app/controllers/plans/index.js
app/models/lead.js
app/templates/plans/index.hbs
tests/acceptance/plans-test.js

Renaming at the request of the marketing team. Related API PR is https://github.com/travis-ci/travis-api/pull/976

[Plans] Rename lead_source to referral_source

---

app/components/build-message.js

https://sf-msg-overwrite.test-deployments.travis-ci.org/svenfuchs/test/jobs/597704851/config

add overwrite config message

---

app/components/landing-pro-page.js
app/controllers/plans/index.js
app/routes/first-sync.js
app/templates/components/landing-pro-page.hbs
app/templates/plans/index.hbs

Ticket: https://travisci.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=217
This PR:
- removes old signups tracking
- prevents manual visits to `/first_sync` page

As tracking improvement

---

app/styles/app/layouts/log.scss
app/styles/app/modules/logo.scss
app/utils/favicon-data-uris.js
package-lock.json
package.json

For https://travisci.assembla.com/spaces/Web/tickets/223/details

Resolve current npm audit security issues

---

app/routes/repo/index.js

This PR fixes a config tab badge for current build page

As fix config badge for current build

---

app/services/auth.js
app/services/storage.js

Another improvement for https://eu-app.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=217

Improve signups reporting

---

app/controllers/application.js
tests/acceptance/home/utm-test.js

An acceptance test for the UTM capturing added in https://github.com/travis-ci/travis-web/pull/2185

Add utm acceptance test

---

.env.example
app/app.js
app/components/profile-nav.js
app/mixins/route/owner/migrate.js
config/dotenv.js

For https://travisci.assembla.com/spaces/Enterprise/tickets/80/details

Hide Migrate tab in enterprise

---

app/services/auth.js
app/services/storage.js
server/index.js
waiter/lib/travis/web/set_token.rb

Issue: https://travisci.slack.com/archives/CA3FDF4MP/p1572376341133400
`become` is broken after auth refactoring.

Fix become authorization flow

---

app/utils/vcs.js
config/environment.js

Ticket: https://travisci.assembla.com/spaces/Enterprise/tickets/realtime_cardwall?ticket=77

Make vcs-related URLs configurable on Enterprise

---

app/models/owner.js
app/models/user.js
app/services/auth.js
app/templates/components/profile-nav.hbs

Reverts travis-ci/travis-web#2216

Revert "Missing first_sync page restored + UI beautification"

---

app/components/job-log.js
app/models/job.js
app/routes/job.js
app/services/store.js
package-lock.json
package.json
tests/test-helper.js

This eliminates the use of `didLoad` which throws deprecations currently

[CHORE] cleanup deprecations

---

tests/unit/services/polling-test.js

Previously this test could result in history occasionally being `model1, model2, model1 model1` for the final assert. This was because `setTimeout` does not guarantee when the callback is executed and in some situations the final callback was waiting long enough that two polling intervals were encountered instead of the expected one.
This refactor ensures we shut off polling as soon as we've polled model1 for the second time, and uses promise behavior to control the timing so that the polling interval can be shorter reducing the minimum time the test takes to run by 70-100ms.

[FIX] prevent race condition in polling test

---

Gemfile
Gemfile.lock
package-lock.json
package.json
server/index.js
waiter/lib/travis/web/set_token.rb

Ticket: https://travisci.assembla.com/spaces/Web/tickets/229-code-injection-in-web-login-form/details

As fix auth injection

---

app/services/auth.js

Addresses https://travisci.assembla.com/spaces/Web/tickets/238/details , which I noticed while doing some testing on another branch

Make auth fetchCurrentUser task keepLatest to prevent help error

---

app/styles/app/layouts/billing.scss
app/templates/components/billing/select-plan.hbs

Small PR to adjust plans selector contrast.

adjust plans contrast

---

app/components/caches-item.js
app/components/enterprise-banner.js
app/controllers/caches.js
app/models/job.js
app/models/request.js
app/models/user.js
app/routes/caches.js
app/routes/settings.js
app/services/ajax.js
app/services/api.js
app/services/tasks.js
app/utils/pusher.js
mirage/config.js

Reverts travis-ci/travis-web#2224
That PR inadvertently made the `Settings` tab unavailable.

Revert "Refactor ajax and api services to not use jquery"

---

app/components/build-header.js
app/templates/components/build-header.hbs

Remove jquery from build-header component

---

app/utils/time-ago-in-words.js
tests/acceptance/repo/settings-test.js

Refactor time-ago-in-words to not use jQuery

---

app/components/top-bar.js

Remove jquery usage from top-bar component

---

app/routes/application.js
app/routes/auth.js
app/routes/index.js
app/routes/not-found.js
app/routes/owner.js
app/routes/simple-layout.js
app/styles/app/layouts/top.scss
app/styles/app/modules/buttons.scss

Split from https://github.com/travis-ci/travis-web/pull/2203. A lot of these seem unused and unnecessary. The one that does seem to be used is in the `auth` route.

Remove jQuery used to set body class in routes

---

app/components/build-messages-list.js
app/components/build-tabs.js
app/components/job-tabs.js
app/mixins/components/with-config-validation.js
app/models/repo.js
app/routes/settings.js
app/templates/components/build-messages-list.hbs
app/templates/components/build-tabs.hbs
app/templates/components/job-tabs.hbs
tests/acceptance/config/yaml-test.js

Request: https://travisci.slack.com/archives/C1FAZPJNP/p1574955576001800

Refactor config validation logic, make it aware of feature state

---

app/components/billing/payment.js
app/components/billing/process.js

For: https://github.com/travis-pro/billing-v2/issues/372

Send coupon with billing payload

---

app/templates/components/billing-summary-status.hbs
tests/acceptance/profile/billing-test.js
tests/pages/profile.js

Resolves: https://github.com/travis-pro/billing-v2/issues/379

Fix marketplace status bug

---

app/components/billing/selected-plan.js
app/models/coupon.js
app/models/subscription.js
mirage/factories/coupon.js
tests/acceptance/profile/billing-test.js

PR to resolve: https://github.com/travis-pro/billing-v2/issues/377

Fix coupon deduction quirk

---

app/components/sync-button.js
app/models/owner.js
app/models/user.js
app/templates/components/profile-nav.hbs
app/utils/live-paginated-collection.js

For https://travisci.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=204

Refresh repos list after sync

---

app/models/vcs-entity.js
app/services/auth.js
app/utils/vcs.js
config/providers.js
ember-cli-build.js
package-lock.json
package.json
tests/unit/services/gtm-test.js
tests/unit/utils/vcs-test.js

[This PR](https://github.com/travis-ci/travis-web/pull/2318)'s mirror for demo

As metrics signup providers

---

app/components/account-token.js
app/controllers/account/settings.js
app/styles/app/layouts/profile.scss
app/templates/account/settings.hbs
app/templates/components/account-token.hbs
tests/acceptance/profile/view-token-test.js
tests/pages/profile.js

For: https://travisci.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=185

Add asset token to api authentication

---

app/components/requests-item.js
app/templates/components/requests-item.hbs

For: https://travisci.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=171

attempt to fix requests confusion

---

app/components/billing/address.js

For https://github.com/travis-pro/billing-v2/issues/394

show contact details error messages to user

---

app/utils/log.js
tests/acceptance/job/basic-layout-test.js

Fix for: https://eu-app.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=184

fix curl result

---

app/components/sales-contact-thanks.js
app/controllers/travisci-vs-jenkins/index.js
app/router.js
app/templates/components/sales-contact-thanks.hbs
app/templates/plans/thank-you.hbs
app/templates/travisci-vs-jenkins/index.hbs
app/templates/travisci-vs-jenkins/thank-you.hbs
tests/helpers/selectors.js

Part of https://github.com/travis-ci/travis-web/pull/2293
merges into epic branch
I noticed while testing this that on staging environments, the contact forms fail. This appears to be because the `travis-ci.org -- DEV` organization in Close has had its trial expire. The production test deployments work as expected, but the lead will go into the Close organization that production uses, so it's probably best to avoid that for now. I posted in slack about it, so that the relevant teams can discuss it.

[TVJ] add contact section

---

app/components/insights-overlay.js
app/components/multi-signin-button.js
app/styles/app/layouts/insights.scss
app/styles/app/modules/buttons.scss
app/styles/app/pages/help.scss
app/templates/components/insights-overlay.hbs
app/templates/components/multi-signin-button.hbs
app/templates/components/owner-not-found.hbs
app/templates/components/repo-not-found.hbs
app/templates/components/zendesk-request-form.hbs
app/templates/repo/active-on-org.hbs
config/tailwind.js
tests/acceptance/owner/insights-test.js
tests/integration/components/insights-overlay-test.js

I think this can just be a part of the signin PR.

So eliminate gh signin buttons

---

app/components/build-message.js

add duplicate_key message

---

app/styles/app/layouts/jobs.scss

Issue: https://travisci.slack.com/archives/C1FAZPJNP/p1582642773015700

Fix job-arch column overlap

---

app/services/auth.js
config/environment.js

Ticket: https://travisci.assembla.com/spaces/Web/tickets/279/details
Also requires API changes: https://github.com/travis-ci/travis-api/pull/1055

Fix intercom

---

app/services/auth.js

Just a little tweak for https://github.com/travis-ci/travis-web/pull/2369

As fix intercom

---

app/templates/components/billing-resubscribe-button.hbs
app/templates/components/billing/authorization.hbs
app/templates/components/billing/billing-details.hbs
app/templates/components/billing/contact-details.hbs
app/templates/components/billing/payment-details.hbs
app/templates/components/billing/summary.hbs

For: https://github.com/travis-pro/billing-v2/issues/450

hide inactive buttons

---

app/templates/plans/index.hbs

@Pezi777 I've moved some of the content around to incorporate enterprise and added some of the copy from the enterprise landing page - we'll have to decide if this is okay, if we need to add anything else or if it needs a rewrite.
@Montana if you could check things over from a syntax point of view to make sure I haven't broken anything that would be great!

Copied over the PDF link and some copy from the Enterprise landing page

---

app/components/build-header.js

follow up to https://github.com/travis-ci/travis-web/pull/2379

hide global env vars from build header

---

app/templates/components/repo-not-found.hbs
tests/acceptance/repo/not-found-test.js
tests/integration/components/repo-not-found-test.js

Ticket: https://travisci.assembla.com/spaces/VCS/tickets/142

Improve repo not found page messaging

---

app/components/log-content.js

Ticket: https://travisci.assembla.com/spaces/VCS/tickets/154/details

Disable log interaction when it's destroyed

---

app/templates/components/header-links.hbs

Ticket: https://github.com/travis-pro/billing-v2/issues/480

update enterprise link

---

app/models/repo.js
app/templates/components/build-header.hbs
app/templates/components/dashboard-row.hbs
app/templates/components/my-build.hbs
app/templates/components/owner-repo-tile.hbs
app/templates/components/repos-list-item.hbs
app/templates/components/repository-visibility-icon.hbs
public/images/stroke-icons/icon-shared.svg
tests/integration/components/build-header-test.js
tests/integration/components/dashboard-row-test.js
tests/integration/components/owner-repo-tile-test.js

https://travisci.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=278

Shared repository indicator

---

config/environment.js

I noticed that tests have been taking longer to complete lately. This PR is intended to address that.

Speed up tests requiring signin

---

app/templates/components/owner/repositories.hbs

For: https://travisci.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=293

Prevent activate from opening in a new tab

---

app/styles/app/layouts/owner.scss
app/styles/app/layouts/profile.scss
app/templates/components/github-apps-repository.hbs
app/templates/components/repository-visibility-icon.hbs

https://travisci.assembla.com/spaces/Web/tickets/realtime_cardwall?ticket=278

Shared icon moved in account/repositories

---

app/components/sales-contact-form.js

This is another attempt to improve sales form reporting.

Add utm parameters to pardot frame url

---

app/models/owner.js
app/styles/app/layouts/profile.scss
app/templates/components/billing/account.hbs
app/templates/components/billing/invoices.hbs
tests/integration/components/billing/invoices-test.js
tests/pages/profile.js

For: https://github.com/travis-pro/billing-v2/issues/506

Ep disable invoice download

---

.travis.yml
app/components/github-apps-repository.js
app/components/repo-show-tools.js
app/components/repository-sidebar.js
app/components/sales-contact-form.js
app/controllers/settings.js
app/models/owner.js
app/models/user.js
app/routes/settings.js
app/services/auth.js
app/services/job-state.js
app/services/permissions.js
app/services/pusher.js
app/services/repositories.js
app/services/tab-states.js
app/styles/app/layouts/profile.scss
app/templates/components/billing/account.hbs
app/templates/components/billing/invoices.hbs
app/templates/components/github-apps-repository.hbs
app/templates/components/repository-sidebar.hbs
tests/acceptance/home/sidebar-tabs-test.js
tests/acceptance/profile/basic-layout-test.js
tests/acceptance/repo/settings-test.js
tests/integration/components/add-ssh-key-test.js
tests/integration/components/billing/invoices-test.js
tests/integration/components/ssh-key-test.js
tests/pages/profile.js

* Make running jobs more consistent
* Refactor a bit
* Address feedback
* Simplify unfinished jobs CP

build docker image on each commit to master

---

app/services/feature-flags.js
config/environment.js

First step for gitlab updates.

[GL] Add gitlab flag

---

waiter/lib/travis/web/app.rb

Another attempt to fix env variable for waiter

Fix stripe config for waiter

---

app/services/auth.js

Fixing this issue: https://travisci.slack.com/archives/C7DRD496Y/p1587594597014300?thread_ts=1586856454.004700&cid=C7DRD496Y

Improve emails reporting for intercom

---

app/components/forms/form-field.js
app/components/travis-form.js
app/styles/app/modules/forms.scss
app/templates/components/forms/multiple-inputs-field.hbs

For https://github.com/travis-pro/billing-v2/issues/528

fix validation when no interaction with input

---

app/models/user.js

For https://travisci.assembla.com/spaces/Web/tickets/307-insufficient-permissions-at-repositories-list/details

reload permissions after sync

---

app/templates/components/repo-actions.hbs

In this PR, The button disables issue is now resolved.
Kindly Review
Rahul Garg

ITC-35 Disable Issue

---

app/components/repo-actions.js
app/styles/app/layouts/jobs.scss
app/templates/components/repo-actions.hbs

This PR is a design fix with respect to the open ticket: [Ticket 10](https://travisci.assembla.com/spaces/Build-Priorities_PRD/tickets/10-ie--ui-issue-----quot-prioritize-build-quot--icon-not-aligned-properly-in-the/details) as the complete UI is working as expected on other browsers but not on the IE 11 browser as it is unable to accommodate the extra prioritize button.
Kindly Review
Rahul Garg

ITC-35 IE 11 Bug Fix

---

app/styles/app/layouts/branches.scss
app/templates/components/created-by.hbs

Ticket: https://travisci.assembla.com/spaces/VCS/tickets/168

Fix long committer name overlap

---

waiter/config.ru
waiter/lib/travis/web/app.rb

This change should allow to set default provider via waiter in compiled app. @eugene-travis could you please check if it works in your setup? Thanks!

Add default provider config to waiter

---

app/models/user.js

Ticket: https://travisci.assembla.com/spaces/VCS/tickets/204

Update orgs after sync

---

package-lock.json
package.json

ref https://github.com/emberobserver/client/pull/190
ref https://github.com/emberjs/data/pull/7264
error - https://dev.azure.com/ember-data/emberjs/_build/results?buildId=4005&view=logs&j=0f730510-e886-53d0-e9ee-3135be6cf1a2&t=f73f74e7-ab42-5087-af50-a5b3a5b2b9a4

Dependencies: bump to latest ember-fetch to resolve latest whatwg global namespace issue

---

app/models/plan.js
app/router.js
app/styles/app/layouts/billing.scss
app/templates/components/billing/select-plan.hbs
app/templates/components/flashes/negative-balance-private.hbs
app/templates/components/flashes/negative-balance-public.hbs

Hello @artursmirnov 
This PR should fix the merged version of my previous PR and epic-pricing, since you mentioned that it didn't work. Also I've adjusted some icons in the plan selection page. Please take a look.

Fix plan page route

---

app/components/billing/payment.js
app/styles/app/layouts/billing.scss

Hello @artursmirnov , can you please take a look at this?

Poll subscription on plan change

---

app/components/billing/authorization.js
app/components/billing/payment.js
app/models/v2-subscription.js

Hello @artursmirnov 
Just a quick fix for the SCA card payments, please take a look.
P.S. pollSubscription removal is intentional, it is no longer needed

SCA card payment fix

---

app/components/billing/account.js
app/components/billing/authorization.js
app/components/billing/payment.js
app/components/billing/subscription.js
app/models/v2-subscription.js
app/services/stripe.js
app/templates/components/billing-resubscribe-button.hbs
app/templates/components/billing/account.hbs
app/templates/components/billing/authorization.hbs
app/templates/components/billing/education.hbs
app/templates/components/billing/process.hbs
app/templates/components/billing/subscription.hbs
app/templates/components/billing/summary.hbs
app/templates/components/billing/trial.hbs
tests/acceptance/profile/billing-test.js

Hello @artursmirnov !
A hotfix for migrating from a legacy plan to a new one.
I've also tried to fix the problem mentioned in the SCA fix, which turned out to be early task cancellation issue and is now working properly. Please take a look.

Plan migration fix

---

app/templates/components/billing/select-plan.hbs

Fix text for tooltip on free plan

Fix text for tooltip on free plan

---

app/templates/components/billing/oss-credit-toggle.hbs
app/templates/components/flashes/negative-balance-public.hbs
tests/acceptance/repo/allowance-test.js

Fix wording to avoid user confusion

Rename the toggle to reflect the function

---

app/templates/plans/index.hbs
tests/acceptance/plans-test.js

remove opensource section from plan page

remove opensource section from plan page

---

app/components/plan-usage.js

Plan usage csv fix

---

app/templates/components/billing/summary-v2.hbs

Removed text macOS for the annual plan

Removed text macOS for annual plan

---

app/models/plan.js
app/templates/plans/index.hbs
config/plans.js
tests/acceptance/plans-test.js

Added hybrid annual plans on the plan page

Added hybrid annual plans on the plan page

---

app/components/billing/oss-credit-toggle.js
app/controllers/account/settings.js
app/services/preferences.js
app/templates/components/billing/credit-balance.hbs
mirage/config.js

Maintenance milestone 2

---

app/components/dashboard-row.js
app/components/repo-actions.js
app/components/repository-layout.js
app/models/repo.js
app/templates/components/dashboard-row.hbs
app/templates/components/repo-actions.hbs
app/templates/components/repo-show-tools.hbs
tests/acceptance/repo/trigger-build-test.js

Fixes for read only mode

---

app/components/billing/postal-address.js
app/models/v2-billing-info.js
app/templates/components/billing/postal-address.hbs
app/utils/countries.js

Maintenance milestone 1

---

app/models/v2-subscription.js

Issue fixed oss credit next replenish date.

Issue fixed oss credit next replenish date

---

app/components/billing/address.js
app/components/billing/oss-credit-toggle.js
app/components/billing/postal-address.js
app/controllers/account/settings.js
app/models/v2-billing-info.js
app/services/preferences.js
app/templates/components/billing/credit-balance.hbs
app/templates/components/billing/postal-address.hbs
app/utils/countries.js
mirage/config.js

Epic maintenance prd 1

---

app/templates/components/migration-banner.hbs

Updated migration banner for .org

updated migration banner

---

app/templates/components/top-bar.hbs

Update logo URL, redirect to WordPress site

Update logo URL redirect to WordPress site

---

app/templates/components/billing/account.hbs
app/templates/components/billing/summary-v2.hbs

Remove Valid until badge for v2 manual subscriptions

Do not show v1 subscription if there is a v2 subscription

---

app/templates/components/billing/select-plan.hbs
tests/integration/components/billing/select-plan-test.js
tests/pages/profile.js

Removed extra details on plan page

improve plan page

---

app/templates/components/plan_usage.hbs

Hide user usage from plans without user licenses

---

app/adapters/billing-info.js
app/adapters/v2-billing-info.js
app/components/billing/address.js
app/components/plan-usage.js
app/models/invoice.js
app/templates/components/billing/invoices.hbs
app/templates/components/plan_usage.hbs
tests/acceptance/profile/billing-test.js
tests/integration/components/billing/invoices-test.js

Bugfix cycle 5

---

app/components/owner/repositories.js

management link fix for installation without logout/login

github apps management url update

---

app/templates/components/billing/information.hbs

Show banner for India based customer

show banner for India based customer

---

app/components/timeseries-chart.js
app/styles/app.scss
app/styles/app/layouts/travis-ci-insights/aggregate-matrices.scss
app/styles/app/layouts/travis-ci-insights/heatmap.scss
app/styles/app/layouts/travis-ci-insights/master-filter.scss
app/styles/app/layouts/travis-ci-insights/timeseries-chart.scss
app/styles/app/layouts/travis-ci-insights/travis-ci-insights.scss
app/templates/components/header-links.hbs
app/templates/components/timeseries-chart.hbs
app/templates/travis-ci-insights.hbs

Integration of UI components for Travis CI Insights.
1. Master Filter
2. Aggregation Metrices
3. Fusion Charts Metrices Trend
4. Heatmap

integration: spotlight ui components

---

app/templates/components/timeseries-chart.hbs
mirage/config.js
tests/integration/components/timeseries-chart-test.js

- Added Tim Series Charts Test Cases
- Added Mock API test Case

adding unit test cases insights timeseries

---

app/components/aggregate-matrices.js
app/components/master-filter.js
app/components/timeseries-chart.js
app/templates/components/aggregate-matrices.hbs
app/templates/components/master-filter.hbs
app/templates/components/timeseries-chart.hbs
app/templates/travis-ci-insights.hbs
tests/integration/components/aggregate-matrices-test.js

Integrating Master Filter with Aggregate Matrices

Travis web master filter integration

---

app/components/billing/select-plan.js
app/styles/app/layouts/billing.scss
app/templates/components/billing/select-plan.hbs
tests/acceptance/profile/billing-test.js
tests/integration/components/billing/select-plan-test.js

rollback hybrid plans on the web

hybrid plans shows on web

---

.env.example
app/routes/index.js
app/routes/plans.js
config/environment.js
waiter/config.ru

Use env vars for hardcoded links for redirections

Use env vars for hardcoded links for redirections

---

app/models/build.js
app/models/job.js
app/templates/components/build-header.hbs

Bug fix cycle 10

---

app/models/v2-plan-config.js
app/templates/components/plan_usage.hbs

[BSFY-162] Hide link to download user license usage CSV for standard tier plan and Pro tier plan

[BSFY-162] Hide link to download user license usage CSV for standard tier plan and Pro tier plan

---

app/templates/settings.hbs

Updated tooltips for disable job logs setting links

Update tooltips for job logs setting links

---

app/components/profile-nav.js
app/models/user.js
app/models/v2-plan-config.js
app/templates/components/plan_usage.hbs
app/templates/components/top-bar.hbs

Bug fix cycle 11

---

app/models/repo.js
app/routes/requests.js
app/services/pusher.js
app/templates/requests.hbs
tests/acceptance/repo/requests-test.js

* Fixed BSFY 178 and BSFY 179 (#2731)
* Fixed style issue
* Fixed tests

Bug fix cycle 13

---

app/components/modal.js
app/templates/components/repository-layout.hbs

https://travisci.assembla.com/spaces/Bugfix-Service/tickets/realtime_cardwall?ticket=180

Bsfy 180 fix

---

app/components/profile-nav.js
app/routes/organization/billing.js
app/routes/organization/plan_usage.js
app/templates/components/profile-nav.hbs
tests/acceptance/profile/billing-test.js

[Clickup Link](https://app.clickup.com/t/38a0p6u)
[Assembla ticket link](https://travisci.assembla.com/spaces/Bugfix-Service/tickets/realtime_cardwall?ticket=207)

Restrict non-admin users to access orgs plan details

---

app/models/user.js
app/services/auth.js
app/services/storage/auth.js
app/templates/account/settings.hbs
server/index.js
tests/helpers/sign-in-user.js
waiter/lib/travis/web/set_token.rb

Add RSS tokens

---

app/styles/app/layouts/error.scss

https://app.clickup.com/t/3a368ax
Fixed layout:

Change css to fix menu

---

app/models/organization.js
tests/acceptance/profile/user-settings-test.js

Cherry pick restarted by feature

Cherry pick restarted by feature

---

app/components/log-content.js

Moving log limit over to enterprise
https://github.com/travis-ci/travis-web/pull/2781/files

Added log limit using env var

---

waiter/lib/travis/web/app.rb

Fix for UI changing "Pull+Request" to "Pull Request"

Hot Fix - Pull Request UI tab

---

app/components/billing/first-plan.js
app/styles/app/layouts/activation.scss
app/templates/components/billing/first-plan.hbs

https://github.com/travis-ci/travis-web/pull/2796

bsfy 281 skip button for first plan

---

app/styles/app/layouts/profile.scss
app/templates/components/billing/summary-v2.hbs

[TBT-24](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=24) #2824

Release 240528

---

app/services/pusher.js

ticket: [TBT-45](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=45) PR: #2828

Release 20240605

---

app/components/add-custom-key.js
app/templates/components/add-custom-key.hbs
app/templates/components/custom-key.hbs

Ticket: [TBT-29](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/29-cosign-requires-update-to-newer-version--rsa-keys-are-no-longer-accepted-/details) PR: https://github.com/travis-ci/travis-web/pull/2834

Release 2024 06 11

---

app/:q
app/components/profile-nav.js
app/controllers/organization/settings.js
app/routes/organization/settings.js

Ticket: [TBT-48](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=48) PR: https://github.com/travis-ci/travis-web/pull/2833

Release 2024 06 13

---

app/components/billing/first-plan.js
app/templates/components/add-cron-job.hbs
app/templates/components/billing/first-plan.hbs
app/templates/components/forms/form-select.hbs

Ticket: [TBT-43](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=57), PR: https://github.com/travis-ci/travis-web/pull/2840
Ticket: [TBT-57](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=57), PR: https://github.com/travis-ci/travis-web/pull/2831

Release 2024 06 24

---

app/components/add-cron-job.js
app/styles/app/modules/travis-form.scss
app/templates/components/add-cron-job.hbs

Ticket: [TBT-1](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=1), PR: https://github.com/travis-ci/travis-web/pull/2842

Release 2024 07 10

---

app/components/billing/select-plan.js
app/models/v2-plan-config.js
app/styles/app/layouts/billing-plans.scss
app/templates/components/billing/first-plan.hbs
app/templates/components/billing/select-addon.hbs
app/templates/components/billing/select-plan.hbs
app/templates/components/billing/selected-plan.hbs
tests/integration/components/billing/select-plan-test.js

[PDTQ-160](https://travisci.assembla.com/spaces/Product-and-Dev-Tickets-Queue/tickets/160--pricing-adjustments--different-text-for-plan-selection-tiles-(usage-hybrid)/details?comment=1459451) [Pricing Adjustments] Different text for plan selection@nikolaTrichkovski
[TBT-41](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=41) Disallow downgrade plan WEB (#2825)
[PDTQ-159](https://travisci.assembla.com/spaces/Product-and-Dev-Tickets-Queue/tickets/realtime_cardwall?ticket=159) [Pricing adjustments] When there are no addons available for buy (#2850)

Release 2024 07 29

---

app/components/ask-travis.js
app/components/billing/authorization.js
app/styles/app/modules/asktravis.scss
app/templates/components/ask-travis.hbs
app/templates/components/billing/select-plan.hbs
tests/acceptance/profile/billing-test.js

[TBT-47](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=47) [HOT-FIX] remove dot (#2860)
[TBT-119](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=119) Add Ask Travis cloud message (#2855)
[TBT-35](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=35) change flash text (#2857)

Release 2024 07 31

---

app/components/billing/select-plan.js
app/templates/components/billing/select-plan.hbs

[Hotfix] Sort available plans

---

Dockerfile.tcie
Makefile
README.md
app/helpers/format-number.js
app/models/v2-plan-config.js
app/templates/components/billing/auto-refill.hbs
app/templates/components/billing/credit-balance.hbs
app/templates/components/billing/first-plan.hbs
app/templates/components/billing/select-addon.hbs
app/templates/components/billing/selected-plan.hbs
app/templates/components/top-bar.hbs
package-lock.json
scripts/k8s-build.sh
tests/acceptance/profile/billing-test.js
tests/integration/components/billing/select-addon-test.js

[PDTQ-162](https://travisci.assembla.com/spaces/Product-and-Dev-Tickets-Queue/tickets/realtime_cardwall?ticket=162) - [Pricing] usage based plans, "- check pricing"
[PDTQ-163](https://travisci.assembla.com/spaces/Product-and-Dev-Tickets-Queue/tickets/realtime_cardwall?ticket=163) - [Pricing] travis-web - everywhere on plans page format
[TBT-130](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=130) - Change "Ask Travis: intro to "Hey, I'm Travis"
[TBT-125](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=125) - Top left Travis-CI icon should not redirect to travis-ci.com
[TBT-112](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=112) - Placeholder: Redeploy Ask Travis after update

Release 2024 08 12

---

app/components/billing/authorization.js

Hotfix - display buy addon button for metered plans

Hotfix - display buy addon button for metered plans

---

app/adapters/v3.js
app/components/billing/authorization.js
app/components/billing/select-plan.js
app/components/owner/wizard.js
app/components/repository-sidebar.js
app/components/trigger-custom-build.js
app/controllers/account/settings.js
app/models/build.js
app/models/owner.js
app/models/repo.js
app/models/v2-plan-config.js
app/routes/account/settings.js
app/routes/dashboard/repositories.js
app/styles/app/layouts/billing.scss
app/templates/components/multi-signin-button.hbs
app/templates/components/owner/wizard.hbs
app/templates/components/page-footer.hbs
app/templates/signin.hbs
app/templates/signup.hbs
config/environment.js
config/providers.js
tests/acceptance/dashboard/repositories-test.js
tests/acceptance/repo/show-test.js

[HOT FIX] - display buy addon button for metered plans (#2847)
[HOT FIX] - sort plans on first-plan and when plan is expired for more than a month (#2875)
[HOT FIX] [PDTQ-162] - add underline for check price link (#2878)
[PDTQ-161] - [Pricing] 10M users in plan page in travis-web instead of 'unlimited' (#2874)
[TBT-139] - Change footer text from Contact to Support (#2873)
[TBT-96] - improvements for repos fetching (#2865)
[TBT-126] - wizard texts update (#2866)
[TBT-142] - Adjust Sign-Up Screen (#2876)

Release 2024 08 19

---

app/components/billing/first-plan.js
app/components/nav-logo.hbs
app/components/temporary-announcement-banner.js
app/styles/app/modules/buttons.scss
app/styles/app/modules/logo.scss
app/templates/components/billing/first-plan.hbs
app/templates/components/temporary-announcement-banner.hbs
app/templates/components/top-bar.hbs
config/environment.js
waiter/lib/travis/web/app.rb

[TBT-146] - The Travis CI Logo at the top left shouldn't be clickable or change when the mouse is hovered over it. (https://github.com/travis-ci/travis-web/pull/2881)
[TBT-117] - [Pricing adjustments] Switch trial plans to 2 week period instead of 1 month (https://github.com/travis-ci/travis-web/pull/2880) - continuation for configurable trial days (env TRIAL_DAYS) in web
[TBT-90] - [UX/UI] Cannot Remove Banner (or no option to) (https://github.com/travis-ci/travis-web/pull/2872)

Release 2024 08 26

---

Dockerfile

[TBT-112](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=112) build script v2 (#2887)

Release 2024 08 28

---

app/components/build-header.js
app/models/job.js
app/styles/app/layouts/billing-plans.scss
app/templates/components/build-header.hbs

[TBT-80](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=80) - vm size added in build info (#2885)
[TBT-163](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=163) - Select Plan Screen fix (#2886)

Release 2024 09 02

---

app/components/build-header.js
package-lock.json
package.json

[TBT-107](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=107) - User management window problems (https://github.com/travis-ci/travis-web/pull/2893)
Fix specs (https://github.com/travis-ci/travis-web/pull/2892)

Release 2024 09 05

---

app/components/billing/authorization.js
app/templates/components/billing/authorization.hbs
app/templates/components/billing/summary-v2.hbs
app/templates/components/billing/user-usage.hbs

[TBT-32](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=32) - Plan Page has graphics defects that should be fixed, PR: #2883

Release 2024 09 09

---

app/components/billing/authorization.js
app/styles/app/layouts/billing.scss
app/templates/components/billing/authorization.hbs
app/templates/components/billing/summary-v2.hbs
app/templates/components/billing/user-usage.hbs

revert wrong PR #2883 merge
[TBT-32] Stripe error display fix #2891

Fix release 2024 09 09

---

app/components/billing/summary-v2.js
app/components/billing/summary.js
app/templates/components/billing/summary-v2.hbs
app/templates/components/billing/summary.hbs
tests/acceptance/profile/billing-test.js
tests/integration/components/billing/summary-test.js
waiter/config.ru
waiter/lib/travis/web/app.rb

[TBT-180](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=180) - added missing env vars to waiter (#2889)
[TBT-190](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=190) - fix text for canceled plans and update expired for consistency (#2900)

Release 2024 09 18

---

waiter/config.ru
waiter/lib/travis/web/app.rb

Revert "[TBT-180] - added missing env vars to waiter (#2889)"

Release 2024 09 23

---

app/templates/components/flashes/negative-balance-public.hbs
tests/acceptance/repo/allowance-test.js

[[TBT-201]](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=201) update message for case when owner cannot build in public repo (#2905)

Release 2024 09 30

---

app/components/billing/summary-v2.js

[TBT-191](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=191) show subscription.validToFromAddon on subscription summary page (#2907)

Release 24 10 07

---

app/templates/components/no-repos.hbs

[PDTQ-175](https://travisci.assembla.com/spaces/Product-and-Dev-Tickets-Queue/tickets/175-word-correction-on-the-screen-/details) - Word correction on the screen(#2911)

Release 2024 10 14

---

app/components/plan-usage.js
app/styles/app/layouts/billing.scss
app/templates/components/plan_usage.hbs
tests/acceptance/profile/plan-usage-test.js

[TBT-192](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=192) - plan usage changes(#2912)

Release 2024 10 21

---

app/components/top-bar.js
app/styles/app/base.scss
app/styles/app/layouts/top.scss
app/styles/app/modules/navigation.scss

[TBT-144](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=144) - CSS styling of top according to design (#2916)

Release 2024 10 23

---

app/adapters/application.js
app/adapters/v3.js
app/components/account-token.js
app/controllers/github-apps-installation.js
app/models/user.js
app/services/api.js
app/services/auth.js
app/services/storage/auth.js
server/index.js
tests/acceptance/auth/automatic-sign-out-test.js
tests/helpers/sign-in-user.js
waiter/lib/travis/web/set_token.rb

[TBT-46](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=46) - Use web token for auth (#2909)

Release 2024 10 24

---

waiter/lib/travis/web/app.rb

Replaces [this](https://github.com/travis-ci/travis-web/pull/2903) PR to add an option for disabling Aida bot in enterprise

An option to disable the aida bot using env variable

---

app/components/billing/authorization.js
app/components/billing/current-trial.js
app/components/billing/first-plan.js
app/components/billing/select-plan.js
app/components/billing/selected-plan.js
app/components/billing/summary-v2.js
app/models/owner.js
app/models/v2-plan-config.js
app/models/v2-subscription.js
app/styles/app/layouts/billing.scss
app/templates/components/billing/current-trial.hbs
app/templates/components/billing/first-plan.hbs
app/templates/components/billing/select-plan.hbs
app/templates/components/billing/selected-plan.hbs
app/templates/components/billing/summary-v2.hbs
tests/acceptance/profile/billing-test.js
tests/integration/components/billing/information-test.js
tests/integration/components/billing/selected-plan-test.js

[TBT-156](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=156) - trials (#2908)
[TBT-161](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=161) -  [Onboarding] Free trial changes - travis-web changes

Release 2024 11 06

---

app/styles/app/layouts/log.scss
app/styles/app/layouts/top.scss
app/styles/app/modules/flash.scss
app/styles/app/modules/sync-button.scss

correct z-index of top class and add top property to flash messages

---

app/components/billing/authorization.js
app/components/billing/credit-balance.js
app/components/billing/first-plan.js
app/models/v2-plan-config.js
app/models/v2-subscription.js
app/templates/components/billing/authorization.hbs
app/templates/components/billing/credit-balance.hbs
app/templates/components/billing/first-plan.hbs
app/templates/components/billing/select-plan.hbs
tests/integration/components/billing/first-plan-test.js
tests/integration/components/billing/summary-v2-test.js
tests/pages/first-plan.js
tests/pages/profile.js

[TBT-34](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=34) - add deferPause attribute (#2924)
[TBT-232](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=232) - autorefill hidden for trials #2930

Release 24 11 27

---

app/components/billing/authorization.js
app/styles/app/layouts/billing.scss
app/templates/components/billing/authorization.hbs
app/templates/components/dialogs/cancel-subscription-confirmation-modal.hbs
tests/acceptance/profile/billing-test.js
tests/pages/profile.js

[TBT-235](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=235) - Create Cancellation Confirmation pop up (#2937)

Release 2024 12 30

---

waiter/lib/travis/web/app.rb

Temp banner

---

app/components/billing/summary-v2.js
app/routes/account.js
app/services/storage.js
app/utils/computed-is-current-trial.js
waiter/lib/travis/web/app.rb

[TBT-249](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=249) - Fix infinite update loop (#2942)
[TBT-250](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=250) - add check if subscription is null (#2943)
Temp banner fix (#2947)

Release 2024 12 31

---

app/components/temporary-announcement-banner.js
app/models/v2-plan-config.js

[PDTQ-187](https://travisci.assembla.com/p/ticket_list?tickets_report_id=filter%3A7&ticket=187&space=Product-and-Dev-Tickets-Queue) - fix plan description (#2953)
[TBT-265](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=265) - Close banner message (#2952)

Release 25 01 20

---

app/components/billing/credit-balance.js
app/components/billing/summary-v2.js
app/components/billing/summary.js
app/templates/components/billing/credit-balance.hbs
app/templates/components/billing/summary-v2.hbs
app/templates/components/billing/summary.hbs
app/utils/subtract-day.js
tests/acceptance/profile/billing-test.js
tests/integration/components/billing/summary-test.js
tests/integration/components/billing/summary-v2-test.js

[Tbt-267](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=267) - plan valid to fix (#2956)

Release 2025 01 27

---

app/controllers/builds.js
app/models/repo.js
mirage/api-spec.js
mirage/factories/repository.js
tests/acceptance/repo/build-list-routes-test.js

[TBT-276](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=276) - build count added (https://github.com/travis-ci/travis-api/pull/1357)

Release 2025.03.03

---

app/components/share-plan.js

[TBT-342] add expired/canceled condition for hasOwnPlan (#2980)

Release 2025 06 02

---

app/components/notification.js
app/styles/app/modules/flash.scss
app/styles/app/modules/notification.scss
app/styles/app/pages/landing.scss
app/templates/components/global-notification.hbs
app/templates/components/notification.hbs

TBT-375 Change flash banner position #2983
TBT-372 Fix global banner text alignment #2984

Release 2025 06 04

---

app/components/log-content.js
app/modifiers/on-page-resize.js
app/modifiers/on-page-scroll.js
app/styles/app/layouts/log.scss
app/styles/app/modules/buttons.scss
app/templates/components/log-content.hbs
tests/acceptance/builds/scrolling-test.js

[TBT-92] Log scroll buttons (#2989)

Release 2025 06 16

---

app/components/plan-usage.js
app/templates/components/plan_usage.hbs

[TBT 193] Csv export for plan usage (#2992)

Release 2025 07 01

---

app/components/plan-usage.js
app/templates/components/plan_usage.hbs

[Tbt 394](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=394) - join usage and license request csv in one (#2997)

Release 2025 07 09

---

app/components/billing/credit-balance.js
app/components/global-notification.js
app/router.js
app/routes/licensing.js
app/styles/app/layouts/content.scss
app/templates/components/billing/credit-balance.hbs
app/templates/components/negative-balance-private-and-public.hbs
app/templates/components/negative-balance-private.hbs
app/templates/components/negative-balance-public.hbs
app/templates/components/page-footer.hbs
app/templates/licensing.hbs
config/environment.js
tests/acceptance/licensing-test.js
tests/acceptance/repo/allowance-test.js
tests/integration/components/page-footer-test.js

- [TBT-378](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=378) - Credits section visibility fix (#2998)
- [TBT-77](https://travisci.assembla.com/spaces/TravisBaseTeam/tickets/realtime_cardwall?ticket=77) -  Open Source License page in app.travis-ci.com (#3005)

Release 2025 08 06
